/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  ApprovalRequestServiceApproveApprovalRequestBody,
  ChorusApproveApprovalRequestReply,
  ChorusCreateDataExtractionRequestReply,
  ChorusCreateDataExtractionRequestRequest,
  ChorusCreateDataTransferRequestReply,
  ChorusCreateDataTransferRequestRequest,
  ChorusDeleteApprovalRequestReply,
  ChorusDownloadApprovalRequestFileReply,
  ChorusGetApprovalRequestReply,
  ChorusListApprovalRequestsReply,
  RpcStatus
} from '../models/index'
import {
  ApprovalRequestServiceApproveApprovalRequestBodyFromJSON,
  ApprovalRequestServiceApproveApprovalRequestBodyToJSON,
  ChorusApproveApprovalRequestReplyFromJSON,
  ChorusApproveApprovalRequestReplyToJSON,
  ChorusCreateDataExtractionRequestReplyFromJSON,
  ChorusCreateDataExtractionRequestReplyToJSON,
  ChorusCreateDataExtractionRequestRequestFromJSON,
  ChorusCreateDataExtractionRequestRequestToJSON,
  ChorusCreateDataTransferRequestReplyFromJSON,
  ChorusCreateDataTransferRequestReplyToJSON,
  ChorusCreateDataTransferRequestRequestFromJSON,
  ChorusCreateDataTransferRequestRequestToJSON,
  ChorusDeleteApprovalRequestReplyFromJSON,
  ChorusDeleteApprovalRequestReplyToJSON,
  ChorusDownloadApprovalRequestFileReplyFromJSON,
  ChorusDownloadApprovalRequestFileReplyToJSON,
  ChorusGetApprovalRequestReplyFromJSON,
  ChorusGetApprovalRequestReplyToJSON,
  ChorusListApprovalRequestsReplyFromJSON,
  ChorusListApprovalRequestsReplyToJSON,
  RpcStatusFromJSON,
  RpcStatusToJSON
} from '../models/index'

export interface ApprovalRequestServiceApproveApprovalRequestRequest {
  id: string
  body: ApprovalRequestServiceApproveApprovalRequestBody
}

export interface ApprovalRequestServiceCreateDataExtractionRequestRequest {
  body: ChorusCreateDataExtractionRequestRequest
}

export interface ApprovalRequestServiceCreateDataTransferRequestRequest {
  body: ChorusCreateDataTransferRequestRequest
}

export interface ApprovalRequestServiceDeleteApprovalRequestRequest {
  id: string
}

export interface ApprovalRequestServiceDownloadApprovalRequestFileRequest {
  id: string
  path: string
}

export interface ApprovalRequestServiceGetApprovalRequestRequest {
  id: string
}

export interface ApprovalRequestServiceListApprovalRequestsRequest {
  paginationOffset?: number
  paginationLimit?: number
  paginationSortOrder?: string
  paginationSortType?: string
  paginationQuery?: Array<string>
  filterStatusesIn?: Array<ApprovalRequestServiceListApprovalRequestsFilterStatusesInEnum>
  filterTypesIn?: Array<ApprovalRequestServiceListApprovalRequestsFilterTypesInEnum>
  filterSourceWorkspaceId?: string
  filterPendingApproval?: boolean
}

/**
 *
 */
export class ApprovalRequestServiceApi extends runtime.BaseAPI {
  /**
   * This endpoint approves or rejects an approval request
   * Approve or reject an approval request
   */
  async approvalRequestServiceApproveApprovalRequestRaw(
    requestParameters: ApprovalRequestServiceApproveApprovalRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusApproveApprovalRequestReply>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling approvalRequestServiceApproveApprovalRequest.'
      )
    }

    if (
      requestParameters.body === null ||
      requestParameters.body === undefined
    ) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling approvalRequestServiceApproveApprovalRequest.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/approval-requests/{id}/approve`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ApprovalRequestServiceApproveApprovalRequestBodyToJSON(
          requestParameters.body
        )
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusApproveApprovalRequestReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint approves or rejects an approval request
   * Approve or reject an approval request
   */
  async approvalRequestServiceApproveApprovalRequest(
    requestParameters: ApprovalRequestServiceApproveApprovalRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusApproveApprovalRequestReply> {
    const response = await this.approvalRequestServiceApproveApprovalRequestRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint creates a data extraction approval request. Files are copied to a staging area for approval before extraction/download.
   * Create a data extraction request
   */
  async approvalRequestServiceCreateDataExtractionRequestRaw(
    requestParameters: ApprovalRequestServiceCreateDataExtractionRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusCreateDataExtractionRequestReply>> {
    if (
      requestParameters.body === null ||
      requestParameters.body === undefined
    ) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling approvalRequestServiceCreateDataExtractionRequest.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/approval-requests/data-extraction`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ChorusCreateDataExtractionRequestRequestToJSON(
          requestParameters.body
        )
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusCreateDataExtractionRequestReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint creates a data extraction approval request. Files are copied to a staging area for approval before extraction/download.
   * Create a data extraction request
   */
  async approvalRequestServiceCreateDataExtractionRequest(
    requestParameters: ApprovalRequestServiceCreateDataExtractionRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusCreateDataExtractionRequestReply> {
    const response =
      await this.approvalRequestServiceCreateDataExtractionRequestRaw(
        requestParameters,
        initOverrides
      )
    return await response.value()
  }

  /**
   * This endpoint creates a data transfer approval request. Files are copied to a staging area for approval before transfer to destination workspace.
   * Create a data transfer request
   */
  async approvalRequestServiceCreateDataTransferRequestRaw(
    requestParameters: ApprovalRequestServiceCreateDataTransferRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusCreateDataTransferRequestReply>> {
    if (
      requestParameters.body === null ||
      requestParameters.body === undefined
    ) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling approvalRequestServiceCreateDataTransferRequest.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/approval-requests/data-transfer`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ChorusCreateDataTransferRequestRequestToJSON(
          requestParameters.body
        )
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusCreateDataTransferRequestReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint creates a data transfer approval request. Files are copied to a staging area for approval before transfer to destination workspace.
   * Create a data transfer request
   */
  async approvalRequestServiceCreateDataTransferRequest(
    requestParameters: ApprovalRequestServiceCreateDataTransferRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusCreateDataTransferRequestReply> {
    const response =
      await this.approvalRequestServiceCreateDataTransferRequestRaw(
        requestParameters,
        initOverrides
      )
    return await response.value()
  }

  /**
   * This endpoint deletes an approval request. Only pending requests can be deleted.
   * Delete an approval request
   */
  async approvalRequestServiceDeleteApprovalRequestRaw(
    requestParameters: ApprovalRequestServiceDeleteApprovalRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusDeleteApprovalRequestReply>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling approvalRequestServiceDeleteApprovalRequest.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/approval-requests/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusDeleteApprovalRequestReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint deletes an approval request. Only pending requests can be deleted.
   * Delete an approval request
   */
  async approvalRequestServiceDeleteApprovalRequest(
    requestParameters: ApprovalRequestServiceDeleteApprovalRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusDeleteApprovalRequestReply> {
    const response = await this.approvalRequestServiceDeleteApprovalRequestRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint downloads a file from an approved data extraction request. Only the creator of the request can download files.
   * Download a file from an approved data extraction request
   */
  async approvalRequestServiceDownloadApprovalRequestFileRaw(
    requestParameters: ApprovalRequestServiceDownloadApprovalRequestFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusDownloadApprovalRequestFileReply>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling approvalRequestServiceDownloadApprovalRequestFile.'
      )
    }

    if (
      requestParameters.path === null ||
      requestParameters.path === undefined
    ) {
      throw new runtime.RequiredError(
        'path',
        'Required parameter requestParameters.path was null or undefined when calling approvalRequestServiceDownloadApprovalRequestFile.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/approval-requests/{id}/files/{path}`
          .replace(
            `{${'id'}}`,
            encodeURIComponent(String(requestParameters.id))
          )
          .replace(
            `{${'path'}}`,
            encodeURIComponent(String(requestParameters.path))
          ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusDownloadApprovalRequestFileReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint downloads a file from an approved data extraction request. Only the creator of the request can download files.
   * Download a file from an approved data extraction request
   */
  async approvalRequestServiceDownloadApprovalRequestFile(
    requestParameters: ApprovalRequestServiceDownloadApprovalRequestFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusDownloadApprovalRequestFileReply> {
    const response =
      await this.approvalRequestServiceDownloadApprovalRequestFileRaw(
        requestParameters,
        initOverrides
      )
    return await response.value()
  }

  /**
   * This endpoint returns an approval request
   * Get an approval request
   */
  async approvalRequestServiceGetApprovalRequestRaw(
    requestParameters: ApprovalRequestServiceGetApprovalRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusGetApprovalRequestReply>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling approvalRequestServiceGetApprovalRequest.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/approval-requests/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusGetApprovalRequestReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint returns an approval request
   * Get an approval request
   */
  async approvalRequestServiceGetApprovalRequest(
    requestParameters: ApprovalRequestServiceGetApprovalRequestRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusGetApprovalRequestReply> {
    const response = await this.approvalRequestServiceGetApprovalRequestRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint returns a list of approval requests
   * List approval requests
   */
  async approvalRequestServiceListApprovalRequestsRaw(
    requestParameters: ApprovalRequestServiceListApprovalRequestsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusListApprovalRequestsReply>> {
    const queryParameters: any = {}

    if (requestParameters.paginationOffset !== undefined) {
      queryParameters['pagination.offset'] = requestParameters.paginationOffset
    }

    if (requestParameters.paginationLimit !== undefined) {
      queryParameters['pagination.limit'] = requestParameters.paginationLimit
    }

    if (requestParameters.paginationSortOrder !== undefined) {
      queryParameters['pagination.sort.order'] =
        requestParameters.paginationSortOrder
    }

    if (requestParameters.paginationSortType !== undefined) {
      queryParameters['pagination.sort.type'] =
        requestParameters.paginationSortType
    }

    if (requestParameters.paginationQuery) {
      queryParameters['pagination.query'] = requestParameters.paginationQuery
    }

    if (requestParameters.filterStatusesIn) {
      queryParameters['filter.statusesIn'] = requestParameters.filterStatusesIn
    }

    if (requestParameters.filterTypesIn) {
      queryParameters['filter.typesIn'] = requestParameters.filterTypesIn
    }

    if (requestParameters.filterSourceWorkspaceId !== undefined) {
      queryParameters['filter.sourceWorkspaceId'] =
        requestParameters.filterSourceWorkspaceId
    }

    if (requestParameters.filterPendingApproval !== undefined) {
      queryParameters['filter.pendingApproval'] =
        requestParameters.filterPendingApproval
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/approval-requests`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusListApprovalRequestsReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint returns a list of approval requests
   * List approval requests
   */
  async approvalRequestServiceListApprovalRequests(
    requestParameters: ApprovalRequestServiceListApprovalRequestsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusListApprovalRequestsReply> {
    const response = await this.approvalRequestServiceListApprovalRequestsRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }
}

/**
 * @export
 */
export const ApprovalRequestServiceListApprovalRequestsFilterStatusesInEnum = {
  Unspecified: 'APPROVAL_REQUEST_STATUS_UNSPECIFIED',
  Pending: 'APPROVAL_REQUEST_STATUS_PENDING',
  Approved: 'APPROVAL_REQUEST_STATUS_APPROVED',
  Rejected: 'APPROVAL_REQUEST_STATUS_REJECTED',
  Cancelled: 'APPROVAL_REQUEST_STATUS_CANCELLED'
} as const
export type ApprovalRequestServiceListApprovalRequestsFilterStatusesInEnum =
  (typeof ApprovalRequestServiceListApprovalRequestsFilterStatusesInEnum)[keyof typeof ApprovalRequestServiceListApprovalRequestsFilterStatusesInEnum]
/**
 * @export
 */
export const ApprovalRequestServiceListApprovalRequestsFilterTypesInEnum = {
  Unspecified: 'APPROVAL_REQUEST_TYPE_UNSPECIFIED',
  DataExtraction: 'APPROVAL_REQUEST_TYPE_DATA_EXTRACTION',
  DataTransfer: 'APPROVAL_REQUEST_TYPE_DATA_TRANSFER'
} as const
export type ApprovalRequestServiceListApprovalRequestsFilterTypesInEnum =
  (typeof ApprovalRequestServiceListApprovalRequestsFilterTypesInEnum)[keyof typeof ApprovalRequestServiceListApprovalRequestsFilterTypesInEnum]
