/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  ChorusChorusErrorResponse,
  ChorusCreateDynamicRoleReply,
  ChorusCreateDynamicRoleRequest,
  ChorusListPermissionsReply,
  ChorusListRolesReply
} from '../models/index'
import {
  ChorusChorusErrorResponseFromJSON,
  ChorusChorusErrorResponseToJSON,
  ChorusCreateDynamicRoleReplyFromJSON,
  ChorusCreateDynamicRoleReplyToJSON,
  ChorusCreateDynamicRoleRequestFromJSON,
  ChorusCreateDynamicRoleRequestToJSON,
  ChorusListPermissionsReplyFromJSON,
  ChorusListPermissionsReplyToJSON,
  ChorusListRolesReplyFromJSON,
  ChorusListRolesReplyToJSON
} from '../models/index'

export interface AuthorizationServiceCreateDynamicRoleRequest {
  body: ChorusCreateDynamicRoleRequest
}

/**
 *
 */
export class AuthorizationServiceApi extends runtime.BaseAPI {
  /**
   * This endpoint creates a platform-scoped or workspace-scoped dynamic role
   * Create dynamic role
   */
  async authorizationServiceCreateDynamicRoleRaw(
    requestParameters: AuthorizationServiceCreateDynamicRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusCreateDynamicRoleReply>> {
    if (
      requestParameters.body === null ||
      requestParameters.body === undefined
    ) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling authorizationServiceCreateDynamicRole.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/authorization/roles`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ChorusCreateDynamicRoleRequestToJSON(requestParameters.body)
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusCreateDynamicRoleReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint creates a platform-scoped or workspace-scoped dynamic role
   * Create dynamic role
   */
  async authorizationServiceCreateDynamicRole(
    requestParameters: AuthorizationServiceCreateDynamicRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusCreateDynamicRoleReply> {
    const response = await this.authorizationServiceCreateDynamicRoleRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint returns a list of all available permissions
   * List permissions
   */
  async authorizationServiceListPermissionsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusListPermissionsReply>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/rest/v1/authorization/permissions`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusListPermissionsReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint returns a list of all available permissions
   * List permissions
   */
  async authorizationServiceListPermissions(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusListPermissionsReply> {
    const response =
      await this.authorizationServiceListPermissionsRaw(initOverrides)
    return await response.value()
  }

  /**
   * This endpoint returns a list of all available roles
   * List roles
   */
  async authorizationServiceListRolesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusListRolesReply>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/rest/v1/authorization/roles`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusListRolesReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint returns a list of all available roles
   * List roles
   */
  async authorizationServiceListRoles(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusListRolesReply> {
    const response = await this.authorizationServiceListRolesRaw(initOverrides)
    return await response.value()
  }
}
