/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  ChorusDeleteEntryReply,
  ChorusGetEntryReply,
  ChorusListEntriesReply,
  ChorusPutEntryReply,
  ChorusPutEntryRequest,
  DevstoreServicePutWorkspaceEntryBody,
  RpcStatus
} from '../models/index'
import {
  ChorusDeleteEntryReplyFromJSON,
  ChorusDeleteEntryReplyToJSON,
  ChorusGetEntryReplyFromJSON,
  ChorusGetEntryReplyToJSON,
  ChorusListEntriesReplyFromJSON,
  ChorusListEntriesReplyToJSON,
  ChorusPutEntryReplyFromJSON,
  ChorusPutEntryReplyToJSON,
  ChorusPutEntryRequestFromJSON,
  ChorusPutEntryRequestToJSON,
  DevstoreServicePutWorkspaceEntryBodyFromJSON,
  DevstoreServicePutWorkspaceEntryBodyToJSON,
  RpcStatusFromJSON,
  RpcStatusToJSON
} from '../models/index'

export interface DevstoreServiceDeleteGlobalEntryRequest {
  key: string
}

export interface DevstoreServiceDeleteUserEntryRequest {
  key: string
}

export interface DevstoreServiceDeleteWorkspaceEntryRequest {
  id: string
  key: string
}

export interface DevstoreServiceGetGlobalEntryRequest {
  key: string
}

export interface DevstoreServiceGetUserEntryRequest {
  key: string
}

export interface DevstoreServiceGetWorkspaceEntryRequest {
  id: string
  key: string
}

export interface DevstoreServiceListWorkspaceEntriesRequest {
  id: string
}

export interface DevstoreServicePutGlobalEntryRequest {
  body: ChorusPutEntryRequest
}

export interface DevstoreServicePutUserEntryRequest {
  body: ChorusPutEntryRequest
}

export interface DevstoreServicePutWorkspaceEntryRequest {
  id: string
  body: DevstoreServicePutWorkspaceEntryBody
}

/**
 *
 */
export class DevstoreServiceApi extends runtime.BaseAPI {
  /**
   * This endpoint deletes a key/value entry from the global store by key
   * Delete a key/value entry from the global store
   */
  async devstoreServiceDeleteGlobalEntryRaw(
    requestParameters: DevstoreServiceDeleteGlobalEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusDeleteEntryReply>> {
    if (requestParameters.key === null || requestParameters.key === undefined) {
      throw new runtime.RequiredError(
        'key',
        'Required parameter requestParameters.key was null or undefined when calling devstoreServiceDeleteGlobalEntry.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/global/{key}`.replace(
          `{${'key'}}`,
          encodeURIComponent(String(requestParameters.key))
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusDeleteEntryReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint deletes a key/value entry from the global store by key
   * Delete a key/value entry from the global store
   */
  async devstoreServiceDeleteGlobalEntry(
    requestParameters: DevstoreServiceDeleteGlobalEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusDeleteEntryReply> {
    const response = await this.devstoreServiceDeleteGlobalEntryRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint deletes a key/value entry from the user store by key
   * Delete a key/value entry from the user store
   */
  async devstoreServiceDeleteUserEntryRaw(
    requestParameters: DevstoreServiceDeleteUserEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusDeleteEntryReply>> {
    if (requestParameters.key === null || requestParameters.key === undefined) {
      throw new runtime.RequiredError(
        'key',
        'Required parameter requestParameters.key was null or undefined when calling devstoreServiceDeleteUserEntry.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/user/{key}`.replace(
          `{${'key'}}`,
          encodeURIComponent(String(requestParameters.key))
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusDeleteEntryReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint deletes a key/value entry from the user store by key
   * Delete a key/value entry from the user store
   */
  async devstoreServiceDeleteUserEntry(
    requestParameters: DevstoreServiceDeleteUserEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusDeleteEntryReply> {
    const response = await this.devstoreServiceDeleteUserEntryRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint deletes a key/value entry from the workspace store by key
   * Delete a key/value entry from the workspace store
   */
  async devstoreServiceDeleteWorkspaceEntryRaw(
    requestParameters: DevstoreServiceDeleteWorkspaceEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusDeleteEntryReply>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling devstoreServiceDeleteWorkspaceEntry.'
      )
    }

    if (requestParameters.key === null || requestParameters.key === undefined) {
      throw new runtime.RequiredError(
        'key',
        'Required parameter requestParameters.key was null or undefined when calling devstoreServiceDeleteWorkspaceEntry.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/workspace/{id}/{key}`
          .replace(
            `{${'id'}}`,
            encodeURIComponent(String(requestParameters.id))
          )
          .replace(
            `{${'key'}}`,
            encodeURIComponent(String(requestParameters.key))
          ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusDeleteEntryReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint deletes a key/value entry from the workspace store by key
   * Delete a key/value entry from the workspace store
   */
  async devstoreServiceDeleteWorkspaceEntry(
    requestParameters: DevstoreServiceDeleteWorkspaceEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusDeleteEntryReply> {
    const response = await this.devstoreServiceDeleteWorkspaceEntryRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint retrieves a key/value entry from the global store by key
   * Get a key/value entry from the global store
   */
  async devstoreServiceGetGlobalEntryRaw(
    requestParameters: DevstoreServiceGetGlobalEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusGetEntryReply>> {
    if (requestParameters.key === null || requestParameters.key === undefined) {
      throw new runtime.RequiredError(
        'key',
        'Required parameter requestParameters.key was null or undefined when calling devstoreServiceGetGlobalEntry.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/global/{key}`.replace(
          `{${'key'}}`,
          encodeURIComponent(String(requestParameters.key))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusGetEntryReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint retrieves a key/value entry from the global store by key
   * Get a key/value entry from the global store
   */
  async devstoreServiceGetGlobalEntry(
    requestParameters: DevstoreServiceGetGlobalEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusGetEntryReply> {
    const response = await this.devstoreServiceGetGlobalEntryRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint retrieves a key/value entry from the user store by key
   * Get a key/value entry from the user store
   */
  async devstoreServiceGetUserEntryRaw(
    requestParameters: DevstoreServiceGetUserEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusGetEntryReply>> {
    if (requestParameters.key === null || requestParameters.key === undefined) {
      throw new runtime.RequiredError(
        'key',
        'Required parameter requestParameters.key was null or undefined when calling devstoreServiceGetUserEntry.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/user/{key}`.replace(
          `{${'key'}}`,
          encodeURIComponent(String(requestParameters.key))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusGetEntryReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint retrieves a key/value entry from the user store by key
   * Get a key/value entry from the user store
   */
  async devstoreServiceGetUserEntry(
    requestParameters: DevstoreServiceGetUserEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusGetEntryReply> {
    const response = await this.devstoreServiceGetUserEntryRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint retrieves a key/value entry from the workspace store by key
   * Get a key/value entry from the workspace store
   */
  async devstoreServiceGetWorkspaceEntryRaw(
    requestParameters: DevstoreServiceGetWorkspaceEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusGetEntryReply>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling devstoreServiceGetWorkspaceEntry.'
      )
    }

    if (requestParameters.key === null || requestParameters.key === undefined) {
      throw new runtime.RequiredError(
        'key',
        'Required parameter requestParameters.key was null or undefined when calling devstoreServiceGetWorkspaceEntry.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/workspace/{id}/{key}`
          .replace(
            `{${'id'}}`,
            encodeURIComponent(String(requestParameters.id))
          )
          .replace(
            `{${'key'}}`,
            encodeURIComponent(String(requestParameters.key))
          ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusGetEntryReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint retrieves a key/value entry from the workspace store by key
   * Get a key/value entry from the workspace store
   */
  async devstoreServiceGetWorkspaceEntry(
    requestParameters: DevstoreServiceGetWorkspaceEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusGetEntryReply> {
    const response = await this.devstoreServiceGetWorkspaceEntryRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint retrieves all key/value entries from the global store
   * List all key/value entries in the global store
   */
  async devstoreServiceListGlobalEntriesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusListEntriesReply>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/global`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusListEntriesReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint retrieves all key/value entries from the global store
   * List all key/value entries in the global store
   */
  async devstoreServiceListGlobalEntries(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusListEntriesReply> {
    const response =
      await this.devstoreServiceListGlobalEntriesRaw(initOverrides)
    return await response.value()
  }

  /**
   * This endpoint retrieves all key/value entries from the user store
   * List all key/value entries in the user store
   */
  async devstoreServiceListUserEntriesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusListEntriesReply>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/user`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusListEntriesReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint retrieves all key/value entries from the user store
   * List all key/value entries in the user store
   */
  async devstoreServiceListUserEntries(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusListEntriesReply> {
    const response = await this.devstoreServiceListUserEntriesRaw(initOverrides)
    return await response.value()
  }

  /**
   * This endpoint retrieves all key/value entries from the workspace store
   * List all key/value entries in the workspace store
   */
  async devstoreServiceListWorkspaceEntriesRaw(
    requestParameters: DevstoreServiceListWorkspaceEntriesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusListEntriesReply>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling devstoreServiceListWorkspaceEntries.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/workspace/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusListEntriesReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint retrieves all key/value entries from the workspace store
   * List all key/value entries in the workspace store
   */
  async devstoreServiceListWorkspaceEntries(
    requestParameters: DevstoreServiceListWorkspaceEntriesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusListEntriesReply> {
    const response = await this.devstoreServiceListWorkspaceEntriesRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint allows to put a key/value entry in the dev global store
   * Put a key/value entry in the dev global store
   */
  async devstoreServicePutGlobalEntryRaw(
    requestParameters: DevstoreServicePutGlobalEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusPutEntryReply>> {
    if (
      requestParameters.body === null ||
      requestParameters.body === undefined
    ) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling devstoreServicePutGlobalEntry.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/global`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ChorusPutEntryRequestToJSON(requestParameters.body)
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusPutEntryReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint allows to put a key/value entry in the dev global store
   * Put a key/value entry in the dev global store
   */
  async devstoreServicePutGlobalEntry(
    requestParameters: DevstoreServicePutGlobalEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusPutEntryReply> {
    const response = await this.devstoreServicePutGlobalEntryRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint allows to put a key/value entry in the dev user store
   * Put a key/value entry in the dev user store
   */
  async devstoreServicePutUserEntryRaw(
    requestParameters: DevstoreServicePutUserEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusPutEntryReply>> {
    if (
      requestParameters.body === null ||
      requestParameters.body === undefined
    ) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling devstoreServicePutUserEntry.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/user`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ChorusPutEntryRequestToJSON(requestParameters.body)
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusPutEntryReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint allows to put a key/value entry in the dev user store
   * Put a key/value entry in the dev user store
   */
  async devstoreServicePutUserEntry(
    requestParameters: DevstoreServicePutUserEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusPutEntryReply> {
    const response = await this.devstoreServicePutUserEntryRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint allows to put a key/value entry in the dev workspace store
   * Put a key/value entry in the dev workspace store
   */
  async devstoreServicePutWorkspaceEntryRaw(
    requestParameters: DevstoreServicePutWorkspaceEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusPutEntryReply>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling devstoreServicePutWorkspaceEntry.'
      )
    }

    if (
      requestParameters.body === null ||
      requestParameters.body === undefined
    ) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling devstoreServicePutWorkspaceEntry.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/api/rest/v1/devstore/workspace/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: DevstoreServicePutWorkspaceEntryBodyToJSON(requestParameters.body)
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusPutEntryReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint allows to put a key/value entry in the dev workspace store
   * Put a key/value entry in the dev workspace store
   */
  async devstoreServicePutWorkspaceEntry(
    requestParameters: DevstoreServicePutWorkspaceEntryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusPutEntryReply> {
    const response = await this.devstoreServicePutWorkspaceEntryRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }
}
