/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  ApiHttpBody,
  ChorusChorusErrorResponse,
  ChorusCreateOrganizationReply,
  ChorusDeleteOrganizationReply,
  ChorusGetOrganizationReply,
  ChorusListOrganizationsReply,
  ChorusOrganization,
  ChorusUpdateOrganizationReply,
  OrganizationServiceUpdateOrganizationBody
} from '../models/index'
import {
  ApiHttpBodyFromJSON,
  ApiHttpBodyToJSON,
  ChorusChorusErrorResponseFromJSON,
  ChorusChorusErrorResponseToJSON,
  ChorusCreateOrganizationReplyFromJSON,
  ChorusCreateOrganizationReplyToJSON,
  ChorusDeleteOrganizationReplyFromJSON,
  ChorusDeleteOrganizationReplyToJSON,
  ChorusGetOrganizationReplyFromJSON,
  ChorusGetOrganizationReplyToJSON,
  ChorusListOrganizationsReplyFromJSON,
  ChorusListOrganizationsReplyToJSON,
  ChorusOrganizationFromJSON,
  ChorusOrganizationToJSON,
  ChorusUpdateOrganizationReplyFromJSON,
  ChorusUpdateOrganizationReplyToJSON,
  OrganizationServiceUpdateOrganizationBodyFromJSON,
  OrganizationServiceUpdateOrganizationBodyToJSON
} from '../models/index'

export interface OrganizationServiceCreateOrganizationRequest {
  body: ChorusOrganization
}

export interface OrganizationServiceDeleteOrganizationRequest {
  id: string
}

export interface OrganizationServiceGetOrganizationRequest {
  id: string
}

export interface OrganizationServiceGetOrganizationLogoRequest {
  id: string
}

export interface OrganizationServiceListOrganizationsRequest {
  paginationOffset?: number
  paginationLimit?: number
  paginationSortOrder?: string
  paginationSortType?: string
  paginationQuery?: Array<string>
}

export interface OrganizationServiceUpdateOrganizationRequest {
  id: string
  body: OrganizationServiceUpdateOrganizationBody
}

/**
 *
 */
export class OrganizationServiceApi extends runtime.BaseAPI {
  /**
   * This endpoint creates an organization. Requires the PlatformOrganizationManager role.
   * Create an organization
   */
  async organizationServiceCreateOrganizationRaw(
    requestParameters: OrganizationServiceCreateOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusCreateOrganizationReply>> {
    if (
      requestParameters.body === null ||
      requestParameters.body === undefined
    ) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling organizationServiceCreateOrganization.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/organizations`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ChorusOrganizationToJSON(requestParameters.body)
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusCreateOrganizationReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint creates an organization. Requires the PlatformOrganizationManager role.
   * Create an organization
   */
  async organizationServiceCreateOrganization(
    requestParameters: OrganizationServiceCreateOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusCreateOrganizationReply> {
    const response = await this.organizationServiceCreateOrganizationRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint soft-deletes an organization. Requires the PlatformOrganizationManager role.
   * Delete an organization
   */
  async organizationServiceDeleteOrganizationRaw(
    requestParameters: OrganizationServiceDeleteOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusDeleteOrganizationReply>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling organizationServiceDeleteOrganization.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/organizations/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusDeleteOrganizationReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint soft-deletes an organization. Requires the PlatformOrganizationManager role.
   * Delete an organization
   */
  async organizationServiceDeleteOrganization(
    requestParameters: OrganizationServiceDeleteOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusDeleteOrganizationReply> {
    const response = await this.organizationServiceDeleteOrganizationRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint returns an organization\'s details, excluding the logo image data
   * Get an organization
   */
  async organizationServiceGetOrganizationRaw(
    requestParameters: OrganizationServiceGetOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusGetOrganizationReply>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling organizationServiceGetOrganization.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/organizations/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusGetOrganizationReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint returns an organization\'s details, excluding the logo image data
   * Get an organization
   */
  async organizationServiceGetOrganization(
    requestParameters: OrganizationServiceGetOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusGetOrganizationReply> {
    const response = await this.organizationServiceGetOrganizationRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint returns the raw logo image bytes with Content-Type and Cache-Control headers, suitable for direct use as an <img> src
   * Get an organization\'s logo
   */
  async organizationServiceGetOrganizationLogoRaw(
    requestParameters: OrganizationServiceGetOrganizationLogoRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ApiHttpBody>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling organizationServiceGetOrganizationLogo.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/organizations/{id}/logo`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ApiHttpBodyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint returns the raw logo image bytes with Content-Type and Cache-Control headers, suitable for direct use as an <img> src
   * Get an organization\'s logo
   */
  async organizationServiceGetOrganizationLogo(
    requestParameters: OrganizationServiceGetOrganizationLogoRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ApiHttpBody> {
    const response = await this.organizationServiceGetOrganizationLogoRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint returns a list of active organizations
   * List organizations
   */
  async organizationServiceListOrganizationsRaw(
    requestParameters: OrganizationServiceListOrganizationsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusListOrganizationsReply>> {
    const queryParameters: any = {}

    if (requestParameters.paginationOffset !== undefined) {
      queryParameters['pagination.offset'] = requestParameters.paginationOffset
    }

    if (requestParameters.paginationLimit !== undefined) {
      queryParameters['pagination.limit'] = requestParameters.paginationLimit
    }

    if (requestParameters.paginationSortOrder !== undefined) {
      queryParameters['pagination.sort.order'] =
        requestParameters.paginationSortOrder
    }

    if (requestParameters.paginationSortType !== undefined) {
      queryParameters['pagination.sort.type'] =
        requestParameters.paginationSortType
    }

    if (requestParameters.paginationQuery) {
      queryParameters['pagination.query'] = requestParameters.paginationQuery
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/organizations`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusListOrganizationsReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint returns a list of active organizations
   * List organizations
   */
  async organizationServiceListOrganizations(
    requestParameters: OrganizationServiceListOrganizationsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusListOrganizationsReply> {
    const response = await this.organizationServiceListOrganizationsRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint updates an organization. Requires the PlatformOrganizationManager role.
   * Update an organization
   */
  async organizationServiceUpdateOrganizationRaw(
    requestParameters: OrganizationServiceUpdateOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusUpdateOrganizationReply>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter requestParameters.id was null or undefined when calling organizationServiceUpdateOrganization.'
      )
    }

    if (
      requestParameters.body === null ||
      requestParameters.body === undefined
    ) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter requestParameters.body was null or undefined when calling organizationServiceUpdateOrganization.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/organizations/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: OrganizationServiceUpdateOrganizationBodyToJSON(
          requestParameters.body
        )
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusUpdateOrganizationReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint updates an organization. Requires the PlatformOrganizationManager role.
   * Update an organization
   */
  async organizationServiceUpdateOrganization(
    requestParameters: OrganizationServiceUpdateOrganizationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusUpdateOrganizationReply> {
    const response = await this.organizationServiceUpdateOrganizationRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }
}
