/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  ChorusCreateWorkspaceFileReply,
  ChorusDeleteWorkspaceFileReply,
  ChorusGetWorkspaceFileReply,
  ChorusListWorkspaceFilesReply,
  ChorusUpdateWorkspaceFileReply,
  ChorusWorkspaceFile,
  RpcStatus
} from '../models/index'
import {
  ChorusCreateWorkspaceFileReplyFromJSON,
  ChorusCreateWorkspaceFileReplyToJSON,
  ChorusDeleteWorkspaceFileReplyFromJSON,
  ChorusDeleteWorkspaceFileReplyToJSON,
  ChorusGetWorkspaceFileReplyFromJSON,
  ChorusGetWorkspaceFileReplyToJSON,
  ChorusListWorkspaceFilesReplyFromJSON,
  ChorusListWorkspaceFilesReplyToJSON,
  ChorusUpdateWorkspaceFileReplyFromJSON,
  ChorusUpdateWorkspaceFileReplyToJSON,
  ChorusWorkspaceFileFromJSON,
  ChorusWorkspaceFileToJSON,
  RpcStatusFromJSON,
  RpcStatusToJSON
} from '../models/index'

export interface WorkspaceFileServiceCreateWorkspaceFileRequest {
  workspaceId: string
  file: ChorusWorkspaceFile
}

export interface WorkspaceFileServiceDeleteWorkspaceFileRequest {
  workspaceId: string
  path: string
}

export interface WorkspaceFileServiceGetWorkspaceFileRequest {
  workspaceId: string
  path: string
}

export interface WorkspaceFileServiceListWorkspaceFilesRequest {
  workspaceId: string
  path: string
}

export interface WorkspaceFileServiceUpdateWorkspaceFileRequest {
  workspaceId: string
  oldPath: string
  file: ChorusWorkspaceFile
}

/**
 *
 */
export class WorkspaceFileServiceApi extends runtime.BaseAPI {
  /**
   * This endpoint creates a file in a workspace at the specified path
   * Create a file in a workspace
   */
  async workspaceFileServiceCreateWorkspaceFileRaw(
    requestParameters: WorkspaceFileServiceCreateWorkspaceFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusCreateWorkspaceFileReply>> {
    if (
      requestParameters.workspaceId === null ||
      requestParameters.workspaceId === undefined
    ) {
      throw new runtime.RequiredError(
        'workspaceId',
        'Required parameter requestParameters.workspaceId was null or undefined when calling workspaceFileServiceCreateWorkspaceFile.'
      )
    }

    if (
      requestParameters.file === null ||
      requestParameters.file === undefined
    ) {
      throw new runtime.RequiredError(
        'file',
        'Required parameter requestParameters.file was null or undefined when calling workspaceFileServiceCreateWorkspaceFile.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/workspaces/{workspaceId}/file`.replace(
          `{${'workspaceId'}}`,
          encodeURIComponent(String(requestParameters.workspaceId))
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ChorusWorkspaceFileToJSON(requestParameters.file)
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusCreateWorkspaceFileReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint creates a file in a workspace at the specified path
   * Create a file in a workspace
   */
  async workspaceFileServiceCreateWorkspaceFile(
    requestParameters: WorkspaceFileServiceCreateWorkspaceFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusCreateWorkspaceFileReply> {
    const response = await this.workspaceFileServiceCreateWorkspaceFileRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint deletes a file in a workspace at the specified path
   * Delete a file in a workspace
   */
  async workspaceFileServiceDeleteWorkspaceFileRaw(
    requestParameters: WorkspaceFileServiceDeleteWorkspaceFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusDeleteWorkspaceFileReply>> {
    if (
      requestParameters.workspaceId === null ||
      requestParameters.workspaceId === undefined
    ) {
      throw new runtime.RequiredError(
        'workspaceId',
        'Required parameter requestParameters.workspaceId was null or undefined when calling workspaceFileServiceDeleteWorkspaceFile.'
      )
    }

    if (
      requestParameters.path === null ||
      requestParameters.path === undefined
    ) {
      throw new runtime.RequiredError(
        'path',
        'Required parameter requestParameters.path was null or undefined when calling workspaceFileServiceDeleteWorkspaceFile.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/workspaces/{workspaceId}/file/{path}`
          .replace(
            `{${'workspaceId'}}`,
            encodeURIComponent(String(requestParameters.workspaceId))
          )
          .replace(
            `{${'path'}}`,
            encodeURIComponent(String(requestParameters.path))
          ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusDeleteWorkspaceFileReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint deletes a file in a workspace at the specified path
   * Delete a file in a workspace
   */
  async workspaceFileServiceDeleteWorkspaceFile(
    requestParameters: WorkspaceFileServiceDeleteWorkspaceFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusDeleteWorkspaceFileReply> {
    const response = await this.workspaceFileServiceDeleteWorkspaceFileRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint retrieves a file at the specified path within a workspace
   * Get a file in a workspace
   */
  async workspaceFileServiceGetWorkspaceFileRaw(
    requestParameters: WorkspaceFileServiceGetWorkspaceFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusGetWorkspaceFileReply>> {
    if (
      requestParameters.workspaceId === null ||
      requestParameters.workspaceId === undefined
    ) {
      throw new runtime.RequiredError(
        'workspaceId',
        'Required parameter requestParameters.workspaceId was null or undefined when calling workspaceFileServiceGetWorkspaceFile.'
      )
    }

    if (
      requestParameters.path === null ||
      requestParameters.path === undefined
    ) {
      throw new runtime.RequiredError(
        'path',
        'Required parameter requestParameters.path was null or undefined when calling workspaceFileServiceGetWorkspaceFile.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/workspaces/{workspaceId}/file/{path}`
          .replace(
            `{${'workspaceId'}}`,
            encodeURIComponent(String(requestParameters.workspaceId))
          )
          .replace(
            `{${'path'}}`,
            encodeURIComponent(String(requestParameters.path))
          ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusGetWorkspaceFileReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint retrieves a file at the specified path within a workspace
   * Get a file in a workspace
   */
  async workspaceFileServiceGetWorkspaceFile(
    requestParameters: WorkspaceFileServiceGetWorkspaceFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusGetWorkspaceFileReply> {
    const response = await this.workspaceFileServiceGetWorkspaceFileRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint lists all files at given path within a workspace
   * List files in a workspace at a specified path
   */
  async workspaceFileServiceListWorkspaceFilesRaw(
    requestParameters: WorkspaceFileServiceListWorkspaceFilesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusListWorkspaceFilesReply>> {
    if (
      requestParameters.workspaceId === null ||
      requestParameters.workspaceId === undefined
    ) {
      throw new runtime.RequiredError(
        'workspaceId',
        'Required parameter requestParameters.workspaceId was null or undefined when calling workspaceFileServiceListWorkspaceFiles.'
      )
    }

    if (
      requestParameters.path === null ||
      requestParameters.path === undefined
    ) {
      throw new runtime.RequiredError(
        'path',
        'Required parameter requestParameters.path was null or undefined when calling workspaceFileServiceListWorkspaceFiles.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/workspaces/{workspaceId}/files/{path}`
          .replace(
            `{${'workspaceId'}}`,
            encodeURIComponent(String(requestParameters.workspaceId))
          )
          .replace(
            `{${'path'}}`,
            encodeURIComponent(String(requestParameters.path))
          ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusListWorkspaceFilesReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint lists all files at given path within a workspace
   * List files in a workspace at a specified path
   */
  async workspaceFileServiceListWorkspaceFiles(
    requestParameters: WorkspaceFileServiceListWorkspaceFilesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusListWorkspaceFilesReply> {
    const response = await this.workspaceFileServiceListWorkspaceFilesRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }

  /**
   * This endpoint updates (rename or moves) a file in a workspace at the specified path
   * Update a file in a workspace
   */
  async workspaceFileServiceUpdateWorkspaceFileRaw(
    requestParameters: WorkspaceFileServiceUpdateWorkspaceFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ChorusUpdateWorkspaceFileReply>> {
    if (
      requestParameters.workspaceId === null ||
      requestParameters.workspaceId === undefined
    ) {
      throw new runtime.RequiredError(
        'workspaceId',
        'Required parameter requestParameters.workspaceId was null or undefined when calling workspaceFileServiceUpdateWorkspaceFile.'
      )
    }

    if (
      requestParameters.oldPath === null ||
      requestParameters.oldPath === undefined
    ) {
      throw new runtime.RequiredError(
        'oldPath',
        'Required parameter requestParameters.oldPath was null or undefined when calling workspaceFileServiceUpdateWorkspaceFile.'
      )
    }

    if (
      requestParameters.file === null ||
      requestParameters.file === undefined
    ) {
      throw new runtime.RequiredError(
        'file',
        'Required parameter requestParameters.file was null or undefined when calling workspaceFileServiceUpdateWorkspaceFile.'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.apiKey) {
      headerParameters['Authorization'] =
        this.configuration.apiKey('Authorization') // bearer authentication
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/workspaces/{workspaceId}/file/{oldPath}`
          .replace(
            `{${'workspaceId'}}`,
            encodeURIComponent(String(requestParameters.workspaceId))
          )
          .replace(
            `{${'oldPath'}}`,
            encodeURIComponent(String(requestParameters.oldPath))
          ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: ChorusWorkspaceFileToJSON(requestParameters.file)
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChorusUpdateWorkspaceFileReplyFromJSON(jsonValue)
    )
  }

  /**
   * This endpoint updates (rename or moves) a file in a workspace at the specified path
   * Update a file in a workspace
   */
  async workspaceFileServiceUpdateWorkspaceFile(
    requestParameters: WorkspaceFileServiceUpdateWorkspaceFileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ChorusUpdateWorkspaceFileReply> {
    const response = await this.workspaceFileServiceUpdateWorkspaceFileRaw(
      requestParameters,
      initOverrides
    )
    return await response.value()
  }
}
