/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ApprovalRequestServiceApproveApprovalRequestBody
 */
export interface ApprovalRequestServiceApproveApprovalRequestBody {
  /**
   *
   * @type {boolean}
   * @memberof ApprovalRequestServiceApproveApprovalRequestBody
   */
  approve?: boolean
  /**
   *
   * @type {string}
   * @memberof ApprovalRequestServiceApproveApprovalRequestBody
   */
  comment?: string
}

/**
 * Check if a given object implements the ApprovalRequestServiceApproveApprovalRequestBody interface.
 */
export function instanceOfApprovalRequestServiceApproveApprovalRequestBody(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ApprovalRequestServiceApproveApprovalRequestBodyFromJSON(
  json: any
): ApprovalRequestServiceApproveApprovalRequestBody {
  return ApprovalRequestServiceApproveApprovalRequestBodyFromJSONTyped(
    json,
    false
  )
}

export function ApprovalRequestServiceApproveApprovalRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApprovalRequestServiceApproveApprovalRequestBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    approve: !exists(json, 'approve') ? undefined : json['approve'],
    comment: !exists(json, 'comment') ? undefined : json['comment']
  }
}

export function ApprovalRequestServiceApproveApprovalRequestBodyToJSON(
  value?: ApprovalRequestServiceApproveApprovalRequestBody | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    approve: value.approve,
    comment: value.comment
  }
}
