/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusApprovalRequestNotification } from './ChorusApprovalRequestNotification'
import {
  ChorusApprovalRequestNotificationFromJSON,
  ChorusApprovalRequestNotificationFromJSONTyped,
  ChorusApprovalRequestNotificationToJSON
} from './ChorusApprovalRequestNotification'
import type { ChorusSystemNotification } from './ChorusSystemNotification'
import {
  ChorusSystemNotificationFromJSON,
  ChorusSystemNotificationFromJSONTyped,
  ChorusSystemNotificationToJSON
} from './ChorusSystemNotification'

/**
 *
 * @export
 * @interface ChorusNotificationContent
 */
export interface ChorusNotificationContent {
  /**
   *
   * @type {ChorusSystemNotification}
   * @memberof ChorusNotificationContent
   */
  systemNotification?: ChorusSystemNotification
  /**
   *
   * @type {ChorusApprovalRequestNotification}
   * @memberof ChorusNotificationContent
   */
  approvalRequestNotification?: ChorusApprovalRequestNotification
}

/**
 * Check if a given object implements the ChorusNotificationContent interface.
 */
export function instanceOfChorusNotificationContent(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusNotificationContentFromJSON(
  json: any
): ChorusNotificationContent {
  return ChorusNotificationContentFromJSONTyped(json, false)
}

export function ChorusNotificationContentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusNotificationContent {
  if (json === undefined || json === null) {
    return json
  }
  return {
    systemNotification: !exists(json, 'systemNotification')
      ? undefined
      : ChorusSystemNotificationFromJSON(json['systemNotification']),
    approvalRequestNotification: !exists(json, 'approvalRequestNotification')
      ? undefined
      : ChorusApprovalRequestNotificationFromJSON(
          json['approvalRequestNotification']
        )
  }
}

export function ChorusNotificationContentToJSON(
  value?: ChorusNotificationContent | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    systemNotification: ChorusSystemNotificationToJSON(
      value.systemNotification
    ),
    approvalRequestNotification: ChorusApprovalRequestNotificationToJSON(
      value.approvalRequestNotification
    )
  }
}
