/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusAppInstance } from './ChorusAppInstance'
import {
  ChorusAppInstanceFromJSON,
  ChorusAppInstanceFromJSONTyped,
  ChorusAppInstanceToJSON
} from './ChorusAppInstance'

/**
 *
 * @export
 * @interface ChorusUpdateAppInstanceResult
 */
export interface ChorusUpdateAppInstanceResult {
  /**
   *
   * @type {ChorusAppInstance}
   * @memberof ChorusUpdateAppInstanceResult
   */
  appInstance?: ChorusAppInstance
}

/**
 * Check if a given object implements the ChorusUpdateAppInstanceResult interface.
 */
export function instanceOfChorusUpdateAppInstanceResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdateAppInstanceResultFromJSON(
  json: any
): ChorusUpdateAppInstanceResult {
  return ChorusUpdateAppInstanceResultFromJSONTyped(json, false)
}

export function ChorusUpdateAppInstanceResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdateAppInstanceResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    appInstance: !exists(json, 'appInstance')
      ? undefined
      : ChorusAppInstanceFromJSON(json['appInstance'])
  }
}

export function ChorusUpdateAppInstanceResultToJSON(
  value?: ChorusUpdateAppInstanceResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    appInstance: ChorusAppInstanceToJSON(value.appInstance)
  }
}
