/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusAppInstance } from './ChorusAppInstance'
import {
  ChorusAppInstanceFromJSON,
  ChorusAppInstanceFromJSONTyped,
  ChorusAppInstanceToJSON
} from './ChorusAppInstance'

/**
 *
 * @export
 * @interface ChorusListAppInstancesReply
 */
export interface ChorusListAppInstancesReply {
  /**
   *
   * @type {Array<ChorusAppInstance>}
   * @memberof ChorusListAppInstancesReply
   */
  result?: Array<ChorusAppInstance>
}

/**
 * Check if a given object implements the ChorusListAppInstancesReply interface.
 */
export function instanceOfChorusListAppInstancesReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListAppInstancesReplyFromJSON(
  json: any
): ChorusListAppInstancesReply {
  return ChorusListAppInstancesReplyFromJSONTyped(json, false)
}

export function ChorusListAppInstancesReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListAppInstancesReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : (json['result'] as Array<any>).map(ChorusAppInstanceFromJSON)
  }
}

export function ChorusListAppInstancesReplyToJSON(
  value?: ChorusListAppInstancesReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result:
      value.result === undefined
        ? undefined
        : (value.result as Array<any>).map(ChorusAppInstanceToJSON)
  }
}
