/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusCreateDynamicRoleResult } from './ChorusCreateDynamicRoleResult'
import {
  ChorusCreateDynamicRoleResultFromJSON,
  ChorusCreateDynamicRoleResultFromJSONTyped,
  ChorusCreateDynamicRoleResultToJSON
} from './ChorusCreateDynamicRoleResult'

/**
 *
 * @export
 * @interface ChorusCreateDynamicRoleReply
 */
export interface ChorusCreateDynamicRoleReply {
  /**
   *
   * @type {ChorusCreateDynamicRoleResult}
   * @memberof ChorusCreateDynamicRoleReply
   */
  result?: ChorusCreateDynamicRoleResult
}

/**
 * Check if a given object implements the ChorusCreateDynamicRoleReply interface.
 */
export function instanceOfChorusCreateDynamicRoleReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateDynamicRoleReplyFromJSON(
  json: any
): ChorusCreateDynamicRoleReply {
  return ChorusCreateDynamicRoleReplyFromJSONTyped(json, false)
}

export function ChorusCreateDynamicRoleReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateDynamicRoleReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusCreateDynamicRoleResultFromJSON(json['result'])
  }
}

export function ChorusCreateDynamicRoleReplyToJSON(
  value?: ChorusCreateDynamicRoleReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusCreateDynamicRoleResultToJSON(value.result)
  }
}
