/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ChorusWorkspaceVisibility = {
  Private: 'WORKSPACE_VISIBILITY_PRIVATE',
  Public: 'WORKSPACE_VISIBILITY_PUBLIC'
} as const
export type ChorusWorkspaceVisibility =
  (typeof ChorusWorkspaceVisibility)[keyof typeof ChorusWorkspaceVisibility]

export function ChorusWorkspaceVisibilityFromJSON(
  json: any
): ChorusWorkspaceVisibility {
  return ChorusWorkspaceVisibilityFromJSONTyped(json, false)
}

export function ChorusWorkspaceVisibilityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusWorkspaceVisibility {
  return json as ChorusWorkspaceVisibility
}

export function ChorusWorkspaceVisibilityToJSON(
  value?: ChorusWorkspaceVisibility | null
): any {
  return value as any
}
