/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspaceServiceInstance } from './ChorusWorkspaceServiceInstance'
import {
  ChorusWorkspaceServiceInstanceFromJSON,
  ChorusWorkspaceServiceInstanceFromJSONTyped,
  ChorusWorkspaceServiceInstanceToJSON
} from './ChorusWorkspaceServiceInstance'

/**
 *
 * @export
 * @interface ChorusListWorkspaceServiceInstancesResult
 */
export interface ChorusListWorkspaceServiceInstancesResult {
  /**
   *
   * @type {Array<ChorusWorkspaceServiceInstance>}
   * @memberof ChorusListWorkspaceServiceInstancesResult
   */
  workspaceServiceInstances?: Array<ChorusWorkspaceServiceInstance>
}

/**
 * Check if a given object implements the ChorusListWorkspaceServiceInstancesResult interface.
 */
export function instanceOfChorusListWorkspaceServiceInstancesResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListWorkspaceServiceInstancesResultFromJSON(
  json: any
): ChorusListWorkspaceServiceInstancesResult {
  return ChorusListWorkspaceServiceInstancesResultFromJSONTyped(json, false)
}

export function ChorusListWorkspaceServiceInstancesResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListWorkspaceServiceInstancesResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    workspaceServiceInstances: !exists(json, 'workspaceServiceInstances')
      ? undefined
      : (json['workspaceServiceInstances'] as Array<any>).map(
          ChorusWorkspaceServiceInstanceFromJSON
        )
  }
}

export function ChorusListWorkspaceServiceInstancesResultToJSON(
  value?: ChorusListWorkspaceServiceInstancesResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    workspaceServiceInstances:
      value.workspaceServiceInstances === undefined
        ? undefined
        : (value.workspaceServiceInstances as Array<any>).map(
            ChorusWorkspaceServiceInstanceToJSON
          )
  }
}
