/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusApprovalRequestNotification
 */
export interface ChorusApprovalRequestNotification {
  /**
   *
   * @type {string}
   * @memberof ChorusApprovalRequestNotification
   */
  approvalRequestId?: string
}

/**
 * Check if a given object implements the ChorusApprovalRequestNotification interface.
 */
export function instanceOfChorusApprovalRequestNotification(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusApprovalRequestNotificationFromJSON(
  json: any
): ChorusApprovalRequestNotification {
  return ChorusApprovalRequestNotificationFromJSONTyped(json, false)
}

export function ChorusApprovalRequestNotificationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusApprovalRequestNotification {
  if (json === undefined || json === null) {
    return json
  }
  return {
    approvalRequestId: !exists(json, 'approvalRequestId')
      ? undefined
      : json['approvalRequestId']
  }
}

export function ChorusApprovalRequestNotificationToJSON(
  value?: ChorusApprovalRequestNotification | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    approvalRequestId: value.approvalRequestId
  }
}
