/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusGetTermsOfUseVersionResult } from './ChorusGetTermsOfUseVersionResult'
import {
  ChorusGetTermsOfUseVersionResultFromJSON,
  ChorusGetTermsOfUseVersionResultFromJSONTyped,
  ChorusGetTermsOfUseVersionResultToJSON
} from './ChorusGetTermsOfUseVersionResult'

/**
 *
 * @export
 * @interface ChorusGetTermsOfUseVersionReply
 */
export interface ChorusGetTermsOfUseVersionReply {
  /**
   *
   * @type {ChorusGetTermsOfUseVersionResult}
   * @memberof ChorusGetTermsOfUseVersionReply
   */
  result?: ChorusGetTermsOfUseVersionResult
}

/**
 * Check if a given object implements the ChorusGetTermsOfUseVersionReply interface.
 */
export function instanceOfChorusGetTermsOfUseVersionReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetTermsOfUseVersionReplyFromJSON(
  json: any
): ChorusGetTermsOfUseVersionReply {
  return ChorusGetTermsOfUseVersionReplyFromJSONTyped(json, false)
}

export function ChorusGetTermsOfUseVersionReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetTermsOfUseVersionReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusGetTermsOfUseVersionResultFromJSON(json['result'])
  }
}

export function ChorusGetTermsOfUseVersionReplyToJSON(
  value?: ChorusGetTermsOfUseVersionReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusGetTermsOfUseVersionResultToJSON(value.result)
  }
}
