/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusPlatformSettings } from './ChorusPlatformSettings'
import {
  ChorusPlatformSettingsFromJSON,
  ChorusPlatformSettingsFromJSONTyped,
  ChorusPlatformSettingsToJSON
} from './ChorusPlatformSettings'

/**
 *
 * @export
 * @interface ChorusUpdatePlatformSettingsResult
 */
export interface ChorusUpdatePlatformSettingsResult {
  /**
   *
   * @type {ChorusPlatformSettings}
   * @memberof ChorusUpdatePlatformSettingsResult
   */
  platformSettings?: ChorusPlatformSettings
}

/**
 * Check if a given object implements the ChorusUpdatePlatformSettingsResult interface.
 */
export function instanceOfChorusUpdatePlatformSettingsResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdatePlatformSettingsResultFromJSON(
  json: any
): ChorusUpdatePlatformSettingsResult {
  return ChorusUpdatePlatformSettingsResultFromJSONTyped(json, false)
}

export function ChorusUpdatePlatformSettingsResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdatePlatformSettingsResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    platformSettings: !exists(json, 'platformSettings')
      ? undefined
      : ChorusPlatformSettingsFromJSON(json['platformSettings'])
  }
}

export function ChorusUpdatePlatformSettingsResultToJSON(
  value?: ChorusUpdatePlatformSettingsResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    platformSettings: ChorusPlatformSettingsToJSON(value.platformSettings)
  }
}
