/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusUpdateWorkspaceServiceInstanceResult } from './ChorusUpdateWorkspaceServiceInstanceResult'
import {
  ChorusUpdateWorkspaceServiceInstanceResultFromJSON,
  ChorusUpdateWorkspaceServiceInstanceResultFromJSONTyped,
  ChorusUpdateWorkspaceServiceInstanceResultToJSON
} from './ChorusUpdateWorkspaceServiceInstanceResult'

/**
 *
 * @export
 * @interface ChorusUpdateWorkspaceServiceInstanceReply
 */
export interface ChorusUpdateWorkspaceServiceInstanceReply {
  /**
   *
   * @type {ChorusUpdateWorkspaceServiceInstanceResult}
   * @memberof ChorusUpdateWorkspaceServiceInstanceReply
   */
  result?: ChorusUpdateWorkspaceServiceInstanceResult
}

/**
 * Check if a given object implements the ChorusUpdateWorkspaceServiceInstanceReply interface.
 */
export function instanceOfChorusUpdateWorkspaceServiceInstanceReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdateWorkspaceServiceInstanceReplyFromJSON(
  json: any
): ChorusUpdateWorkspaceServiceInstanceReply {
  return ChorusUpdateWorkspaceServiceInstanceReplyFromJSONTyped(json, false)
}

export function ChorusUpdateWorkspaceServiceInstanceReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdateWorkspaceServiceInstanceReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusUpdateWorkspaceServiceInstanceResultFromJSON(json['result'])
  }
}

export function ChorusUpdateWorkspaceServiceInstanceReplyToJSON(
  value?: ChorusUpdateWorkspaceServiceInstanceReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusUpdateWorkspaceServiceInstanceResultToJSON(value.result)
  }
}
