/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusUpdateWorkspaceFileResult } from './ChorusUpdateWorkspaceFileResult'
import {
  ChorusUpdateWorkspaceFileResultFromJSON,
  ChorusUpdateWorkspaceFileResultFromJSONTyped,
  ChorusUpdateWorkspaceFileResultToJSON
} from './ChorusUpdateWorkspaceFileResult'

/**
 *
 * @export
 * @interface ChorusUpdateWorkspaceFileReply
 */
export interface ChorusUpdateWorkspaceFileReply {
  /**
   *
   * @type {ChorusUpdateWorkspaceFileResult}
   * @memberof ChorusUpdateWorkspaceFileReply
   */
  result?: ChorusUpdateWorkspaceFileResult
}

/**
 * Check if a given object implements the ChorusUpdateWorkspaceFileReply interface.
 */
export function instanceOfChorusUpdateWorkspaceFileReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdateWorkspaceFileReplyFromJSON(
  json: any
): ChorusUpdateWorkspaceFileReply {
  return ChorusUpdateWorkspaceFileReplyFromJSONTyped(json, false)
}

export function ChorusUpdateWorkspaceFileReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdateWorkspaceFileReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusUpdateWorkspaceFileResultFromJSON(json['result'])
  }
}

export function ChorusUpdateWorkspaceFileReplyToJSON(
  value?: ChorusUpdateWorkspaceFileReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusUpdateWorkspaceFileResultToJSON(value.result)
  }
}
