/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusTermsOfUseVersion } from './ChorusTermsOfUseVersion'
import {
  ChorusTermsOfUseVersionFromJSON,
  ChorusTermsOfUseVersionFromJSONTyped,
  ChorusTermsOfUseVersionToJSON
} from './ChorusTermsOfUseVersion'

/**
 *
 * @export
 * @interface ChorusGetCurrentTermsOfUseVersionResult
 */
export interface ChorusGetCurrentTermsOfUseVersionResult {
  /**
   *
   * @type {ChorusTermsOfUseVersion}
   * @memberof ChorusGetCurrentTermsOfUseVersionResult
   */
  termsOfUseVersion?: ChorusTermsOfUseVersion
}

/**
 * Check if a given object implements the ChorusGetCurrentTermsOfUseVersionResult interface.
 */
export function instanceOfChorusGetCurrentTermsOfUseVersionResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetCurrentTermsOfUseVersionResultFromJSON(
  json: any
): ChorusGetCurrentTermsOfUseVersionResult {
  return ChorusGetCurrentTermsOfUseVersionResultFromJSONTyped(json, false)
}

export function ChorusGetCurrentTermsOfUseVersionResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetCurrentTermsOfUseVersionResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    termsOfUseVersion: !exists(json, 'termsOfUseVersion')
      ? undefined
      : ChorusTermsOfUseVersionFromJSON(json['termsOfUseVersion'])
  }
}

export function ChorusGetCurrentTermsOfUseVersionResultToJSON(
  value?: ChorusGetCurrentTermsOfUseVersionResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    termsOfUseVersion: ChorusTermsOfUseVersionToJSON(value.termsOfUseVersion)
  }
}
