/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusPublicWorkspace } from './ChorusPublicWorkspace'
import {
  ChorusPublicWorkspaceFromJSON,
  ChorusPublicWorkspaceFromJSONTyped,
  ChorusPublicWorkspaceToJSON
} from './ChorusPublicWorkspace'

/**
 *
 * @export
 * @interface ChorusListPublicWorkspacesResult
 */
export interface ChorusListPublicWorkspacesResult {
  /**
   *
   * @type {Array<ChorusPublicWorkspace>}
   * @memberof ChorusListPublicWorkspacesResult
   */
  publicWorkspaces?: Array<ChorusPublicWorkspace>
}

/**
 * Check if a given object implements the ChorusListPublicWorkspacesResult interface.
 */
export function instanceOfChorusListPublicWorkspacesResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListPublicWorkspacesResultFromJSON(
  json: any
): ChorusListPublicWorkspacesResult {
  return ChorusListPublicWorkspacesResultFromJSONTyped(json, false)
}

export function ChorusListPublicWorkspacesResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListPublicWorkspacesResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    publicWorkspaces: !exists(json, 'publicWorkspaces')
      ? undefined
      : (json['publicWorkspaces'] as Array<any>).map(
          ChorusPublicWorkspaceFromJSON
        )
  }
}

export function ChorusListPublicWorkspacesResultToJSON(
  value?: ChorusListPublicWorkspacesResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    publicWorkspaces:
      value.publicWorkspaces === undefined
        ? undefined
        : (value.publicWorkspaces as Array<any>).map(
            ChorusPublicWorkspaceToJSON
          )
  }
}
