/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspaceFile } from './ChorusWorkspaceFile'
import {
  ChorusWorkspaceFileFromJSON,
  ChorusWorkspaceFileFromJSONTyped,
  ChorusWorkspaceFileToJSON
} from './ChorusWorkspaceFile'

/**
 *
 * @export
 * @interface ChorusGetWorkspaceFileResult
 */
export interface ChorusGetWorkspaceFileResult {
  /**
   *
   * @type {ChorusWorkspaceFile}
   * @memberof ChorusGetWorkspaceFileResult
   */
  file?: ChorusWorkspaceFile
  /**
   *
   * @type {Array<ChorusWorkspaceFile>}
   * @memberof ChorusGetWorkspaceFileResult
   */
  children?: Array<ChorusWorkspaceFile>
}

/**
 * Check if a given object implements the ChorusGetWorkspaceFileResult interface.
 */
export function instanceOfChorusGetWorkspaceFileResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetWorkspaceFileResultFromJSON(
  json: any
): ChorusGetWorkspaceFileResult {
  return ChorusGetWorkspaceFileResultFromJSONTyped(json, false)
}

export function ChorusGetWorkspaceFileResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetWorkspaceFileResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    file: !exists(json, 'file')
      ? undefined
      : ChorusWorkspaceFileFromJSON(json['file']),
    children: !exists(json, 'children')
      ? undefined
      : (json['children'] as Array<any>).map(ChorusWorkspaceFileFromJSON)
  }
}

export function ChorusGetWorkspaceFileResultToJSON(
  value?: ChorusGetWorkspaceFileResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    file: ChorusWorkspaceFileToJSON(value.file),
    children:
      value.children === undefined
        ? undefined
        : (value.children as Array<any>).map(ChorusWorkspaceFileToJSON)
  }
}
