/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusPutEntryRequest
 */
export interface ChorusPutEntryRequest {
  /**
   *
   * @type {string}
   * @memberof ChorusPutEntryRequest
   */
  key?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPutEntryRequest
   */
  value?: string
}

/**
 * Check if a given object implements the ChorusPutEntryRequest interface.
 */
export function instanceOfChorusPutEntryRequest(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusPutEntryRequestFromJSON(
  json: any
): ChorusPutEntryRequest {
  return ChorusPutEntryRequestFromJSONTyped(json, false)
}

export function ChorusPutEntryRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusPutEntryRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    key: !exists(json, 'key') ? undefined : json['key'],
    value: !exists(json, 'value') ? undefined : json['value']
  }
}

export function ChorusPutEntryRequestToJSON(
  value?: ChorusPutEntryRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    key: value.key,
    value: value.value
  }
}
