/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusListTermsOfUseVersionsResult } from './ChorusListTermsOfUseVersionsResult'
import {
  ChorusListTermsOfUseVersionsResultFromJSON,
  ChorusListTermsOfUseVersionsResultFromJSONTyped,
  ChorusListTermsOfUseVersionsResultToJSON
} from './ChorusListTermsOfUseVersionsResult'
import type { ChorusPaginationResult } from './ChorusPaginationResult'
import {
  ChorusPaginationResultFromJSON,
  ChorusPaginationResultFromJSONTyped,
  ChorusPaginationResultToJSON
} from './ChorusPaginationResult'

/**
 *
 * @export
 * @interface ChorusListTermsOfUseVersionsReply
 */
export interface ChorusListTermsOfUseVersionsReply {
  /**
   *
   * @type {ChorusListTermsOfUseVersionsResult}
   * @memberof ChorusListTermsOfUseVersionsReply
   */
  result?: ChorusListTermsOfUseVersionsResult
  /**
   *
   * @type {ChorusPaginationResult}
   * @memberof ChorusListTermsOfUseVersionsReply
   */
  pagination?: ChorusPaginationResult
}

/**
 * Check if a given object implements the ChorusListTermsOfUseVersionsReply interface.
 */
export function instanceOfChorusListTermsOfUseVersionsReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListTermsOfUseVersionsReplyFromJSON(
  json: any
): ChorusListTermsOfUseVersionsReply {
  return ChorusListTermsOfUseVersionsReplyFromJSONTyped(json, false)
}

export function ChorusListTermsOfUseVersionsReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListTermsOfUseVersionsReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusListTermsOfUseVersionsResultFromJSON(json['result']),
    pagination: !exists(json, 'pagination')
      ? undefined
      : ChorusPaginationResultFromJSON(json['pagination'])
  }
}

export function ChorusListTermsOfUseVersionsReplyToJSON(
  value?: ChorusListTermsOfUseVersionsReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusListTermsOfUseVersionsResultToJSON(value.result),
    pagination: ChorusPaginationResultToJSON(value.pagination)
  }
}
