/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusPlatformSettings
 */
export interface ChorusPlatformSettings {
  /**
   *
   * @type {string}
   * @memberof ChorusPlatformSettings
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPlatformSettings
   */
  tenantId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPlatformSettings
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPlatformSettings
   */
  headline?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPlatformSettings
   */
  tagline?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPlatformSettings
   */
  websiteURL?: string
  /**
   *
   * @type {number}
   * @memberof ChorusPlatformSettings
   */
  maxWorkspacesPerUser?: number
  /**
   *
   * @type {number}
   * @memberof ChorusPlatformSettings
   */
  maxSessionsPerUser?: number
  /**
   *
   * @type {number}
   * @memberof ChorusPlatformSettings
   */
  maxAppInstancesPerUser?: number
  /**
   *
   * @type {Date}
   * @memberof ChorusPlatformSettings
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof ChorusPlatformSettings
   */
  updatedAt?: Date
}

/**
 * Check if a given object implements the ChorusPlatformSettings interface.
 */
export function instanceOfChorusPlatformSettings(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusPlatformSettingsFromJSON(
  json: any
): ChorusPlatformSettings {
  return ChorusPlatformSettingsFromJSONTyped(json, false)
}

export function ChorusPlatformSettingsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusPlatformSettings {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    tenantId: !exists(json, 'tenantId') ? undefined : json['tenantId'],
    title: !exists(json, 'title') ? undefined : json['title'],
    headline: !exists(json, 'headline') ? undefined : json['headline'],
    tagline: !exists(json, 'tagline') ? undefined : json['tagline'],
    websiteURL: !exists(json, 'websiteURL') ? undefined : json['websiteURL'],
    maxWorkspacesPerUser: !exists(json, 'maxWorkspacesPerUser')
      ? undefined
      : json['maxWorkspacesPerUser'],
    maxSessionsPerUser: !exists(json, 'maxSessionsPerUser')
      ? undefined
      : json['maxSessionsPerUser'],
    maxAppInstancesPerUser: !exists(json, 'maxAppInstancesPerUser')
      ? undefined
      : json['maxAppInstancesPerUser'],
    createdAt: !exists(json, 'createdAt')
      ? undefined
      : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt')
      ? undefined
      : new Date(json['updatedAt'])
  }
}

export function ChorusPlatformSettingsToJSON(
  value?: ChorusPlatformSettings | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    tenantId: value.tenantId,
    title: value.title,
    headline: value.headline,
    tagline: value.tagline,
    websiteURL: value.websiteURL,
    maxWorkspacesPerUser: value.maxWorkspacesPerUser,
    maxSessionsPerUser: value.maxSessionsPerUser,
    maxAppInstancesPerUser: value.maxAppInstancesPerUser,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString()
  }
}
