/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusUser } from './ChorusUser'
import {
  ChorusUserFromJSON,
  ChorusUserFromJSONTyped,
  ChorusUserToJSON
} from './ChorusUser'

/**
 *
 * @export
 * @interface ChorusCreateUserResult
 */
export interface ChorusCreateUserResult {
  /**
   *
   * @type {ChorusUser}
   * @memberof ChorusCreateUserResult
   */
  user?: ChorusUser
}

/**
 * Check if a given object implements the ChorusCreateUserResult interface.
 */
export function instanceOfChorusCreateUserResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateUserResultFromJSON(
  json: any
): ChorusCreateUserResult {
  return ChorusCreateUserResultFromJSONTyped(json, false)
}

export function ChorusCreateUserResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateUserResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    user: !exists(json, 'user') ? undefined : ChorusUserFromJSON(json['user'])
  }
}

export function ChorusCreateUserResultToJSON(
  value?: ChorusCreateUserResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    user: ChorusUserToJSON(value.user)
  }
}
