/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusAppVersion } from './ChorusAppVersion'
import {
  ChorusAppVersionFromJSON,
  ChorusAppVersionFromJSONTyped,
  ChorusAppVersionToJSON
} from './ChorusAppVersion'

/**
 *
 * @export
 * @interface ChorusApp
 */
export interface ChorusApp {
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  tenantId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  userId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  status?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  dockerImageRegistry?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  dockerImageName?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  dockerImageTag?: string
  /**
   *
   * @type {Array<ChorusAppVersion>}
   * @memberof ChorusApp
   */
  groupedVersions?: Array<ChorusAppVersion>
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  shmSize?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  maxCPU?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  minCPU?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  maxMemory?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  minMemory?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  maxEphemeralStorage?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  minEphemeralStorage?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  browserConfigURL?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  browserConfigJWTURL?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  browserConfigJWTOIDCClientID?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  iconURL?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  iconBackgroundColor?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  stabilityStatus?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApp
   */
  category?: string
  /**
   *
   * @type {Date}
   * @memberof ChorusApp
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof ChorusApp
   */
  updatedAt?: Date
}

/**
 * Check if a given object implements the ChorusApp interface.
 */
export function instanceOfChorusApp(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusAppFromJSON(json: any): ChorusApp {
  return ChorusAppFromJSONTyped(json, false)
}

export function ChorusAppFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusApp {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    tenantId: !exists(json, 'tenantId') ? undefined : json['tenantId'],
    userId: !exists(json, 'userId') ? undefined : json['userId'],
    name: !exists(json, 'name') ? undefined : json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
    status: !exists(json, 'status') ? undefined : json['status'],
    dockerImageRegistry: !exists(json, 'dockerImageRegistry')
      ? undefined
      : json['dockerImageRegistry'],
    dockerImageName: !exists(json, 'dockerImageName')
      ? undefined
      : json['dockerImageName'],
    dockerImageTag: !exists(json, 'dockerImageTag')
      ? undefined
      : json['dockerImageTag'],
    groupedVersions: !exists(json, 'groupedVersions')
      ? undefined
      : (json['groupedVersions'] as Array<any>).map(ChorusAppVersionFromJSON),
    shmSize: !exists(json, 'shmSize') ? undefined : json['shmSize'],
    maxCPU: !exists(json, 'maxCPU') ? undefined : json['maxCPU'],
    minCPU: !exists(json, 'minCPU') ? undefined : json['minCPU'],
    maxMemory: !exists(json, 'maxMemory') ? undefined : json['maxMemory'],
    minMemory: !exists(json, 'minMemory') ? undefined : json['minMemory'],
    maxEphemeralStorage: !exists(json, 'maxEphemeralStorage')
      ? undefined
      : json['maxEphemeralStorage'],
    minEphemeralStorage: !exists(json, 'minEphemeralStorage')
      ? undefined
      : json['minEphemeralStorage'],
    browserConfigURL: !exists(json, 'browserConfigURL')
      ? undefined
      : json['browserConfigURL'],
    browserConfigJWTURL: !exists(json, 'browserConfigJWTURL')
      ? undefined
      : json['browserConfigJWTURL'],
    browserConfigJWTOIDCClientID: !exists(json, 'browserConfigJWTOIDCClientID')
      ? undefined
      : json['browserConfigJWTOIDCClientID'],
    iconURL: !exists(json, 'iconURL') ? undefined : json['iconURL'],
    iconBackgroundColor: !exists(json, 'iconBackgroundColor')
      ? undefined
      : json['iconBackgroundColor'],
    stabilityStatus: !exists(json, 'stabilityStatus')
      ? undefined
      : json['stabilityStatus'],
    category: !exists(json, 'category') ? undefined : json['category'],
    createdAt: !exists(json, 'createdAt')
      ? undefined
      : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt')
      ? undefined
      : new Date(json['updatedAt'])
  }
}

export function ChorusAppToJSON(value?: ChorusApp | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    tenantId: value.tenantId,
    userId: value.userId,
    name: value.name,
    description: value.description,
    status: value.status,
    dockerImageRegistry: value.dockerImageRegistry,
    dockerImageName: value.dockerImageName,
    dockerImageTag: value.dockerImageTag,
    groupedVersions:
      value.groupedVersions === undefined
        ? undefined
        : (value.groupedVersions as Array<any>).map(ChorusAppVersionToJSON),
    shmSize: value.shmSize,
    maxCPU: value.maxCPU,
    minCPU: value.minCPU,
    maxMemory: value.maxMemory,
    minMemory: value.minMemory,
    maxEphemeralStorage: value.maxEphemeralStorage,
    minEphemeralStorage: value.minEphemeralStorage,
    browserConfigURL: value.browserConfigURL,
    browserConfigJWTURL: value.browserConfigJWTURL,
    browserConfigJWTOIDCClientID: value.browserConfigJWTOIDCClientID,
    iconURL: value.iconURL,
    iconBackgroundColor: value.iconBackgroundColor,
    stabilityStatus: value.stabilityStatus,
    category: value.category,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString()
  }
}
