/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusCreateDataExtractionRequestResult } from './ChorusCreateDataExtractionRequestResult'
import {
  ChorusCreateDataExtractionRequestResultFromJSON,
  ChorusCreateDataExtractionRequestResultFromJSONTyped,
  ChorusCreateDataExtractionRequestResultToJSON
} from './ChorusCreateDataExtractionRequestResult'

/**
 *
 * @export
 * @interface ChorusCreateDataExtractionRequestReply
 */
export interface ChorusCreateDataExtractionRequestReply {
  /**
   *
   * @type {ChorusCreateDataExtractionRequestResult}
   * @memberof ChorusCreateDataExtractionRequestReply
   */
  result?: ChorusCreateDataExtractionRequestResult
}

/**
 * Check if a given object implements the ChorusCreateDataExtractionRequestReply interface.
 */
export function instanceOfChorusCreateDataExtractionRequestReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateDataExtractionRequestReplyFromJSON(
  json: any
): ChorusCreateDataExtractionRequestReply {
  return ChorusCreateDataExtractionRequestReplyFromJSONTyped(json, false)
}

export function ChorusCreateDataExtractionRequestReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateDataExtractionRequestReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusCreateDataExtractionRequestResultFromJSON(json['result'])
  }
}

export function ChorusCreateDataExtractionRequestReplyToJSON(
  value?: ChorusCreateDataExtractionRequestReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusCreateDataExtractionRequestResultToJSON(value.result)
  }
}
