/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusDeleteEntryReply
 */
export interface ChorusDeleteEntryReply {
  /**
   *
   * @type {object}
   * @memberof ChorusDeleteEntryReply
   */
  result?: object
}

/**
 * Check if a given object implements the ChorusDeleteEntryReply interface.
 */
export function instanceOfChorusDeleteEntryReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusDeleteEntryReplyFromJSON(
  json: any
): ChorusDeleteEntryReply {
  return ChorusDeleteEntryReplyFromJSONTyped(json, false)
}

export function ChorusDeleteEntryReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusDeleteEntryReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result') ? undefined : json['result']
  }
}

export function ChorusDeleteEntryReplyToJSON(
  value?: ChorusDeleteEntryReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: value.result
  }
}
