/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusTermsOfUseAcceptance
 */
export interface ChorusTermsOfUseAcceptance {
  /**
   *
   * @type {string}
   * @memberof ChorusTermsOfUseAcceptance
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof ChorusTermsOfUseAcceptance
   */
  tenantId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusTermsOfUseAcceptance
   */
  userId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusTermsOfUseAcceptance
   */
  termsOfUseVersionId?: string
  /**
   *
   * @type {Date}
   * @memberof ChorusTermsOfUseAcceptance
   */
  acceptedAt?: Date
}

/**
 * Check if a given object implements the ChorusTermsOfUseAcceptance interface.
 */
export function instanceOfChorusTermsOfUseAcceptance(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusTermsOfUseAcceptanceFromJSON(
  json: any
): ChorusTermsOfUseAcceptance {
  return ChorusTermsOfUseAcceptanceFromJSONTyped(json, false)
}

export function ChorusTermsOfUseAcceptanceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusTermsOfUseAcceptance {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    tenantId: !exists(json, 'tenantId') ? undefined : json['tenantId'],
    userId: !exists(json, 'userId') ? undefined : json['userId'],
    termsOfUseVersionId: !exists(json, 'termsOfUseVersionId')
      ? undefined
      : json['termsOfUseVersionId'],
    acceptedAt: !exists(json, 'acceptedAt')
      ? undefined
      : new Date(json['acceptedAt'])
  }
}

export function ChorusTermsOfUseAcceptanceToJSON(
  value?: ChorusTermsOfUseAcceptance | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    tenantId: value.tenantId,
    userId: value.userId,
    termsOfUseVersionId: value.termsOfUseVersionId,
    acceptedAt:
      value.acceptedAt === undefined
        ? undefined
        : value.acceptedAt.toISOString()
  }
}
