/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusNotificationContent } from './ChorusNotificationContent'
import {
  ChorusNotificationContentFromJSON,
  ChorusNotificationContentFromJSONTyped,
  ChorusNotificationContentToJSON
} from './ChorusNotificationContent'

/**
 *
 * @export
 * @interface ChorusNotification
 */
export interface ChorusNotification {
  /**
   *
   * @type {string}
   * @memberof ChorusNotification
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof ChorusNotification
   */
  tenantId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusNotification
   */
  message?: string
  /**
   *
   * @type {ChorusNotificationContent}
   * @memberof ChorusNotification
   */
  content?: ChorusNotificationContent
  /**
   *
   * @type {Date}
   * @memberof ChorusNotification
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof ChorusNotification
   */
  readAt?: Date
}

/**
 * Check if a given object implements the ChorusNotification interface.
 */
export function instanceOfChorusNotification(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusNotificationFromJSON(json: any): ChorusNotification {
  return ChorusNotificationFromJSONTyped(json, false)
}

export function ChorusNotificationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusNotification {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    tenantId: !exists(json, 'tenantId') ? undefined : json['tenantId'],
    message: !exists(json, 'message') ? undefined : json['message'],
    content: !exists(json, 'content')
      ? undefined
      : ChorusNotificationContentFromJSON(json['content']),
    createdAt: !exists(json, 'createdAt')
      ? undefined
      : new Date(json['createdAt']),
    readAt: !exists(json, 'readAt') ? undefined : new Date(json['readAt'])
  }
}

export function ChorusNotificationToJSON(
  value?: ChorusNotification | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    tenantId: value.tenantId,
    message: value.message,
    content: ChorusNotificationContentToJSON(value.content),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    readAt: value.readAt === undefined ? undefined : value.readAt.toISOString()
  }
}
