/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ChorusApprovalRequestStatus = {
  Unspecified: 'APPROVAL_REQUEST_STATUS_UNSPECIFIED',
  Pending: 'APPROVAL_REQUEST_STATUS_PENDING',
  Approved: 'APPROVAL_REQUEST_STATUS_APPROVED',
  Rejected: 'APPROVAL_REQUEST_STATUS_REJECTED',
  Cancelled: 'APPROVAL_REQUEST_STATUS_CANCELLED'
} as const
export type ChorusApprovalRequestStatus =
  (typeof ChorusApprovalRequestStatus)[keyof typeof ChorusApprovalRequestStatus]

export function ChorusApprovalRequestStatusFromJSON(
  json: any
): ChorusApprovalRequestStatus {
  return ChorusApprovalRequestStatusFromJSONTyped(json, false)
}

export function ChorusApprovalRequestStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusApprovalRequestStatus {
  return json as ChorusApprovalRequestStatus
}

export function ChorusApprovalRequestStatusToJSON(
  value?: ChorusApprovalRequestStatus | null
): any {
  return value as any
}
