/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusApp } from './ChorusApp'
import {
  ChorusAppFromJSON,
  ChorusAppFromJSONTyped,
  ChorusAppToJSON
} from './ChorusApp'

/**
 *
 * @export
 * @interface ChorusListAppsReply
 */
export interface ChorusListAppsReply {
  /**
   *
   * @type {Array<ChorusApp>}
   * @memberof ChorusListAppsReply
   */
  result?: Array<ChorusApp>
}

/**
 * Check if a given object implements the ChorusListAppsReply interface.
 */
export function instanceOfChorusListAppsReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListAppsReplyFromJSON(json: any): ChorusListAppsReply {
  return ChorusListAppsReplyFromJSONTyped(json, false)
}

export function ChorusListAppsReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListAppsReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : (json['result'] as Array<any>).map(ChorusAppFromJSON)
  }
}

export function ChorusListAppsReplyToJSON(
  value?: ChorusListAppsReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result:
      value.result === undefined
        ? undefined
        : (value.result as Array<any>).map(ChorusAppToJSON)
  }
}
