/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusAuthorizationPermission } from './ChorusAuthorizationPermission'
import {
  ChorusAuthorizationPermissionFromJSON,
  ChorusAuthorizationPermissionFromJSONTyped,
  ChorusAuthorizationPermissionToJSON
} from './ChorusAuthorizationPermission'

/**
 *
 * @export
 * @interface ChorusListPermissionsResult
 */
export interface ChorusListPermissionsResult {
  /**
   *
   * @type {Array<ChorusAuthorizationPermission>}
   * @memberof ChorusListPermissionsResult
   */
  permissions?: Array<ChorusAuthorizationPermission>
}

/**
 * Check if a given object implements the ChorusListPermissionsResult interface.
 */
export function instanceOfChorusListPermissionsResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListPermissionsResultFromJSON(
  json: any
): ChorusListPermissionsResult {
  return ChorusListPermissionsResultFromJSONTyped(json, false)
}

export function ChorusListPermissionsResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListPermissionsResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    permissions: !exists(json, 'permissions')
      ? undefined
      : (json['permissions'] as Array<any>).map(
          ChorusAuthorizationPermissionFromJSON
        )
  }
}

export function ChorusListPermissionsResultToJSON(
  value?: ChorusListPermissionsResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    permissions:
      value.permissions === undefined
        ? undefined
        : (value.permissions as Array<any>).map(
            ChorusAuthorizationPermissionToJSON
          )
  }
}
