/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusTermsOfUseAcceptance } from './ChorusTermsOfUseAcceptance'
import {
  ChorusTermsOfUseAcceptanceFromJSON,
  ChorusTermsOfUseAcceptanceFromJSONTyped,
  ChorusTermsOfUseAcceptanceToJSON
} from './ChorusTermsOfUseAcceptance'

/**
 *
 * @export
 * @interface ChorusListTermsOfUseAcceptancesResult
 */
export interface ChorusListTermsOfUseAcceptancesResult {
  /**
   *
   * @type {Array<ChorusTermsOfUseAcceptance>}
   * @memberof ChorusListTermsOfUseAcceptancesResult
   */
  termsOfUseAcceptances?: Array<ChorusTermsOfUseAcceptance>
}

/**
 * Check if a given object implements the ChorusListTermsOfUseAcceptancesResult interface.
 */
export function instanceOfChorusListTermsOfUseAcceptancesResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListTermsOfUseAcceptancesResultFromJSON(
  json: any
): ChorusListTermsOfUseAcceptancesResult {
  return ChorusListTermsOfUseAcceptancesResultFromJSONTyped(json, false)
}

export function ChorusListTermsOfUseAcceptancesResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListTermsOfUseAcceptancesResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    termsOfUseAcceptances: !exists(json, 'termsOfUseAcceptances')
      ? undefined
      : (json['termsOfUseAcceptances'] as Array<any>).map(
          ChorusTermsOfUseAcceptanceFromJSON
        )
  }
}

export function ChorusListTermsOfUseAcceptancesResultToJSON(
  value?: ChorusListTermsOfUseAcceptancesResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    termsOfUseAcceptances:
      value.termsOfUseAcceptances === undefined
        ? undefined
        : (value.termsOfUseAcceptances as Array<any>).map(
            ChorusTermsOfUseAcceptanceToJSON
          )
  }
}
