/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusUser } from './ChorusUser'
import {
  ChorusUserFromJSON,
  ChorusUserFromJSONTyped,
  ChorusUserToJSON
} from './ChorusUser'

/**
 *
 * @export
 * @interface ChorusListUsersResult
 */
export interface ChorusListUsersResult {
  /**
   *
   * @type {Array<ChorusUser>}
   * @memberof ChorusListUsersResult
   */
  users?: Array<ChorusUser>
}

/**
 * Check if a given object implements the ChorusListUsersResult interface.
 */
export function instanceOfChorusListUsersResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListUsersResultFromJSON(
  json: any
): ChorusListUsersResult {
  return ChorusListUsersResultFromJSONTyped(json, false)
}

export function ChorusListUsersResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListUsersResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    users: !exists(json, 'users')
      ? undefined
      : (json['users'] as Array<any>).map(ChorusUserFromJSON)
  }
}

export function ChorusListUsersResultToJSON(
  value?: ChorusListUsersResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    users:
      value.users === undefined
        ? undefined
        : (value.users as Array<any>).map(ChorusUserToJSON)
  }
}
