/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusCreateAppResult } from './ChorusCreateAppResult'
import {
  ChorusCreateAppResultFromJSON,
  ChorusCreateAppResultFromJSONTyped,
  ChorusCreateAppResultToJSON
} from './ChorusCreateAppResult'

/**
 *
 * @export
 * @interface ChorusCreateAppReply
 */
export interface ChorusCreateAppReply {
  /**
   *
   * @type {ChorusCreateAppResult}
   * @memberof ChorusCreateAppReply
   */
  result?: ChorusCreateAppResult
}

/**
 * Check if a given object implements the ChorusCreateAppReply interface.
 */
export function instanceOfChorusCreateAppReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateAppReplyFromJSON(json: any): ChorusCreateAppReply {
  return ChorusCreateAppReplyFromJSONTyped(json, false)
}

export function ChorusCreateAppReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateAppReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusCreateAppResultFromJSON(json['result'])
  }
}

export function ChorusCreateAppReplyToJSON(
  value?: ChorusCreateAppReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusCreateAppResultToJSON(value.result)
  }
}
