/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusCreateWorkspaceResult
 */
export interface ChorusCreateWorkspaceResult {
  /**
   *
   * @type {string}
   * @memberof ChorusCreateWorkspaceResult
   */
  id?: string
}

/**
 * Check if a given object implements the ChorusCreateWorkspaceResult interface.
 */
export function instanceOfChorusCreateWorkspaceResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateWorkspaceResultFromJSON(
  json: any
): ChorusCreateWorkspaceResult {
  return ChorusCreateWorkspaceResultFromJSONTyped(json, false)
}

export function ChorusCreateWorkspaceResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateWorkspaceResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id']
  }
}

export function ChorusCreateWorkspaceResultToJSON(
  value?: ChorusCreateWorkspaceResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id
  }
}
