/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusListPermissionsResult } from './ChorusListPermissionsResult'
import {
  ChorusListPermissionsResultFromJSON,
  ChorusListPermissionsResultFromJSONTyped,
  ChorusListPermissionsResultToJSON
} from './ChorusListPermissionsResult'

/**
 *
 * @export
 * @interface ChorusListPermissionsReply
 */
export interface ChorusListPermissionsReply {
  /**
   *
   * @type {ChorusListPermissionsResult}
   * @memberof ChorusListPermissionsReply
   */
  result?: ChorusListPermissionsResult
}

/**
 * Check if a given object implements the ChorusListPermissionsReply interface.
 */
export function instanceOfChorusListPermissionsReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListPermissionsReplyFromJSON(
  json: any
): ChorusListPermissionsReply {
  return ChorusListPermissionsReplyFromJSONTyped(json, false)
}

export function ChorusListPermissionsReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListPermissionsReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusListPermissionsResultFromJSON(json['result'])
  }
}

export function ChorusListPermissionsReplyToJSON(
  value?: ChorusListPermissionsReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusListPermissionsResultToJSON(value.result)
  }
}
