/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusAuditEntry } from './ChorusAuditEntry'
import {
  ChorusAuditEntryFromJSON,
  ChorusAuditEntryFromJSONTyped,
  ChorusAuditEntryToJSON
} from './ChorusAuditEntry'

/**
 *
 * @export
 * @interface ChorusListAuditEntriesResult
 */
export interface ChorusListAuditEntriesResult {
  /**
   *
   * @type {Array<ChorusAuditEntry>}
   * @memberof ChorusListAuditEntriesResult
   */
  entries?: Array<ChorusAuditEntry>
}

/**
 * Check if a given object implements the ChorusListAuditEntriesResult interface.
 */
export function instanceOfChorusListAuditEntriesResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListAuditEntriesResultFromJSON(
  json: any
): ChorusListAuditEntriesResult {
  return ChorusListAuditEntriesResultFromJSONTyped(json, false)
}

export function ChorusListAuditEntriesResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListAuditEntriesResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    entries: !exists(json, 'entries')
      ? undefined
      : (json['entries'] as Array<any>).map(ChorusAuditEntryFromJSON)
  }
}

export function ChorusListAuditEntriesResultToJSON(
  value?: ChorusListAuditEntriesResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    entries:
      value.entries === undefined
        ? undefined
        : (value.entries as Array<any>).map(ChorusAuditEntryToJSON)
  }
}
