/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspaceFilePart } from './ChorusWorkspaceFilePart'
import {
  ChorusWorkspaceFilePartFromJSON,
  ChorusWorkspaceFilePartFromJSONTyped,
  ChorusWorkspaceFilePartToJSON
} from './ChorusWorkspaceFilePart'

/**
 *
 * @export
 * @interface ChorusUploadWorkspaceFilePartResult
 */
export interface ChorusUploadWorkspaceFilePartResult {
  /**
   *
   * @type {ChorusWorkspaceFilePart}
   * @memberof ChorusUploadWorkspaceFilePartResult
   */
  part?: ChorusWorkspaceFilePart
}

/**
 * Check if a given object implements the ChorusUploadWorkspaceFilePartResult interface.
 */
export function instanceOfChorusUploadWorkspaceFilePartResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUploadWorkspaceFilePartResultFromJSON(
  json: any
): ChorusUploadWorkspaceFilePartResult {
  return ChorusUploadWorkspaceFilePartResultFromJSONTyped(json, false)
}

export function ChorusUploadWorkspaceFilePartResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUploadWorkspaceFilePartResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    part: !exists(json, 'part')
      ? undefined
      : ChorusWorkspaceFilePartFromJSON(json['part'])
  }
}

export function ChorusUploadWorkspaceFilePartResultToJSON(
  value?: ChorusUploadWorkspaceFilePartResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    part: ChorusWorkspaceFilePartToJSON(value.part)
  }
}
