/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspace } from './ChorusWorkspace'
import {
  ChorusWorkspaceFromJSON,
  ChorusWorkspaceFromJSONTyped,
  ChorusWorkspaceToJSON
} from './ChorusWorkspace'

/**
 *
 * @export
 * @interface ChorusManageUserRoleInWorkspaceResult
 */
export interface ChorusManageUserRoleInWorkspaceResult {
  /**
   *
   * @type {ChorusWorkspace}
   * @memberof ChorusManageUserRoleInWorkspaceResult
   */
  workspace?: ChorusWorkspace
}

/**
 * Check if a given object implements the ChorusManageUserRoleInWorkspaceResult interface.
 */
export function instanceOfChorusManageUserRoleInWorkspaceResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusManageUserRoleInWorkspaceResultFromJSON(
  json: any
): ChorusManageUserRoleInWorkspaceResult {
  return ChorusManageUserRoleInWorkspaceResultFromJSONTyped(json, false)
}

export function ChorusManageUserRoleInWorkspaceResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusManageUserRoleInWorkspaceResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    workspace: !exists(json, 'workspace')
      ? undefined
      : ChorusWorkspaceFromJSON(json['workspace'])
  }
}

export function ChorusManageUserRoleInWorkspaceResultToJSON(
  value?: ChorusManageUserRoleInWorkspaceResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    workspace: ChorusWorkspaceToJSON(value.workspace)
  }
}
