/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusGetWorkspaceServiceInstanceResult } from './ChorusGetWorkspaceServiceInstanceResult'
import {
  ChorusGetWorkspaceServiceInstanceResultFromJSON,
  ChorusGetWorkspaceServiceInstanceResultFromJSONTyped,
  ChorusGetWorkspaceServiceInstanceResultToJSON
} from './ChorusGetWorkspaceServiceInstanceResult'

/**
 *
 * @export
 * @interface ChorusGetWorkspaceServiceInstanceReply
 */
export interface ChorusGetWorkspaceServiceInstanceReply {
  /**
   *
   * @type {ChorusGetWorkspaceServiceInstanceResult}
   * @memberof ChorusGetWorkspaceServiceInstanceReply
   */
  result?: ChorusGetWorkspaceServiceInstanceResult
}

/**
 * Check if a given object implements the ChorusGetWorkspaceServiceInstanceReply interface.
 */
export function instanceOfChorusGetWorkspaceServiceInstanceReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetWorkspaceServiceInstanceReplyFromJSON(
  json: any
): ChorusGetWorkspaceServiceInstanceReply {
  return ChorusGetWorkspaceServiceInstanceReplyFromJSONTyped(json, false)
}

export function ChorusGetWorkspaceServiceInstanceReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetWorkspaceServiceInstanceReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusGetWorkspaceServiceInstanceResultFromJSON(json['result'])
  }
}

export function ChorusGetWorkspaceServiceInstanceReplyToJSON(
  value?: ChorusGetWorkspaceServiceInstanceReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusGetWorkspaceServiceInstanceResultToJSON(value.result)
  }
}
