/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusUpdateUserResult } from './ChorusUpdateUserResult'
import {
  ChorusUpdateUserResultFromJSON,
  ChorusUpdateUserResultFromJSONTyped,
  ChorusUpdateUserResultToJSON
} from './ChorusUpdateUserResult'

/**
 *
 * @export
 * @interface ChorusUpdateUserReply
 */
export interface ChorusUpdateUserReply {
  /**
   *
   * @type {ChorusUpdateUserResult}
   * @memberof ChorusUpdateUserReply
   */
  result?: ChorusUpdateUserResult
}

/**
 * Check if a given object implements the ChorusUpdateUserReply interface.
 */
export function instanceOfChorusUpdateUserReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdateUserReplyFromJSON(
  json: any
): ChorusUpdateUserReply {
  return ChorusUpdateUserReplyFromJSONTyped(json, false)
}

export function ChorusUpdateUserReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdateUserReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusUpdateUserResultFromJSON(json['result'])
  }
}

export function ChorusUpdateUserReplyToJSON(
  value?: ChorusUpdateUserReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusUpdateUserResultToJSON(value.result)
  }
}
