/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusInitializeTenantResult
 */
export interface ChorusInitializeTenantResult {
  /**
   *
   * @type {string}
   * @memberof ChorusInitializeTenantResult
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof ChorusInitializeTenantResult
   */
  name?: string
  /**
   *
   * @type {Date}
   * @memberof ChorusInitializeTenantResult
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof ChorusInitializeTenantResult
   */
  updatedAt?: Date
}

/**
 * Check if a given object implements the ChorusInitializeTenantResult interface.
 */
export function instanceOfChorusInitializeTenantResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusInitializeTenantResultFromJSON(
  json: any
): ChorusInitializeTenantResult {
  return ChorusInitializeTenantResultFromJSONTyped(json, false)
}

export function ChorusInitializeTenantResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusInitializeTenantResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    name: !exists(json, 'name') ? undefined : json['name'],
    createdAt: !exists(json, 'createdAt')
      ? undefined
      : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt')
      ? undefined
      : new Date(json['updatedAt'])
  }
}

export function ChorusInitializeTenantResultToJSON(
  value?: ChorusInitializeTenantResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    name: value.name,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString()
  }
}
