/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusAppInstance } from './ChorusAppInstance'
import {
  ChorusAppInstanceFromJSON,
  ChorusAppInstanceFromJSONTyped,
  ChorusAppInstanceToJSON
} from './ChorusAppInstance'

/**
 *
 * @export
 * @interface ChorusDeleteAppInstanceResult
 */
export interface ChorusDeleteAppInstanceResult {
  /**
   *
   * @type {ChorusAppInstance}
   * @memberof ChorusDeleteAppInstanceResult
   */
  appInstance?: ChorusAppInstance
}

/**
 * Check if a given object implements the ChorusDeleteAppInstanceResult interface.
 */
export function instanceOfChorusDeleteAppInstanceResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusDeleteAppInstanceResultFromJSON(
  json: any
): ChorusDeleteAppInstanceResult {
  return ChorusDeleteAppInstanceResultFromJSONTyped(json, false)
}

export function ChorusDeleteAppInstanceResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusDeleteAppInstanceResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    appInstance: !exists(json, 'appInstance')
      ? undefined
      : ChorusAppInstanceFromJSON(json['appInstance'])
  }
}

export function ChorusDeleteAppInstanceResultToJSON(
  value?: ChorusDeleteAppInstanceResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    appInstance: ChorusAppInstanceToJSON(value.appInstance)
  }
}
