/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusOrganization } from './ChorusOrganization'
import {
  ChorusOrganizationFromJSON,
  ChorusOrganizationFromJSONTyped,
  ChorusOrganizationToJSON
} from './ChorusOrganization'

/**
 *
 * @export
 * @interface ChorusListOrganizationsResult
 */
export interface ChorusListOrganizationsResult {
  /**
   *
   * @type {Array<ChorusOrganization>}
   * @memberof ChorusListOrganizationsResult
   */
  organizations?: Array<ChorusOrganization>
}

/**
 * Check if a given object implements the ChorusListOrganizationsResult interface.
 */
export function instanceOfChorusListOrganizationsResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListOrganizationsResultFromJSON(
  json: any
): ChorusListOrganizationsResult {
  return ChorusListOrganizationsResultFromJSONTyped(json, false)
}

export function ChorusListOrganizationsResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListOrganizationsResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    organizations: !exists(json, 'organizations')
      ? undefined
      : (json['organizations'] as Array<any>).map(ChorusOrganizationFromJSON)
  }
}

export function ChorusListOrganizationsResultToJSON(
  value?: ChorusListOrganizationsResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    organizations:
      value.organizations === undefined
        ? undefined
        : (value.organizations as Array<any>).map(ChorusOrganizationToJSON)
  }
}
