/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusGetAppResult } from './ChorusGetAppResult'
import {
  ChorusGetAppResultFromJSON,
  ChorusGetAppResultFromJSONTyped,
  ChorusGetAppResultToJSON
} from './ChorusGetAppResult'

/**
 *
 * @export
 * @interface ChorusGetAppReply
 */
export interface ChorusGetAppReply {
  /**
   *
   * @type {ChorusGetAppResult}
   * @memberof ChorusGetAppReply
   */
  result?: ChorusGetAppResult
}

/**
 * Check if a given object implements the ChorusGetAppReply interface.
 */
export function instanceOfChorusGetAppReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetAppReplyFromJSON(json: any): ChorusGetAppReply {
  return ChorusGetAppReplyFromJSONTyped(json, false)
}

export function ChorusGetAppReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetAppReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusGetAppResultFromJSON(json['result'])
  }
}

export function ChorusGetAppReplyToJSON(value?: ChorusGetAppReply | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusGetAppResultToJSON(value.result)
  }
}
