/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusRefreshTokenResult
 */
export interface ChorusRefreshTokenResult {
  /**
   *
   * @type {string}
   * @memberof ChorusRefreshTokenResult
   */
  token?: string
}

/**
 * Check if a given object implements the ChorusRefreshTokenResult interface.
 */
export function instanceOfChorusRefreshTokenResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusRefreshTokenResultFromJSON(
  json: any
): ChorusRefreshTokenResult {
  return ChorusRefreshTokenResultFromJSONTyped(json, false)
}

export function ChorusRefreshTokenResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusRefreshTokenResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    token: !exists(json, 'token') ? undefined : json['token']
  }
}

export function ChorusRefreshTokenResultToJSON(
  value?: ChorusRefreshTokenResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    token: value.token
  }
}
