/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusUpdatePlatformSettingsResult } from './ChorusUpdatePlatformSettingsResult'
import {
  ChorusUpdatePlatformSettingsResultFromJSON,
  ChorusUpdatePlatformSettingsResultFromJSONTyped,
  ChorusUpdatePlatformSettingsResultToJSON
} from './ChorusUpdatePlatformSettingsResult'

/**
 *
 * @export
 * @interface ChorusUpdatePlatformSettingsReply
 */
export interface ChorusUpdatePlatformSettingsReply {
  /**
   *
   * @type {ChorusUpdatePlatformSettingsResult}
   * @memberof ChorusUpdatePlatformSettingsReply
   */
  result?: ChorusUpdatePlatformSettingsResult
}

/**
 * Check if a given object implements the ChorusUpdatePlatformSettingsReply interface.
 */
export function instanceOfChorusUpdatePlatformSettingsReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdatePlatformSettingsReplyFromJSON(
  json: any
): ChorusUpdatePlatformSettingsReply {
  return ChorusUpdatePlatformSettingsReplyFromJSONTyped(json, false)
}

export function ChorusUpdatePlatformSettingsReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdatePlatformSettingsReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusUpdatePlatformSettingsResultFromJSON(json['result'])
  }
}

export function ChorusUpdatePlatformSettingsReplyToJSON(
  value?: ChorusUpdatePlatformSettingsReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusUpdatePlatformSettingsResultToJSON(value.result)
  }
}
