/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspaceFile } from './ChorusWorkspaceFile'
import {
  ChorusWorkspaceFileFromJSON,
  ChorusWorkspaceFileFromJSONTyped,
  ChorusWorkspaceFileToJSON
} from './ChorusWorkspaceFile'

/**
 *
 * @export
 * @interface ChorusCreateWorkspaceFileResult
 */
export interface ChorusCreateWorkspaceFileResult {
  /**
   *
   * @type {ChorusWorkspaceFile}
   * @memberof ChorusCreateWorkspaceFileResult
   */
  file?: ChorusWorkspaceFile
}

/**
 * Check if a given object implements the ChorusCreateWorkspaceFileResult interface.
 */
export function instanceOfChorusCreateWorkspaceFileResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateWorkspaceFileResultFromJSON(
  json: any
): ChorusCreateWorkspaceFileResult {
  return ChorusCreateWorkspaceFileResultFromJSONTyped(json, false)
}

export function ChorusCreateWorkspaceFileResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateWorkspaceFileResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    file: !exists(json, 'file')
      ? undefined
      : ChorusWorkspaceFileFromJSON(json['file'])
  }
}

export function ChorusCreateWorkspaceFileResultToJSON(
  value?: ChorusCreateWorkspaceFileResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    file: ChorusWorkspaceFileToJSON(value.file)
  }
}
