/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusApp } from './ChorusApp'
import {
  ChorusAppFromJSON,
  ChorusAppFromJSONTyped,
  ChorusAppToJSON
} from './ChorusApp'

/**
 *
 * @export
 * @interface ChorusGetAppResult
 */
export interface ChorusGetAppResult {
  /**
   *
   * @type {ChorusApp}
   * @memberof ChorusGetAppResult
   */
  app?: ChorusApp
}

/**
 * Check if a given object implements the ChorusGetAppResult interface.
 */
export function instanceOfChorusGetAppResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetAppResultFromJSON(json: any): ChorusGetAppResult {
  return ChorusGetAppResultFromJSONTyped(json, false)
}

export function ChorusGetAppResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetAppResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    app: !exists(json, 'app') ? undefined : ChorusAppFromJSON(json['app'])
  }
}

export function ChorusGetAppResultToJSON(
  value?: ChorusGetAppResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    app: ChorusAppToJSON(value.app)
  }
}
