/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusAppInstance
 */
export interface ChorusAppInstance {
  /**
   *
   * @type {string}
   * @memberof ChorusAppInstance
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof ChorusAppInstance
   */
  tenantId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusAppInstance
   */
  userId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusAppInstance
   */
  appId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusAppInstance
   */
  workspaceId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusAppInstance
   */
  status?: string
  /**
   *
   * @type {Date}
   * @memberof ChorusAppInstance
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof ChorusAppInstance
   */
  updatedAt?: Date
}

/**
 * Check if a given object implements the ChorusAppInstance interface.
 */
export function instanceOfChorusAppInstance(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusAppInstanceFromJSON(json: any): ChorusAppInstance {
  return ChorusAppInstanceFromJSONTyped(json, false)
}

export function ChorusAppInstanceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusAppInstance {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    tenantId: !exists(json, 'tenantId') ? undefined : json['tenantId'],
    userId: !exists(json, 'userId') ? undefined : json['userId'],
    appId: !exists(json, 'appId') ? undefined : json['appId'],
    workspaceId: !exists(json, 'workspaceId') ? undefined : json['workspaceId'],
    status: !exists(json, 'status') ? undefined : json['status'],
    createdAt: !exists(json, 'createdAt')
      ? undefined
      : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt')
      ? undefined
      : new Date(json['updatedAt'])
  }
}

export function ChorusAppInstanceToJSON(value?: ChorusAppInstance | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    tenantId: value.tenantId,
    userId: value.userId,
    appId: value.appId,
    workspaceId: value.workspaceId,
    status: value.status,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString()
  }
}
