/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusUser } from './ChorusUser'
import {
  ChorusUserFromJSON,
  ChorusUserFromJSONTyped,
  ChorusUserToJSON
} from './ChorusUser'

/**
 *
 * @export
 * @interface ChorusGetUserMeResult
 */
export interface ChorusGetUserMeResult {
  /**
   *
   * @type {ChorusUser}
   * @memberof ChorusGetUserMeResult
   */
  me?: ChorusUser
}

/**
 * Check if a given object implements the ChorusGetUserMeResult interface.
 */
export function instanceOfChorusGetUserMeResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetUserMeResultFromJSON(
  json: any
): ChorusGetUserMeResult {
  return ChorusGetUserMeResultFromJSONTyped(json, false)
}

export function ChorusGetUserMeResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetUserMeResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    me: !exists(json, 'me') ? undefined : ChorusUserFromJSON(json['me'])
  }
}

export function ChorusGetUserMeResultToJSON(
  value?: ChorusGetUserMeResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    me: ChorusUserToJSON(value.me)
  }
}
