/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusUser } from './ChorusUser'
import {
  ChorusUserFromJSON,
  ChorusUserFromJSONTyped,
  ChorusUserToJSON
} from './ChorusUser'

/**
 *
 * @export
 * @interface ChorusUpdateUserRequest
 */
export interface ChorusUpdateUserRequest {
  /**
   *
   * @type {ChorusUser}
   * @memberof ChorusUpdateUserRequest
   */
  user?: ChorusUser
}

/**
 * Check if a given object implements the ChorusUpdateUserRequest interface.
 */
export function instanceOfChorusUpdateUserRequest(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdateUserRequestFromJSON(
  json: any
): ChorusUpdateUserRequest {
  return ChorusUpdateUserRequestFromJSONTyped(json, false)
}

export function ChorusUpdateUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdateUserRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    user: !exists(json, 'user') ? undefined : ChorusUserFromJSON(json['user'])
  }
}

export function ChorusUpdateUserRequestToJSON(
  value?: ChorusUpdateUserRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    user: ChorusUserToJSON(value.user)
  }
}
