/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusCountMyApprovalRequestsResult } from './ChorusCountMyApprovalRequestsResult'
import {
  ChorusCountMyApprovalRequestsResultFromJSON,
  ChorusCountMyApprovalRequestsResultFromJSONTyped,
  ChorusCountMyApprovalRequestsResultToJSON
} from './ChorusCountMyApprovalRequestsResult'

/**
 *
 * @export
 * @interface ChorusCountMyApprovalRequestsReply
 */
export interface ChorusCountMyApprovalRequestsReply {
  /**
   *
   * @type {ChorusCountMyApprovalRequestsResult}
   * @memberof ChorusCountMyApprovalRequestsReply
   */
  result?: ChorusCountMyApprovalRequestsResult
}

/**
 * Check if a given object implements the ChorusCountMyApprovalRequestsReply interface.
 */
export function instanceOfChorusCountMyApprovalRequestsReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCountMyApprovalRequestsReplyFromJSON(
  json: any
): ChorusCountMyApprovalRequestsReply {
  return ChorusCountMyApprovalRequestsReplyFromJSONTyped(json, false)
}

export function ChorusCountMyApprovalRequestsReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCountMyApprovalRequestsReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusCountMyApprovalRequestsResultFromJSON(json['result'])
  }
}

export function ChorusCountMyApprovalRequestsReplyToJSON(
  value?: ChorusCountMyApprovalRequestsReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusCountMyApprovalRequestsResultToJSON(value.result)
  }
}
