/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusApprovalRequestFile } from './ChorusApprovalRequestFile'
import {
  ChorusApprovalRequestFileFromJSON,
  ChorusApprovalRequestFileFromJSONTyped,
  ChorusApprovalRequestFileToJSON
} from './ChorusApprovalRequestFile'

/**
 *
 * @export
 * @interface ChorusDownloadApprovalRequestFileResult
 */
export interface ChorusDownloadApprovalRequestFileResult {
  /**
   *
   * @type {ChorusApprovalRequestFile}
   * @memberof ChorusDownloadApprovalRequestFileResult
   */
  file?: ChorusApprovalRequestFile
  /**
   *
   * @type {string}
   * @memberof ChorusDownloadApprovalRequestFileResult
   */
  content?: string
}

/**
 * Check if a given object implements the ChorusDownloadApprovalRequestFileResult interface.
 */
export function instanceOfChorusDownloadApprovalRequestFileResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusDownloadApprovalRequestFileResultFromJSON(
  json: any
): ChorusDownloadApprovalRequestFileResult {
  return ChorusDownloadApprovalRequestFileResultFromJSONTyped(json, false)
}

export function ChorusDownloadApprovalRequestFileResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusDownloadApprovalRequestFileResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    file: !exists(json, 'file')
      ? undefined
      : ChorusApprovalRequestFileFromJSON(json['file']),
    content: !exists(json, 'content') ? undefined : json['content']
  }
}

export function ChorusDownloadApprovalRequestFileResultToJSON(
  value?: ChorusDownloadApprovalRequestFileResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    file: ChorusApprovalRequestFileToJSON(value.file),
    content: value.content
  }
}
