/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusApprovalRequestStatus } from './ChorusApprovalRequestStatus'
import {
  ChorusApprovalRequestStatusFromJSON,
  ChorusApprovalRequestStatusFromJSONTyped,
  ChorusApprovalRequestStatusToJSON
} from './ChorusApprovalRequestStatus'
import type { ChorusApprovalRequestType } from './ChorusApprovalRequestType'
import {
  ChorusApprovalRequestTypeFromJSON,
  ChorusApprovalRequestTypeFromJSONTyped,
  ChorusApprovalRequestTypeToJSON
} from './ChorusApprovalRequestType'
import type { ChorusDataExtractionDetails } from './ChorusDataExtractionDetails'
import {
  ChorusDataExtractionDetailsFromJSON,
  ChorusDataExtractionDetailsFromJSONTyped,
  ChorusDataExtractionDetailsToJSON
} from './ChorusDataExtractionDetails'
import type { ChorusDataTransferDetails } from './ChorusDataTransferDetails'
import {
  ChorusDataTransferDetailsFromJSON,
  ChorusDataTransferDetailsFromJSONTyped,
  ChorusDataTransferDetailsToJSON
} from './ChorusDataTransferDetails'

/**
 *
 * @export
 * @interface ChorusApprovalRequest
 */
export interface ChorusApprovalRequest {
  /**
   *
   * @type {string}
   * @memberof ChorusApprovalRequest
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApprovalRequest
   */
  tenantId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApprovalRequest
   */
  requesterId?: string
  /**
   *
   * @type {ChorusApprovalRequestType}
   * @memberof ChorusApprovalRequest
   */
  type?: ChorusApprovalRequestType
  /**
   *
   * @type {ChorusApprovalRequestStatus}
   * @memberof ChorusApprovalRequest
   */
  status?: ChorusApprovalRequestStatus
  /**
   *
   * @type {string}
   * @memberof ChorusApprovalRequest
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof ChorusApprovalRequest
   */
  description?: string
  /**
   *
   * @type {ChorusDataExtractionDetails}
   * @memberof ChorusApprovalRequest
   */
  dataExtraction?: ChorusDataExtractionDetails
  /**
   *
   * @type {ChorusDataTransferDetails}
   * @memberof ChorusApprovalRequest
   */
  dataTransfer?: ChorusDataTransferDetails
  /**
   *
   * @type {Array<string>}
   * @memberof ChorusApprovalRequest
   */
  approverIds?: Array<string>
  /**
   *
   * @type {string}
   * @memberof ChorusApprovalRequest
   */
  approvedById?: string
  /**
   *
   * @type {Date}
   * @memberof ChorusApprovalRequest
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof ChorusApprovalRequest
   */
  updatedAt?: Date
  /**
   *
   * @type {Date}
   * @memberof ChorusApprovalRequest
   */
  approvedAt?: Date
  /**
   *
   * @type {boolean}
   * @memberof ChorusApprovalRequest
   */
  autoApproved?: boolean
  /**
   *
   * @type {string}
   * @memberof ChorusApprovalRequest
   */
  approvalMessage?: string
}

/**
 * Check if a given object implements the ChorusApprovalRequest interface.
 */
export function instanceOfChorusApprovalRequest(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusApprovalRequestFromJSON(
  json: any
): ChorusApprovalRequest {
  return ChorusApprovalRequestFromJSONTyped(json, false)
}

export function ChorusApprovalRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusApprovalRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    tenantId: !exists(json, 'tenantId') ? undefined : json['tenantId'],
    requesterId: !exists(json, 'requesterId') ? undefined : json['requesterId'],
    type: !exists(json, 'type')
      ? undefined
      : ChorusApprovalRequestTypeFromJSON(json['type']),
    status: !exists(json, 'status')
      ? undefined
      : ChorusApprovalRequestStatusFromJSON(json['status']),
    title: !exists(json, 'title') ? undefined : json['title'],
    description: !exists(json, 'description') ? undefined : json['description'],
    dataExtraction: !exists(json, 'dataExtraction')
      ? undefined
      : ChorusDataExtractionDetailsFromJSON(json['dataExtraction']),
    dataTransfer: !exists(json, 'dataTransfer')
      ? undefined
      : ChorusDataTransferDetailsFromJSON(json['dataTransfer']),
    approverIds: !exists(json, 'approverIds') ? undefined : json['approverIds'],
    approvedById: !exists(json, 'approvedById')
      ? undefined
      : json['approvedById'],
    createdAt: !exists(json, 'createdAt')
      ? undefined
      : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt')
      ? undefined
      : new Date(json['updatedAt']),
    approvedAt: !exists(json, 'approvedAt')
      ? undefined
      : new Date(json['approvedAt']),
    autoApproved: !exists(json, 'autoApproved')
      ? undefined
      : json['autoApproved'],
    approvalMessage: !exists(json, 'approvalMessage')
      ? undefined
      : json['approvalMessage']
  }
}

export function ChorusApprovalRequestToJSON(
  value?: ChorusApprovalRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    tenantId: value.tenantId,
    requesterId: value.requesterId,
    type: ChorusApprovalRequestTypeToJSON(value.type),
    status: ChorusApprovalRequestStatusToJSON(value.status),
    title: value.title,
    description: value.description,
    dataExtraction: ChorusDataExtractionDetailsToJSON(value.dataExtraction),
    dataTransfer: ChorusDataTransferDetailsToJSON(value.dataTransfer),
    approverIds: value.approverIds,
    approvedById: value.approvedById,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    approvedAt:
      value.approvedAt === undefined
        ? undefined
        : value.approvedAt.toISOString(),
    autoApproved: value.autoApproved,
    approvalMessage: value.approvalMessage
  }
}
