/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusChorusErrorCode } from './ChorusChorusErrorCode'
import {
  ChorusChorusErrorCodeFromJSON,
  ChorusChorusErrorCodeFromJSONTyped,
  ChorusChorusErrorCodeToJSON
} from './ChorusChorusErrorCode'
import type { ChorusValidationError } from './ChorusValidationError'
import {
  ChorusValidationErrorFromJSON,
  ChorusValidationErrorFromJSONTyped,
  ChorusValidationErrorToJSON
} from './ChorusValidationError'

/**
 * A single error occurrence; Chorus errors return exactly one in ChorusErrorResponse.details.
 * @export
 * @interface ChorusErrorDetail
 */
export interface ChorusErrorDetail {
  /**
   *
   * @type {ChorusChorusErrorCode}
   * @memberof ChorusErrorDetail
   */
  chorusCode?: ChorusChorusErrorCode
  /**
   *
   * @type {string}
   * @memberof ChorusErrorDetail
   */
  instance?: string
  /**
   *
   * @type {string}
   * @memberof ChorusErrorDetail
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof ChorusErrorDetail
   */
  message?: string
  /**
   *
   * @type {Array<ChorusValidationError>}
   * @memberof ChorusErrorDetail
   */
  validationErrors?: Array<ChorusValidationError>
  /**
   * Debug-only stack trace; empty unless server has stacktrace exposure enabled.
   * @type {string}
   * @memberof ChorusErrorDetail
   */
  stackTrace?: string
}

/**
 * Check if a given object implements the ChorusErrorDetail interface.
 */
export function instanceOfChorusErrorDetail(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusErrorDetailFromJSON(json: any): ChorusErrorDetail {
  return ChorusErrorDetailFromJSONTyped(json, false)
}

export function ChorusErrorDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusErrorDetail {
  if (json === undefined || json === null) {
    return json
  }
  return {
    chorusCode: !exists(json, 'chorusCode')
      ? undefined
      : ChorusChorusErrorCodeFromJSON(json['chorusCode']),
    instance: !exists(json, 'instance') ? undefined : json['instance'],
    title: !exists(json, 'title') ? undefined : json['title'],
    message: !exists(json, 'message') ? undefined : json['message'],
    validationErrors: !exists(json, 'validationErrors')
      ? undefined
      : (json['validationErrors'] as Array<any>).map(
          ChorusValidationErrorFromJSON
        ),
    stackTrace: !exists(json, 'stackTrace') ? undefined : json['stackTrace']
  }
}

export function ChorusErrorDetailToJSON(value?: ChorusErrorDetail | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    chorusCode: ChorusChorusErrorCodeToJSON(value.chorusCode),
    instance: value.instance,
    title: value.title,
    message: value.message,
    validationErrors:
      value.validationErrors === undefined
        ? undefined
        : (value.validationErrors as Array<any>).map(
            ChorusValidationErrorToJSON
          ),
    stackTrace: value.stackTrace
  }
}
