/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusOpenID
 */
export interface ChorusOpenID {
  /**
   *
   * @type {string}
   * @memberof ChorusOpenID
   */
  id?: string
}

/**
 * Check if a given object implements the ChorusOpenID interface.
 */
export function instanceOfChorusOpenID(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusOpenIDFromJSON(json: any): ChorusOpenID {
  return ChorusOpenIDFromJSONTyped(json, false)
}

export function ChorusOpenIDFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusOpenID {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id']
  }
}

export function ChorusOpenIDToJSON(value?: ChorusOpenID | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id
  }
}
