/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspaceStatus } from './ChorusWorkspaceStatus'
import {
  ChorusWorkspaceStatusFromJSON,
  ChorusWorkspaceStatusFromJSONTyped,
  ChorusWorkspaceStatusToJSON
} from './ChorusWorkspaceStatus'

/**
 *
 * @export
 * @interface ChorusPublicWorkspace
 */
export interface ChorusPublicWorkspace {
  /**
   *
   * @type {string}
   * @memberof ChorusPublicWorkspace
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPublicWorkspace
   */
  tenantId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPublicWorkspace
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPublicWorkspace
   */
  shortName?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPublicWorkspace
   */
  description?: string
  /**
   *
   * @type {ChorusWorkspaceStatus}
   * @memberof ChorusPublicWorkspace
   */
  status?: ChorusWorkspaceStatus
  /**
   *
   * @type {string}
   * @memberof ChorusPublicWorkspace
   */
  contactUsername?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPublicWorkspace
   */
  contactFirstName?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPublicWorkspace
   */
  contactLastName?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPublicWorkspace
   */
  contactEmail?: string
  /**
   *
   * @type {Date}
   * @memberof ChorusPublicWorkspace
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof ChorusPublicWorkspace
   */
  updatedAt?: Date
}

/**
 * Check if a given object implements the ChorusPublicWorkspace interface.
 */
export function instanceOfChorusPublicWorkspace(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusPublicWorkspaceFromJSON(
  json: any
): ChorusPublicWorkspace {
  return ChorusPublicWorkspaceFromJSONTyped(json, false)
}

export function ChorusPublicWorkspaceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusPublicWorkspace {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    tenantId: !exists(json, 'tenantId') ? undefined : json['tenantId'],
    name: !exists(json, 'name') ? undefined : json['name'],
    shortName: !exists(json, 'shortName') ? undefined : json['shortName'],
    description: !exists(json, 'description') ? undefined : json['description'],
    status: !exists(json, 'status')
      ? undefined
      : ChorusWorkspaceStatusFromJSON(json['status']),
    contactUsername: !exists(json, 'contactUsername')
      ? undefined
      : json['contactUsername'],
    contactFirstName: !exists(json, 'contactFirstName')
      ? undefined
      : json['contactFirstName'],
    contactLastName: !exists(json, 'contactLastName')
      ? undefined
      : json['contactLastName'],
    contactEmail: !exists(json, 'contactEmail')
      ? undefined
      : json['contactEmail'],
    createdAt: !exists(json, 'createdAt')
      ? undefined
      : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt')
      ? undefined
      : new Date(json['updatedAt'])
  }
}

export function ChorusPublicWorkspaceToJSON(
  value?: ChorusPublicWorkspace | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    tenantId: value.tenantId,
    name: value.name,
    shortName: value.shortName,
    description: value.description,
    status: ChorusWorkspaceStatusToJSON(value.status),
    contactUsername: value.contactUsername,
    contactFirstName: value.contactFirstName,
    contactLastName: value.contactLastName,
    contactEmail: value.contactEmail,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString()
  }
}
