/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusWorkspace
 */
export interface ChorusWorkspace {
  /**
   *
   * @type {string}
   * @memberof ChorusWorkspace
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof ChorusWorkspace
   */
  tenantId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusWorkspace
   */
  userId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusWorkspace
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof ChorusWorkspace
   */
  shortName?: string
  /**
   *
   * @type {string}
   * @memberof ChorusWorkspace
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof ChorusWorkspace
   */
  status?: string
  /**
   *
   * @type {boolean}
   * @memberof ChorusWorkspace
   */
  isMain?: boolean
  /**
   *
   * @type {Array<string>}
   * @memberof ChorusWorkspace
   */
  appInstanceIds?: Array<string>
  /**
   *
   * @type {Array<string>}
   * @memberof ChorusWorkspace
   */
  appInstances?: Array<string>
  /**
   *
   * @type {Date}
   * @memberof ChorusWorkspace
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof ChorusWorkspace
   */
  updatedAt?: Date
}

/**
 * Check if a given object implements the ChorusWorkspace interface.
 */
export function instanceOfChorusWorkspace(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusWorkspaceFromJSON(json: any): ChorusWorkspace {
  return ChorusWorkspaceFromJSONTyped(json, false)
}

export function ChorusWorkspaceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusWorkspace {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    tenantId: !exists(json, 'tenantId') ? undefined : json['tenantId'],
    userId: !exists(json, 'userId') ? undefined : json['userId'],
    name: !exists(json, 'name') ? undefined : json['name'],
    shortName: !exists(json, 'shortName') ? undefined : json['shortName'],
    description: !exists(json, 'description') ? undefined : json['description'],
    status: !exists(json, 'status') ? undefined : json['status'],
    isMain: !exists(json, 'isMain') ? undefined : json['isMain'],
    appInstanceIds: !exists(json, 'appInstanceIds')
      ? undefined
      : json['appInstanceIds'],
    appInstances: !exists(json, 'appInstances')
      ? undefined
      : json['appInstances'],
    createdAt: !exists(json, 'createdAt')
      ? undefined
      : new Date(json['createdAt']),
    updatedAt: !exists(json, 'updatedAt')
      ? undefined
      : new Date(json['updatedAt'])
  }
}

export function ChorusWorkspaceToJSON(value?: ChorusWorkspace | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    tenantId: value.tenantId,
    userId: value.userId,
    name: value.name,
    shortName: value.shortName,
    description: value.description,
    status: value.status,
    isMain: value.isMain,
    appInstanceIds: value.appInstanceIds,
    appInstances: value.appInstances,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString()
  }
}
