/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusAuditEntry
 */
export interface ChorusAuditEntry {
  /**
   * Unique identifier of the audit entry.
   * @type {string}
   * @memberof ChorusAuditEntry
   */
  id?: string
  /**
   * ID of the user who performed the action.
   * @type {string}
   * @memberof ChorusAuditEntry
   */
  actorId?: string
  /**
   * Username of the user who performed the action.
   * @type {string}
   * @memberof ChorusAuditEntry
   */
  actorUsername?: string
  /**
   * Correlation ID to trace the request across services.
   * @type {string}
   * @memberof ChorusAuditEntry
   */
  correlationId?: string
  /**
   * The type of action performed (e.g. CreateUser, DeleteWorkspace).
   * @type {string}
   * @memberof ChorusAuditEntry
   */
  action?: string
  /**
   * ID of the workspace related to this action, if applicable.
   * @type {string}
   * @memberof ChorusAuditEntry
   */
  workspaceId?: string
  /**
   * ID of the workbench related to this action, if applicable.
   * @type {string}
   * @memberof ChorusAuditEntry
   */
  workbenchId?: string
  /**
   * ID of the user targeted by this action, if applicable.
   * @type {string}
   * @memberof ChorusAuditEntry
   */
  userId?: string
  /**
   * Human-readable description of what happened.
   * @type {string}
   * @memberof ChorusAuditEntry
   */
  description?: string
  /**
   * Additional key-value metadata about the action.
   * @type {{ [key: string]: string; }}
   * @memberof ChorusAuditEntry
   */
  details?: { [key: string]: string }
  /**
   * Timestamp when the action occurred.
   * @type {Date}
   * @memberof ChorusAuditEntry
   */
  createdAt?: Date
}

/**
 * Check if a given object implements the ChorusAuditEntry interface.
 */
export function instanceOfChorusAuditEntry(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusAuditEntryFromJSON(json: any): ChorusAuditEntry {
  return ChorusAuditEntryFromJSONTyped(json, false)
}

export function ChorusAuditEntryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusAuditEntry {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    actorId: !exists(json, 'actorId') ? undefined : json['actorId'],
    actorUsername: !exists(json, 'actorUsername')
      ? undefined
      : json['actorUsername'],
    correlationId: !exists(json, 'correlationId')
      ? undefined
      : json['correlationId'],
    action: !exists(json, 'action') ? undefined : json['action'],
    workspaceId: !exists(json, 'workspaceId') ? undefined : json['workspaceId'],
    workbenchId: !exists(json, 'workbenchId') ? undefined : json['workbenchId'],
    userId: !exists(json, 'userId') ? undefined : json['userId'],
    description: !exists(json, 'description') ? undefined : json['description'],
    details: !exists(json, 'details') ? undefined : json['details'],
    createdAt: !exists(json, 'createdAt')
      ? undefined
      : new Date(json['createdAt'])
  }
}

export function ChorusAuditEntryToJSON(value?: ChorusAuditEntry | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    actorId: value.actorId,
    actorUsername: value.actorUsername,
    correlationId: value.correlationId,
    action: value.action,
    workspaceId: value.workspaceId,
    workbenchId: value.workbenchId,
    userId: value.userId,
    description: value.description,
    details: value.details,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString()
  }
}
