/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusUpdateAppInstanceResult } from './ChorusUpdateAppInstanceResult'
import {
  ChorusUpdateAppInstanceResultFromJSON,
  ChorusUpdateAppInstanceResultFromJSONTyped,
  ChorusUpdateAppInstanceResultToJSON
} from './ChorusUpdateAppInstanceResult'

/**
 *
 * @export
 * @interface ChorusUpdateAppInstanceReply
 */
export interface ChorusUpdateAppInstanceReply {
  /**
   *
   * @type {ChorusUpdateAppInstanceResult}
   * @memberof ChorusUpdateAppInstanceReply
   */
  result?: ChorusUpdateAppInstanceResult
}

/**
 * Check if a given object implements the ChorusUpdateAppInstanceReply interface.
 */
export function instanceOfChorusUpdateAppInstanceReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdateAppInstanceReplyFromJSON(
  json: any
): ChorusUpdateAppInstanceReply {
  return ChorusUpdateAppInstanceReplyFromJSONTyped(json, false)
}

export function ChorusUpdateAppInstanceReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdateAppInstanceReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusUpdateAppInstanceResultFromJSON(json['result'])
  }
}

export function ChorusUpdateAppInstanceReplyToJSON(
  value?: ChorusUpdateAppInstanceReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusUpdateAppInstanceResultToJSON(value.result)
  }
}
