/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusDeleteUserRoleResult } from './ChorusDeleteUserRoleResult'
import {
  ChorusDeleteUserRoleResultFromJSON,
  ChorusDeleteUserRoleResultFromJSONTyped,
  ChorusDeleteUserRoleResultToJSON
} from './ChorusDeleteUserRoleResult'

/**
 *
 * @export
 * @interface ChorusDeleteUserRoleReply
 */
export interface ChorusDeleteUserRoleReply {
  /**
   *
   * @type {ChorusDeleteUserRoleResult}
   * @memberof ChorusDeleteUserRoleReply
   */
  result?: ChorusDeleteUserRoleResult
}

/**
 * Check if a given object implements the ChorusDeleteUserRoleReply interface.
 */
export function instanceOfChorusDeleteUserRoleReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusDeleteUserRoleReplyFromJSON(
  json: any
): ChorusDeleteUserRoleReply {
  return ChorusDeleteUserRoleReplyFromJSONTyped(json, false)
}

export function ChorusDeleteUserRoleReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusDeleteUserRoleReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusDeleteUserRoleResultFromJSON(json['result'])
  }
}

export function ChorusDeleteUserRoleReplyToJSON(
  value?: ChorusDeleteUserRoleReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusDeleteUserRoleResultToJSON(value.result)
  }
}
