/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusAuditFilter
 */
export interface ChorusAuditFilter {
  /**
   *
   * @type {string}
   * @memberof ChorusAuditFilter
   */
  userId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusAuditFilter
   */
  workspaceId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusAuditFilter
   */
  workbenchId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusAuditFilter
   */
  action?: string
  /**
   *
   * @type {Date}
   * @memberof ChorusAuditFilter
   */
  fromTime?: Date
  /**
   *
   * @type {Date}
   * @memberof ChorusAuditFilter
   */
  toTime?: Date
}

/**
 * Check if a given object implements the ChorusAuditFilter interface.
 */
export function instanceOfChorusAuditFilter(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusAuditFilterFromJSON(json: any): ChorusAuditFilter {
  return ChorusAuditFilterFromJSONTyped(json, false)
}

export function ChorusAuditFilterFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusAuditFilter {
  if (json === undefined || json === null) {
    return json
  }
  return {
    userId: !exists(json, 'userId') ? undefined : json['userId'],
    workspaceId: !exists(json, 'workspaceId') ? undefined : json['workspaceId'],
    workbenchId: !exists(json, 'workbenchId') ? undefined : json['workbenchId'],
    action: !exists(json, 'action') ? undefined : json['action'],
    fromTime: !exists(json, 'fromTime')
      ? undefined
      : new Date(json['fromTime']),
    toTime: !exists(json, 'toTime') ? undefined : new Date(json['toTime'])
  }
}

export function ChorusAuditFilterToJSON(value?: ChorusAuditFilter | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    userId: value.userId,
    workspaceId: value.workspaceId,
    workbenchId: value.workbenchId,
    action: value.action,
    fromTime:
      value.fromTime === undefined ? undefined : value.fromTime.toISOString(),
    toTime: value.toTime === undefined ? undefined : value.toTime.toISOString()
  }
}
