/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusListAppInstancesResult } from './ChorusListAppInstancesResult'
import {
  ChorusListAppInstancesResultFromJSON,
  ChorusListAppInstancesResultFromJSONTyped,
  ChorusListAppInstancesResultToJSON
} from './ChorusListAppInstancesResult'
import type { ChorusPaginationResult } from './ChorusPaginationResult'
import {
  ChorusPaginationResultFromJSON,
  ChorusPaginationResultFromJSONTyped,
  ChorusPaginationResultToJSON
} from './ChorusPaginationResult'

/**
 *
 * @export
 * @interface ChorusListAppInstancesReply
 */
export interface ChorusListAppInstancesReply {
  /**
   *
   * @type {ChorusListAppInstancesResult}
   * @memberof ChorusListAppInstancesReply
   */
  result?: ChorusListAppInstancesResult
  /**
   *
   * @type {ChorusPaginationResult}
   * @memberof ChorusListAppInstancesReply
   */
  pagination?: ChorusPaginationResult
}

/**
 * Check if a given object implements the ChorusListAppInstancesReply interface.
 */
export function instanceOfChorusListAppInstancesReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListAppInstancesReplyFromJSON(
  json: any
): ChorusListAppInstancesReply {
  return ChorusListAppInstancesReplyFromJSONTyped(json, false)
}

export function ChorusListAppInstancesReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListAppInstancesReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusListAppInstancesResultFromJSON(json['result']),
    pagination: !exists(json, 'pagination')
      ? undefined
      : ChorusPaginationResultFromJSON(json['pagination'])
  }
}

export function ChorusListAppInstancesReplyToJSON(
  value?: ChorusListAppInstancesReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusListAppInstancesResultToJSON(value.result),
    pagination: ChorusPaginationResultToJSON(value.pagination)
  }
}
