/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusAuthorizationRole
 */
export interface ChorusAuthorizationRole {
  /**
   *
   * @type {string}
   * @memberof ChorusAuthorizationRole
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof ChorusAuthorizationRole
   */
  description?: string
  /**
   *
   * @type {Array<string>}
   * @memberof ChorusAuthorizationRole
   */
  context?: Array<string>
}

/**
 * Check if a given object implements the ChorusAuthorizationRole interface.
 */
export function instanceOfChorusAuthorizationRole(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusAuthorizationRoleFromJSON(
  json: any
): ChorusAuthorizationRole {
  return ChorusAuthorizationRoleFromJSONTyped(json, false)
}

export function ChorusAuthorizationRoleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusAuthorizationRole {
  if (json === undefined || json === null) {
    return json
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
    context: !exists(json, 'context') ? undefined : json['context']
  }
}

export function ChorusAuthorizationRoleToJSON(
  value?: ChorusAuthorizationRole | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name,
    description: value.description,
    context: value.context
  }
}
