/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusGetWorkspaceFileResult } from './ChorusGetWorkspaceFileResult'
import {
  ChorusGetWorkspaceFileResultFromJSON,
  ChorusGetWorkspaceFileResultFromJSONTyped,
  ChorusGetWorkspaceFileResultToJSON
} from './ChorusGetWorkspaceFileResult'

/**
 *
 * @export
 * @interface ChorusGetWorkspaceFileReply
 */
export interface ChorusGetWorkspaceFileReply {
  /**
   *
   * @type {ChorusGetWorkspaceFileResult}
   * @memberof ChorusGetWorkspaceFileReply
   */
  result?: ChorusGetWorkspaceFileResult
}

/**
 * Check if a given object implements the ChorusGetWorkspaceFileReply interface.
 */
export function instanceOfChorusGetWorkspaceFileReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetWorkspaceFileReplyFromJSON(
  json: any
): ChorusGetWorkspaceFileReply {
  return ChorusGetWorkspaceFileReplyFromJSONTyped(json, false)
}

export function ChorusGetWorkspaceFileReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetWorkspaceFileReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusGetWorkspaceFileResultFromJSON(json['result'])
  }
}

export function ChorusGetWorkspaceFileReplyToJSON(
  value?: ChorusGetWorkspaceFileReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusGetWorkspaceFileResultToJSON(value.result)
  }
}
