/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusCreateAppInstanceResult } from './ChorusCreateAppInstanceResult'
import {
  ChorusCreateAppInstanceResultFromJSON,
  ChorusCreateAppInstanceResultFromJSONTyped,
  ChorusCreateAppInstanceResultToJSON
} from './ChorusCreateAppInstanceResult'

/**
 *
 * @export
 * @interface ChorusCreateAppInstanceReply
 */
export interface ChorusCreateAppInstanceReply {
  /**
   *
   * @type {ChorusCreateAppInstanceResult}
   * @memberof ChorusCreateAppInstanceReply
   */
  result?: ChorusCreateAppInstanceResult
}

/**
 * Check if a given object implements the ChorusCreateAppInstanceReply interface.
 */
export function instanceOfChorusCreateAppInstanceReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateAppInstanceReplyFromJSON(
  json: any
): ChorusCreateAppInstanceReply {
  return ChorusCreateAppInstanceReplyFromJSONTyped(json, false)
}

export function ChorusCreateAppInstanceReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateAppInstanceReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusCreateAppInstanceResultFromJSON(json['result'])
  }
}

export function ChorusCreateAppInstanceReplyToJSON(
  value?: ChorusCreateAppInstanceReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusCreateAppInstanceResultToJSON(value.result)
  }
}
