/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusInitializeTenantResult } from './ChorusInitializeTenantResult'
import {
  ChorusInitializeTenantResultFromJSON,
  ChorusInitializeTenantResultFromJSONTyped,
  ChorusInitializeTenantResultToJSON
} from './ChorusInitializeTenantResult'

/**
 *
 * @export
 * @interface ChorusInitializeTenantReply
 */
export interface ChorusInitializeTenantReply {
  /**
   *
   * @type {ChorusInitializeTenantResult}
   * @memberof ChorusInitializeTenantReply
   */
  result?: ChorusInitializeTenantResult
}

/**
 * Check if a given object implements the ChorusInitializeTenantReply interface.
 */
export function instanceOfChorusInitializeTenantReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusInitializeTenantReplyFromJSON(
  json: any
): ChorusInitializeTenantReply {
  return ChorusInitializeTenantReplyFromJSONTyped(json, false)
}

export function ChorusInitializeTenantReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusInitializeTenantReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusInitializeTenantResultFromJSON(json['result'])
  }
}

export function ChorusInitializeTenantReplyToJSON(
  value?: ChorusInitializeTenantReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusInitializeTenantResultToJSON(value.result)
  }
}
