/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusApprovalRequest } from './ChorusApprovalRequest'
import {
  ChorusApprovalRequestFromJSON,
  ChorusApprovalRequestFromJSONTyped,
  ChorusApprovalRequestToJSON
} from './ChorusApprovalRequest'

/**
 *
 * @export
 * @interface ChorusCreateDataTransferRequestResult
 */
export interface ChorusCreateDataTransferRequestResult {
  /**
   *
   * @type {ChorusApprovalRequest}
   * @memberof ChorusCreateDataTransferRequestResult
   */
  approvalRequest?: ChorusApprovalRequest
}

/**
 * Check if a given object implements the ChorusCreateDataTransferRequestResult interface.
 */
export function instanceOfChorusCreateDataTransferRequestResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateDataTransferRequestResultFromJSON(
  json: any
): ChorusCreateDataTransferRequestResult {
  return ChorusCreateDataTransferRequestResultFromJSONTyped(json, false)
}

export function ChorusCreateDataTransferRequestResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateDataTransferRequestResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    approvalRequest: !exists(json, 'approvalRequest')
      ? undefined
      : ChorusApprovalRequestFromJSON(json['approvalRequest'])
  }
}

export function ChorusCreateDataTransferRequestResultToJSON(
  value?: ChorusCreateDataTransferRequestResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    approvalRequest: ChorusApprovalRequestToJSON(value.approvalRequest)
  }
}
