/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusInitiateWorkspaceFileUploadResult } from './ChorusInitiateWorkspaceFileUploadResult'
import {
  ChorusInitiateWorkspaceFileUploadResultFromJSON,
  ChorusInitiateWorkspaceFileUploadResultFromJSONTyped,
  ChorusInitiateWorkspaceFileUploadResultToJSON
} from './ChorusInitiateWorkspaceFileUploadResult'

/**
 *
 * @export
 * @interface ChorusInitiateWorkspaceFileUploadReply
 */
export interface ChorusInitiateWorkspaceFileUploadReply {
  /**
   *
   * @type {ChorusInitiateWorkspaceFileUploadResult}
   * @memberof ChorusInitiateWorkspaceFileUploadReply
   */
  result?: ChorusInitiateWorkspaceFileUploadResult
}

/**
 * Check if a given object implements the ChorusInitiateWorkspaceFileUploadReply interface.
 */
export function instanceOfChorusInitiateWorkspaceFileUploadReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusInitiateWorkspaceFileUploadReplyFromJSON(
  json: any
): ChorusInitiateWorkspaceFileUploadReply {
  return ChorusInitiateWorkspaceFileUploadReplyFromJSONTyped(json, false)
}

export function ChorusInitiateWorkspaceFileUploadReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusInitiateWorkspaceFileUploadReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusInitiateWorkspaceFileUploadResultFromJSON(json['result'])
  }
}

export function ChorusInitiateWorkspaceFileUploadReplyToJSON(
  value?: ChorusInitiateWorkspaceFileUploadReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusInitiateWorkspaceFileUploadResultToJSON(value.result)
  }
}
