/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusWorkspaceFilePart
 */
export interface ChorusWorkspaceFilePart {
  /**
   *
   * @type {string}
   * @memberof ChorusWorkspaceFilePart
   */
  partNumber?: string
  /**
   *
   * @type {string}
   * @memberof ChorusWorkspaceFilePart
   */
  data?: string
  /**
   *
   * @type {string}
   * @memberof ChorusWorkspaceFilePart
   */
  etag?: string
}

/**
 * Check if a given object implements the ChorusWorkspaceFilePart interface.
 */
export function instanceOfChorusWorkspaceFilePart(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusWorkspaceFilePartFromJSON(
  json: any
): ChorusWorkspaceFilePart {
  return ChorusWorkspaceFilePartFromJSONTyped(json, false)
}

export function ChorusWorkspaceFilePartFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusWorkspaceFilePart {
  if (json === undefined || json === null) {
    return json
  }
  return {
    partNumber: !exists(json, 'partNumber') ? undefined : json['partNumber'],
    data: !exists(json, 'data') ? undefined : json['data'],
    etag: !exists(json, 'etag') ? undefined : json['etag']
  }
}

export function ChorusWorkspaceFilePartToJSON(
  value?: ChorusWorkspaceFilePart | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    partNumber: value.partNumber,
    data: value.data,
    etag: value.etag
  }
}
