/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusCreateTermsOfUseVersionResult } from './ChorusCreateTermsOfUseVersionResult'
import {
  ChorusCreateTermsOfUseVersionResultFromJSON,
  ChorusCreateTermsOfUseVersionResultFromJSONTyped,
  ChorusCreateTermsOfUseVersionResultToJSON
} from './ChorusCreateTermsOfUseVersionResult'

/**
 *
 * @export
 * @interface ChorusCreateTermsOfUseVersionReply
 */
export interface ChorusCreateTermsOfUseVersionReply {
  /**
   *
   * @type {ChorusCreateTermsOfUseVersionResult}
   * @memberof ChorusCreateTermsOfUseVersionReply
   */
  result?: ChorusCreateTermsOfUseVersionResult
}

/**
 * Check if a given object implements the ChorusCreateTermsOfUseVersionReply interface.
 */
export function instanceOfChorusCreateTermsOfUseVersionReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateTermsOfUseVersionReplyFromJSON(
  json: any
): ChorusCreateTermsOfUseVersionReply {
  return ChorusCreateTermsOfUseVersionReplyFromJSONTyped(json, false)
}

export function ChorusCreateTermsOfUseVersionReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateTermsOfUseVersionReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusCreateTermsOfUseVersionResultFromJSON(json['result'])
  }
}

export function ChorusCreateTermsOfUseVersionReplyToJSON(
  value?: ChorusCreateTermsOfUseVersionReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusCreateTermsOfUseVersionResultToJSON(value.result)
  }
}
