/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusOrganization } from './ChorusOrganization'
import {
  ChorusOrganizationFromJSON,
  ChorusOrganizationFromJSONTyped,
  ChorusOrganizationToJSON
} from './ChorusOrganization'

/**
 *
 * @export
 * @interface ChorusGetOrganizationResult
 */
export interface ChorusGetOrganizationResult {
  /**
   *
   * @type {ChorusOrganization}
   * @memberof ChorusGetOrganizationResult
   */
  organization?: ChorusOrganization
}

/**
 * Check if a given object implements the ChorusGetOrganizationResult interface.
 */
export function instanceOfChorusGetOrganizationResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetOrganizationResultFromJSON(
  json: any
): ChorusGetOrganizationResult {
  return ChorusGetOrganizationResultFromJSONTyped(json, false)
}

export function ChorusGetOrganizationResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetOrganizationResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    organization: !exists(json, 'organization')
      ? undefined
      : ChorusOrganizationFromJSON(json['organization'])
  }
}

export function ChorusGetOrganizationResultToJSON(
  value?: ChorusGetOrganizationResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    organization: ChorusOrganizationToJSON(value.organization)
  }
}
