/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ChorusApprovalRequestType = {
  Unspecified: 'APPROVAL_REQUEST_TYPE_UNSPECIFIED',
  DataExtraction: 'APPROVAL_REQUEST_TYPE_DATA_EXTRACTION',
  DataTransfer: 'APPROVAL_REQUEST_TYPE_DATA_TRANSFER'
} as const
export type ChorusApprovalRequestType =
  (typeof ChorusApprovalRequestType)[keyof typeof ChorusApprovalRequestType]

export function ChorusApprovalRequestTypeFromJSON(
  json: any
): ChorusApprovalRequestType {
  return ChorusApprovalRequestTypeFromJSONTyped(json, false)
}

export function ChorusApprovalRequestTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusApprovalRequestType {
  return json as ChorusApprovalRequestType
}

export function ChorusApprovalRequestTypeToJSON(
  value?: ChorusApprovalRequestType | null
): any {
  return value as any
}
