/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusInitializeTenantRequest
 */
export interface ChorusInitializeTenantRequest {
  /**
   *
   * @type {string}
   * @memberof ChorusInitializeTenantRequest
   */
  name?: string
}

/**
 * Check if a given object implements the ChorusInitializeTenantRequest interface.
 */
export function instanceOfChorusInitializeTenantRequest(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusInitializeTenantRequestFromJSON(
  json: any
): ChorusInitializeTenantRequest {
  return ChorusInitializeTenantRequestFromJSONTyped(json, false)
}

export function ChorusInitializeTenantRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusInitializeTenantRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name']
  }
}

export function ChorusInitializeTenantRequestToJSON(
  value?: ChorusInitializeTenantRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name
  }
}
