/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusGetCurrentTermsOfUseVersionResult } from './ChorusGetCurrentTermsOfUseVersionResult'
import {
  ChorusGetCurrentTermsOfUseVersionResultFromJSON,
  ChorusGetCurrentTermsOfUseVersionResultFromJSONTyped,
  ChorusGetCurrentTermsOfUseVersionResultToJSON
} from './ChorusGetCurrentTermsOfUseVersionResult'

/**
 *
 * @export
 * @interface ChorusGetCurrentTermsOfUseVersionReply
 */
export interface ChorusGetCurrentTermsOfUseVersionReply {
  /**
   *
   * @type {ChorusGetCurrentTermsOfUseVersionResult}
   * @memberof ChorusGetCurrentTermsOfUseVersionReply
   */
  result?: ChorusGetCurrentTermsOfUseVersionResult
}

/**
 * Check if a given object implements the ChorusGetCurrentTermsOfUseVersionReply interface.
 */
export function instanceOfChorusGetCurrentTermsOfUseVersionReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetCurrentTermsOfUseVersionReplyFromJSON(
  json: any
): ChorusGetCurrentTermsOfUseVersionReply {
  return ChorusGetCurrentTermsOfUseVersionReplyFromJSONTyped(json, false)
}

export function ChorusGetCurrentTermsOfUseVersionReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetCurrentTermsOfUseVersionReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusGetCurrentTermsOfUseVersionResultFromJSON(json['result'])
  }
}

export function ChorusGetCurrentTermsOfUseVersionReplyToJSON(
  value?: ChorusGetCurrentTermsOfUseVersionReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusGetCurrentTermsOfUseVersionResultToJSON(value.result)
  }
}
