/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusAuthenticationMode } from './ChorusAuthenticationMode'
import {
  ChorusAuthenticationModeFromJSON,
  ChorusAuthenticationModeFromJSONTyped,
  ChorusAuthenticationModeToJSON
} from './ChorusAuthenticationMode'

/**
 *
 * @export
 * @interface ChorusGetAuthenticationModesResult
 */
export interface ChorusGetAuthenticationModesResult {
  /**
   *
   * @type {Array<ChorusAuthenticationMode>}
   * @memberof ChorusGetAuthenticationModesResult
   */
  modes?: Array<ChorusAuthenticationMode>
}

/**
 * Check if a given object implements the ChorusGetAuthenticationModesResult interface.
 */
export function instanceOfChorusGetAuthenticationModesResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetAuthenticationModesResultFromJSON(
  json: any
): ChorusGetAuthenticationModesResult {
  return ChorusGetAuthenticationModesResultFromJSONTyped(json, false)
}

export function ChorusGetAuthenticationModesResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetAuthenticationModesResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    modes: !exists(json, 'modes')
      ? undefined
      : (json['modes'] as Array<any>).map(ChorusAuthenticationModeFromJSON)
  }
}

export function ChorusGetAuthenticationModesResultToJSON(
  value?: ChorusGetAuthenticationModesResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    modes:
      value.modes === undefined
        ? undefined
        : (value.modes as Array<any>).map(ChorusAuthenticationModeToJSON)
  }
}
