/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusCountMyApprovalRequestsResult
 */
export interface ChorusCountMyApprovalRequestsResult {
  /**
   *
   * @type {string}
   * @memberof ChorusCountMyApprovalRequestsResult
   */
  total?: string
  /**
   *
   * @type {string}
   * @memberof ChorusCountMyApprovalRequestsResult
   */
  totalApprover?: string
  /**
   *
   * @type {string}
   * @memberof ChorusCountMyApprovalRequestsResult
   */
  totalRequester?: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ChorusCountMyApprovalRequestsResult
   */
  countByStatus?: { [key: string]: string }
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ChorusCountMyApprovalRequestsResult
   */
  countByType?: { [key: string]: string }
}

/**
 * Check if a given object implements the ChorusCountMyApprovalRequestsResult interface.
 */
export function instanceOfChorusCountMyApprovalRequestsResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCountMyApprovalRequestsResultFromJSON(
  json: any
): ChorusCountMyApprovalRequestsResult {
  return ChorusCountMyApprovalRequestsResultFromJSONTyped(json, false)
}

export function ChorusCountMyApprovalRequestsResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCountMyApprovalRequestsResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    total: !exists(json, 'total') ? undefined : json['total'],
    totalApprover: !exists(json, 'totalApprover')
      ? undefined
      : json['totalApprover'],
    totalRequester: !exists(json, 'totalRequester')
      ? undefined
      : json['totalRequester'],
    countByStatus: !exists(json, 'countByStatus')
      ? undefined
      : json['countByStatus'],
    countByType: !exists(json, 'countByType') ? undefined : json['countByType']
  }
}

export function ChorusCountMyApprovalRequestsResultToJSON(
  value?: ChorusCountMyApprovalRequestsResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    total: value.total,
    totalApprover: value.totalApprover,
    totalRequester: value.totalRequester,
    countByStatus: value.countByStatus,
    countByType: value.countByType
  }
}
