/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusCreateUserResult } from './ChorusCreateUserResult'
import {
  ChorusCreateUserResultFromJSON,
  ChorusCreateUserResultFromJSONTyped,
  ChorusCreateUserResultToJSON
} from './ChorusCreateUserResult'

/**
 *
 * @export
 * @interface ChorusCreateUserReply
 */
export interface ChorusCreateUserReply {
  /**
   *
   * @type {ChorusCreateUserResult}
   * @memberof ChorusCreateUserReply
   */
  result?: ChorusCreateUserResult
}

/**
 * Check if a given object implements the ChorusCreateUserReply interface.
 */
export function instanceOfChorusCreateUserReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateUserReplyFromJSON(
  json: any
): ChorusCreateUserReply {
  return ChorusCreateUserReplyFromJSONTyped(json, false)
}

export function ChorusCreateUserReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateUserReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusCreateUserResultFromJSON(json['result'])
  }
}

export function ChorusCreateUserReplyToJSON(
  value?: ChorusCreateUserReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusCreateUserResultToJSON(value.result)
  }
}
