/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusGetOrganizationResult } from './ChorusGetOrganizationResult'
import {
  ChorusGetOrganizationResultFromJSON,
  ChorusGetOrganizationResultFromJSONTyped,
  ChorusGetOrganizationResultToJSON
} from './ChorusGetOrganizationResult'

/**
 *
 * @export
 * @interface ChorusGetOrganizationReply
 */
export interface ChorusGetOrganizationReply {
  /**
   *
   * @type {ChorusGetOrganizationResult}
   * @memberof ChorusGetOrganizationReply
   */
  result?: ChorusGetOrganizationResult
}

/**
 * Check if a given object implements the ChorusGetOrganizationReply interface.
 */
export function instanceOfChorusGetOrganizationReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusGetOrganizationReplyFromJSON(
  json: any
): ChorusGetOrganizationReply {
  return ChorusGetOrganizationReplyFromJSONTyped(json, false)
}

export function ChorusGetOrganizationReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusGetOrganizationReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusGetOrganizationResultFromJSON(json['result'])
  }
}

export function ChorusGetOrganizationReplyToJSON(
  value?: ChorusGetOrganizationReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusGetOrganizationResultToJSON(value.result)
  }
}
