/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspaceFileStoreInfo } from './ChorusWorkspaceFileStoreInfo'
import {
  ChorusWorkspaceFileStoreInfoFromJSON,
  ChorusWorkspaceFileStoreInfoFromJSONTyped,
  ChorusWorkspaceFileStoreInfoToJSON
} from './ChorusWorkspaceFileStoreInfo'

/**
 *
 * @export
 * @interface ChorusListWorkspaceFileStoresResult
 */
export interface ChorusListWorkspaceFileStoresResult {
  /**
   *
   * @type {Array<ChorusWorkspaceFileStoreInfo>}
   * @memberof ChorusListWorkspaceFileStoresResult
   */
  stores?: Array<ChorusWorkspaceFileStoreInfo>
}

/**
 * Check if a given object implements the ChorusListWorkspaceFileStoresResult interface.
 */
export function instanceOfChorusListWorkspaceFileStoresResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListWorkspaceFileStoresResultFromJSON(
  json: any
): ChorusListWorkspaceFileStoresResult {
  return ChorusListWorkspaceFileStoresResultFromJSONTyped(json, false)
}

export function ChorusListWorkspaceFileStoresResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListWorkspaceFileStoresResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    stores: !exists(json, 'stores')
      ? undefined
      : (json['stores'] as Array<any>).map(ChorusWorkspaceFileStoreInfoFromJSON)
  }
}

export function ChorusListWorkspaceFileStoresResultToJSON(
  value?: ChorusListWorkspaceFileStoresResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    stores:
      value.stores === undefined
        ? undefined
        : (value.stores as Array<any>).map(ChorusWorkspaceFileStoreInfoToJSON)
  }
}
