/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusListUsersResult } from './ChorusListUsersResult'
import {
  ChorusListUsersResultFromJSON,
  ChorusListUsersResultFromJSONTyped,
  ChorusListUsersResultToJSON
} from './ChorusListUsersResult'
import type { ChorusPaginationResult } from './ChorusPaginationResult'
import {
  ChorusPaginationResultFromJSON,
  ChorusPaginationResultFromJSONTyped,
  ChorusPaginationResultToJSON
} from './ChorusPaginationResult'

/**
 *
 * @export
 * @interface ChorusListUsersReply
 */
export interface ChorusListUsersReply {
  /**
   *
   * @type {ChorusListUsersResult}
   * @memberof ChorusListUsersReply
   */
  result?: ChorusListUsersResult
  /**
   *
   * @type {ChorusPaginationResult}
   * @memberof ChorusListUsersReply
   */
  pagination?: ChorusPaginationResult
}

/**
 * Check if a given object implements the ChorusListUsersReply interface.
 */
export function instanceOfChorusListUsersReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListUsersReplyFromJSON(json: any): ChorusListUsersReply {
  return ChorusListUsersReplyFromJSONTyped(json, false)
}

export function ChorusListUsersReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListUsersReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusListUsersResultFromJSON(json['result']),
    pagination: !exists(json, 'pagination')
      ? undefined
      : ChorusPaginationResultFromJSON(json['pagination'])
  }
}

export function ChorusListUsersReplyToJSON(
  value?: ChorusListUsersReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusListUsersResultToJSON(value.result),
    pagination: ChorusPaginationResultToJSON(value.pagination)
  }
}
