/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspaceServiceInstance } from './ChorusWorkspaceServiceInstance'
import {
  ChorusWorkspaceServiceInstanceFromJSON,
  ChorusWorkspaceServiceInstanceFromJSONTyped,
  ChorusWorkspaceServiceInstanceToJSON
} from './ChorusWorkspaceServiceInstance'

/**
 *
 * @export
 * @interface ChorusDeleteWorkspaceServiceInstanceResult
 */
export interface ChorusDeleteWorkspaceServiceInstanceResult {
  /**
   *
   * @type {ChorusWorkspaceServiceInstance}
   * @memberof ChorusDeleteWorkspaceServiceInstanceResult
   */
  workspaceServiceInstance?: ChorusWorkspaceServiceInstance
}

/**
 * Check if a given object implements the ChorusDeleteWorkspaceServiceInstanceResult interface.
 */
export function instanceOfChorusDeleteWorkspaceServiceInstanceResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusDeleteWorkspaceServiceInstanceResultFromJSON(
  json: any
): ChorusDeleteWorkspaceServiceInstanceResult {
  return ChorusDeleteWorkspaceServiceInstanceResultFromJSONTyped(json, false)
}

export function ChorusDeleteWorkspaceServiceInstanceResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusDeleteWorkspaceServiceInstanceResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    workspaceServiceInstance: !exists(json, 'workspaceServiceInstance')
      ? undefined
      : ChorusWorkspaceServiceInstanceFromJSON(json['workspaceServiceInstance'])
  }
}

export function ChorusDeleteWorkspaceServiceInstanceResultToJSON(
  value?: ChorusDeleteWorkspaceServiceInstanceResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    workspaceServiceInstance: ChorusWorkspaceServiceInstanceToJSON(
      value.workspaceServiceInstance
    )
  }
}
