/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusAuthorizationRole } from './ChorusAuthorizationRole'
import {
  ChorusAuthorizationRoleFromJSON,
  ChorusAuthorizationRoleFromJSONTyped,
  ChorusAuthorizationRoleToJSON
} from './ChorusAuthorizationRole'

/**
 *
 * @export
 * @interface ChorusCreateDynamicRoleResult
 */
export interface ChorusCreateDynamicRoleResult {
  /**
   *
   * @type {ChorusAuthorizationRole}
   * @memberof ChorusCreateDynamicRoleResult
   */
  role?: ChorusAuthorizationRole
}

/**
 * Check if a given object implements the ChorusCreateDynamicRoleResult interface.
 */
export function instanceOfChorusCreateDynamicRoleResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateDynamicRoleResultFromJSON(
  json: any
): ChorusCreateDynamicRoleResult {
  return ChorusCreateDynamicRoleResultFromJSONTyped(json, false)
}

export function ChorusCreateDynamicRoleResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateDynamicRoleResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    role: !exists(json, 'role')
      ? undefined
      : ChorusAuthorizationRoleFromJSON(json['role'])
  }
}

export function ChorusCreateDynamicRoleResultToJSON(
  value?: ChorusCreateDynamicRoleResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    role: ChorusAuthorizationRoleToJSON(value.role)
  }
}
