/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusListWorkspaceServiceInstancesResult } from './ChorusListWorkspaceServiceInstancesResult'
import {
  ChorusListWorkspaceServiceInstancesResultFromJSON,
  ChorusListWorkspaceServiceInstancesResultFromJSONTyped,
  ChorusListWorkspaceServiceInstancesResultToJSON
} from './ChorusListWorkspaceServiceInstancesResult'
import type { ChorusPaginationResult } from './ChorusPaginationResult'
import {
  ChorusPaginationResultFromJSON,
  ChorusPaginationResultFromJSONTyped,
  ChorusPaginationResultToJSON
} from './ChorusPaginationResult'

/**
 *
 * @export
 * @interface ChorusListWorkspaceServiceInstancesReply
 */
export interface ChorusListWorkspaceServiceInstancesReply {
  /**
   *
   * @type {ChorusListWorkspaceServiceInstancesResult}
   * @memberof ChorusListWorkspaceServiceInstancesReply
   */
  result?: ChorusListWorkspaceServiceInstancesResult
  /**
   *
   * @type {ChorusPaginationResult}
   * @memberof ChorusListWorkspaceServiceInstancesReply
   */
  pagination?: ChorusPaginationResult
}

/**
 * Check if a given object implements the ChorusListWorkspaceServiceInstancesReply interface.
 */
export function instanceOfChorusListWorkspaceServiceInstancesReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListWorkspaceServiceInstancesReplyFromJSON(
  json: any
): ChorusListWorkspaceServiceInstancesReply {
  return ChorusListWorkspaceServiceInstancesReplyFromJSONTyped(json, false)
}

export function ChorusListWorkspaceServiceInstancesReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListWorkspaceServiceInstancesReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusListWorkspaceServiceInstancesResultFromJSON(json['result']),
    pagination: !exists(json, 'pagination')
      ? undefined
      : ChorusPaginationResultFromJSON(json['pagination'])
  }
}

export function ChorusListWorkspaceServiceInstancesReplyToJSON(
  value?: ChorusListWorkspaceServiceInstancesReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusListWorkspaceServiceInstancesResultToJSON(value.result),
    pagination: ChorusPaginationResultToJSON(value.pagination)
  }
}
