/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusListPublicWorkspacesResult } from './ChorusListPublicWorkspacesResult'
import {
  ChorusListPublicWorkspacesResultFromJSON,
  ChorusListPublicWorkspacesResultFromJSONTyped,
  ChorusListPublicWorkspacesResultToJSON
} from './ChorusListPublicWorkspacesResult'
import type { ChorusPaginationResult } from './ChorusPaginationResult'
import {
  ChorusPaginationResultFromJSON,
  ChorusPaginationResultFromJSONTyped,
  ChorusPaginationResultToJSON
} from './ChorusPaginationResult'

/**
 *
 * @export
 * @interface ChorusListPublicWorkspacesReply
 */
export interface ChorusListPublicWorkspacesReply {
  /**
   *
   * @type {ChorusListPublicWorkspacesResult}
   * @memberof ChorusListPublicWorkspacesReply
   */
  result?: ChorusListPublicWorkspacesResult
  /**
   *
   * @type {ChorusPaginationResult}
   * @memberof ChorusListPublicWorkspacesReply
   */
  pagination?: ChorusPaginationResult
}

/**
 * Check if a given object implements the ChorusListPublicWorkspacesReply interface.
 */
export function instanceOfChorusListPublicWorkspacesReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListPublicWorkspacesReplyFromJSON(
  json: any
): ChorusListPublicWorkspacesReply {
  return ChorusListPublicWorkspacesReplyFromJSONTyped(json, false)
}

export function ChorusListPublicWorkspacesReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListPublicWorkspacesReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusListPublicWorkspacesResultFromJSON(json['result']),
    pagination: !exists(json, 'pagination')
      ? undefined
      : ChorusPaginationResultFromJSON(json['pagination'])
  }
}

export function ChorusListPublicWorkspacesReplyToJSON(
  value?: ChorusListPublicWorkspacesReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusListPublicWorkspacesResultToJSON(value.result),
    pagination: ChorusPaginationResultToJSON(value.pagination)
  }
}
