/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusDownloadApprovalRequestFileResult } from './ChorusDownloadApprovalRequestFileResult'
import {
  ChorusDownloadApprovalRequestFileResultFromJSON,
  ChorusDownloadApprovalRequestFileResultFromJSONTyped,
  ChorusDownloadApprovalRequestFileResultToJSON
} from './ChorusDownloadApprovalRequestFileResult'

/**
 *
 * @export
 * @interface ChorusDownloadApprovalRequestFileReply
 */
export interface ChorusDownloadApprovalRequestFileReply {
  /**
   *
   * @type {ChorusDownloadApprovalRequestFileResult}
   * @memberof ChorusDownloadApprovalRequestFileReply
   */
  result?: ChorusDownloadApprovalRequestFileResult
}

/**
 * Check if a given object implements the ChorusDownloadApprovalRequestFileReply interface.
 */
export function instanceOfChorusDownloadApprovalRequestFileReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusDownloadApprovalRequestFileReplyFromJSON(
  json: any
): ChorusDownloadApprovalRequestFileReply {
  return ChorusDownloadApprovalRequestFileReplyFromJSONTyped(json, false)
}

export function ChorusDownloadApprovalRequestFileReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusDownloadApprovalRequestFileReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusDownloadApprovalRequestFileResultFromJSON(json['result'])
  }
}

export function ChorusDownloadApprovalRequestFileReplyToJSON(
  value?: ChorusDownloadApprovalRequestFileReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusDownloadApprovalRequestFileResultToJSON(value.result)
  }
}
