/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusRole
 */
export interface ChorusRole {
  /**
   *
   * @type {string}
   * @memberof ChorusRole
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof ChorusRole
   */
  name?: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ChorusRole
   */
  context?: { [key: string]: string }
}

/**
 * Check if a given object implements the ChorusRole interface.
 */
export function instanceOfChorusRole(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusRoleFromJSON(json: any): ChorusRole {
  return ChorusRoleFromJSONTyped(json, false)
}

export function ChorusRoleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusRole {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    name: !exists(json, 'name') ? undefined : json['name'],
    context: !exists(json, 'context') ? undefined : json['context']
  }
}

export function ChorusRoleToJSON(value?: ChorusRole | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    name: value.name,
    context: value.context
  }
}
