/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusUpdatePasswordReply
 */
export interface ChorusUpdatePasswordReply {
  /**
   *
   * @type {object}
   * @memberof ChorusUpdatePasswordReply
   */
  result?: object
}

/**
 * Check if a given object implements the ChorusUpdatePasswordReply interface.
 */
export function instanceOfChorusUpdatePasswordReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdatePasswordReplyFromJSON(
  json: any
): ChorusUpdatePasswordReply {
  return ChorusUpdatePasswordReplyFromJSONTyped(json, false)
}

export function ChorusUpdatePasswordReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdatePasswordReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result') ? undefined : json['result']
  }
}

export function ChorusUpdatePasswordReplyToJSON(
  value?: ChorusUpdatePasswordReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: value.result
  }
}
