/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusListAuditEntriesResult } from './ChorusListAuditEntriesResult'
import {
  ChorusListAuditEntriesResultFromJSON,
  ChorusListAuditEntriesResultFromJSONTyped,
  ChorusListAuditEntriesResultToJSON
} from './ChorusListAuditEntriesResult'
import type { ChorusPaginationResult } from './ChorusPaginationResult'
import {
  ChorusPaginationResultFromJSON,
  ChorusPaginationResultFromJSONTyped,
  ChorusPaginationResultToJSON
} from './ChorusPaginationResult'

/**
 *
 * @export
 * @interface ChorusListAuditEntriesReply
 */
export interface ChorusListAuditEntriesReply {
  /**
   *
   * @type {ChorusListAuditEntriesResult}
   * @memberof ChorusListAuditEntriesReply
   */
  result?: ChorusListAuditEntriesResult
  /**
   *
   * @type {ChorusPaginationResult}
   * @memberof ChorusListAuditEntriesReply
   */
  pagination?: ChorusPaginationResult
}

/**
 * Check if a given object implements the ChorusListAuditEntriesReply interface.
 */
export function instanceOfChorusListAuditEntriesReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListAuditEntriesReplyFromJSON(
  json: any
): ChorusListAuditEntriesReply {
  return ChorusListAuditEntriesReplyFromJSONTyped(json, false)
}

export function ChorusListAuditEntriesReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListAuditEntriesReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusListAuditEntriesResultFromJSON(json['result']),
    pagination: !exists(json, 'pagination')
      ? undefined
      : ChorusPaginationResultFromJSON(json['pagination'])
  }
}

export function ChorusListAuditEntriesReplyToJSON(
  value?: ChorusListAuditEntriesReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusListAuditEntriesResultToJSON(value.result),
    pagination: ChorusPaginationResultToJSON(value.pagination)
  }
}
