/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusRefreshTokenResult } from './ChorusRefreshTokenResult'
import {
  ChorusRefreshTokenResultFromJSON,
  ChorusRefreshTokenResultFromJSONTyped,
  ChorusRefreshTokenResultToJSON
} from './ChorusRefreshTokenResult'

/**
 *
 * @export
 * @interface ChorusRefreshTokenReply
 */
export interface ChorusRefreshTokenReply {
  /**
   *
   * @type {ChorusRefreshTokenResult}
   * @memberof ChorusRefreshTokenReply
   */
  result?: ChorusRefreshTokenResult
}

/**
 * Check if a given object implements the ChorusRefreshTokenReply interface.
 */
export function instanceOfChorusRefreshTokenReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusRefreshTokenReplyFromJSON(
  json: any
): ChorusRefreshTokenReply {
  return ChorusRefreshTokenReplyFromJSONTyped(json, false)
}

export function ChorusRefreshTokenReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusRefreshTokenReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusRefreshTokenResultFromJSON(json['result'])
  }
}

export function ChorusRefreshTokenReplyToJSON(
  value?: ChorusRefreshTokenReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusRefreshTokenResultToJSON(value.result)
  }
}
