/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusSystemNotification
 */
export interface ChorusSystemNotification {
  /**
   *
   * @type {boolean}
   * @memberof ChorusSystemNotification
   */
  refreshJWTRequired?: boolean
}

/**
 * Check if a given object implements the ChorusSystemNotification interface.
 */
export function instanceOfChorusSystemNotification(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusSystemNotificationFromJSON(
  json: any
): ChorusSystemNotification {
  return ChorusSystemNotificationFromJSONTyped(json, false)
}

export function ChorusSystemNotificationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusSystemNotification {
  if (json === undefined || json === null) {
    return json
  }
  return {
    refreshJWTRequired: !exists(json, 'refreshJWTRequired')
      ? undefined
      : json['refreshJWTRequired']
  }
}

export function ChorusSystemNotificationToJSON(
  value?: ChorusSystemNotification | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    refreshJWTRequired: value.refreshJWTRequired
  }
}
