/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * OrganizationLogo bundles the logo bytes with their content type so the two
 * always travel together. It is only ever populated in the request sent to
 * CreateOrganization/UpdateOrganization when adding or replacing a logo.
 * Fetch the logo bytes separately via GetOrganizationLogo.
 * @export
 * @interface ChorusOrganizationLogo
 */
export interface ChorusOrganizationLogo {
  /**
   *
   * @type {string}
   * @memberof ChorusOrganizationLogo
   */
  data?: string
  /**
   *
   * @type {string}
   * @memberof ChorusOrganizationLogo
   */
  contentType?: string
}

/**
 * Check if a given object implements the ChorusOrganizationLogo interface.
 */
export function instanceOfChorusOrganizationLogo(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusOrganizationLogoFromJSON(
  json: any
): ChorusOrganizationLogo {
  return ChorusOrganizationLogoFromJSONTyped(json, false)
}

export function ChorusOrganizationLogoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusOrganizationLogo {
  if (json === undefined || json === null) {
    return json
  }
  return {
    data: !exists(json, 'data') ? undefined : json['data'],
    contentType: !exists(json, 'contentType') ? undefined : json['contentType']
  }
}

export function ChorusOrganizationLogoToJSON(
  value?: ChorusOrganizationLogo | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    data: value.data,
    contentType: value.contentType
  }
}
