/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusInitiateWorkspaceFileUploadResult
 */
export interface ChorusInitiateWorkspaceFileUploadResult {
  /**
   *
   * @type {string}
   * @memberof ChorusInitiateWorkspaceFileUploadResult
   */
  uploadId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusInitiateWorkspaceFileUploadResult
   */
  partSize?: string
  /**
   *
   * @type {string}
   * @memberof ChorusInitiateWorkspaceFileUploadResult
   */
  totalParts?: string
}

/**
 * Check if a given object implements the ChorusInitiateWorkspaceFileUploadResult interface.
 */
export function instanceOfChorusInitiateWorkspaceFileUploadResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusInitiateWorkspaceFileUploadResultFromJSON(
  json: any
): ChorusInitiateWorkspaceFileUploadResult {
  return ChorusInitiateWorkspaceFileUploadResultFromJSONTyped(json, false)
}

export function ChorusInitiateWorkspaceFileUploadResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusInitiateWorkspaceFileUploadResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    uploadId: !exists(json, 'uploadId') ? undefined : json['uploadId'],
    partSize: !exists(json, 'partSize') ? undefined : json['partSize'],
    totalParts: !exists(json, 'totalParts') ? undefined : json['totalParts']
  }
}

export function ChorusInitiateWorkspaceFileUploadResultToJSON(
  value?: ChorusInitiateWorkspaceFileUploadResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    uploadId: value.uploadId,
    partSize: value.partSize,
    totalParts: value.totalParts
  }
}
