/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusPutEntryResult
 */
export interface ChorusPutEntryResult {
  /**
   *
   * @type {string}
   * @memberof ChorusPutEntryResult
   */
  key?: string
  /**
   *
   * @type {string}
   * @memberof ChorusPutEntryResult
   */
  value?: string
}

/**
 * Check if a given object implements the ChorusPutEntryResult interface.
 */
export function instanceOfChorusPutEntryResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusPutEntryResultFromJSON(json: any): ChorusPutEntryResult {
  return ChorusPutEntryResultFromJSONTyped(json, false)
}

export function ChorusPutEntryResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusPutEntryResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    key: !exists(json, 'key') ? undefined : json['key'],
    value: !exists(json, 'value') ? undefined : json['value']
  }
}

export function ChorusPutEntryResultToJSON(
  value?: ChorusPutEntryResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    key: value.key,
    value: value.value
  }
}
