/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusApprovalRequestFile } from './ChorusApprovalRequestFile'
import {
  ChorusApprovalRequestFileFromJSON,
  ChorusApprovalRequestFileFromJSONTyped,
  ChorusApprovalRequestFileToJSON
} from './ChorusApprovalRequestFile'

/**
 *
 * @export
 * @interface ChorusDataTransferDetails
 */
export interface ChorusDataTransferDetails {
  /**
   *
   * @type {string}
   * @memberof ChorusDataTransferDetails
   */
  sourceWorkspaceId?: string
  /**
   *
   * @type {string}
   * @memberof ChorusDataTransferDetails
   */
  destinationWorkspaceId?: string
  /**
   *
   * @type {Array<ChorusApprovalRequestFile>}
   * @memberof ChorusDataTransferDetails
   */
  files?: Array<ChorusApprovalRequestFile>
}

/**
 * Check if a given object implements the ChorusDataTransferDetails interface.
 */
export function instanceOfChorusDataTransferDetails(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusDataTransferDetailsFromJSON(
  json: any
): ChorusDataTransferDetails {
  return ChorusDataTransferDetailsFromJSONTyped(json, false)
}

export function ChorusDataTransferDetailsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusDataTransferDetails {
  if (json === undefined || json === null) {
    return json
  }
  return {
    sourceWorkspaceId: !exists(json, 'sourceWorkspaceId')
      ? undefined
      : json['sourceWorkspaceId'],
    destinationWorkspaceId: !exists(json, 'destinationWorkspaceId')
      ? undefined
      : json['destinationWorkspaceId'],
    files: !exists(json, 'files')
      ? undefined
      : (json['files'] as Array<any>).map(ChorusApprovalRequestFileFromJSON)
  }
}

export function ChorusDataTransferDetailsToJSON(
  value?: ChorusDataTransferDetails | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    sourceWorkspaceId: value.sourceWorkspaceId,
    destinationWorkspaceId: value.destinationWorkspaceId,
    files:
      value.files === undefined
        ? undefined
        : (value.files as Array<any>).map(ChorusApprovalRequestFileToJSON)
  }
}
