/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusListOrganizationsResult } from './ChorusListOrganizationsResult'
import {
  ChorusListOrganizationsResultFromJSON,
  ChorusListOrganizationsResultFromJSONTyped,
  ChorusListOrganizationsResultToJSON
} from './ChorusListOrganizationsResult'
import type { ChorusPaginationResult } from './ChorusPaginationResult'
import {
  ChorusPaginationResultFromJSON,
  ChorusPaginationResultFromJSONTyped,
  ChorusPaginationResultToJSON
} from './ChorusPaginationResult'

/**
 *
 * @export
 * @interface ChorusListOrganizationsReply
 */
export interface ChorusListOrganizationsReply {
  /**
   *
   * @type {ChorusListOrganizationsResult}
   * @memberof ChorusListOrganizationsReply
   */
  result?: ChorusListOrganizationsResult
  /**
   *
   * @type {ChorusPaginationResult}
   * @memberof ChorusListOrganizationsReply
   */
  pagination?: ChorusPaginationResult
}

/**
 * Check if a given object implements the ChorusListOrganizationsReply interface.
 */
export function instanceOfChorusListOrganizationsReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListOrganizationsReplyFromJSON(
  json: any
): ChorusListOrganizationsReply {
  return ChorusListOrganizationsReplyFromJSONTyped(json, false)
}

export function ChorusListOrganizationsReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListOrganizationsReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusListOrganizationsResultFromJSON(json['result']),
    pagination: !exists(json, 'pagination')
      ? undefined
      : ChorusPaginationResultFromJSON(json['pagination'])
  }
}

export function ChorusListOrganizationsReplyToJSON(
  value?: ChorusListOrganizationsReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusListOrganizationsResultToJSON(value.result),
    pagination: ChorusPaginationResultToJSON(value.pagination)
  }
}
