/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusTermsOfUseVersion } from './ChorusTermsOfUseVersion'
import {
  ChorusTermsOfUseVersionFromJSON,
  ChorusTermsOfUseVersionFromJSONTyped,
  ChorusTermsOfUseVersionToJSON
} from './ChorusTermsOfUseVersion'

/**
 *
 * @export
 * @interface ChorusListTermsOfUseVersionsResult
 */
export interface ChorusListTermsOfUseVersionsResult {
  /**
   *
   * @type {Array<ChorusTermsOfUseVersion>}
   * @memberof ChorusListTermsOfUseVersionsResult
   */
  termsOfUseVersions?: Array<ChorusTermsOfUseVersion>
}

/**
 * Check if a given object implements the ChorusListTermsOfUseVersionsResult interface.
 */
export function instanceOfChorusListTermsOfUseVersionsResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListTermsOfUseVersionsResultFromJSON(
  json: any
): ChorusListTermsOfUseVersionsResult {
  return ChorusListTermsOfUseVersionsResultFromJSONTyped(json, false)
}

export function ChorusListTermsOfUseVersionsResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListTermsOfUseVersionsResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    termsOfUseVersions: !exists(json, 'termsOfUseVersions')
      ? undefined
      : (json['termsOfUseVersions'] as Array<any>).map(
          ChorusTermsOfUseVersionFromJSON
        )
  }
}

export function ChorusListTermsOfUseVersionsResultToJSON(
  value?: ChorusListTermsOfUseVersionsResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    termsOfUseVersions:
      value.termsOfUseVersions === undefined
        ? undefined
        : (value.termsOfUseVersions as Array<any>).map(
            ChorusTermsOfUseVersionToJSON
          )
  }
}
