/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusUpdateOrganizationResult } from './ChorusUpdateOrganizationResult'
import {
  ChorusUpdateOrganizationResultFromJSON,
  ChorusUpdateOrganizationResultFromJSONTyped,
  ChorusUpdateOrganizationResultToJSON
} from './ChorusUpdateOrganizationResult'

/**
 *
 * @export
 * @interface ChorusUpdateOrganizationReply
 */
export interface ChorusUpdateOrganizationReply {
  /**
   *
   * @type {ChorusUpdateOrganizationResult}
   * @memberof ChorusUpdateOrganizationReply
   */
  result?: ChorusUpdateOrganizationResult
}

/**
 * Check if a given object implements the ChorusUpdateOrganizationReply interface.
 */
export function instanceOfChorusUpdateOrganizationReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdateOrganizationReplyFromJSON(
  json: any
): ChorusUpdateOrganizationReply {
  return ChorusUpdateOrganizationReplyFromJSONTyped(json, false)
}

export function ChorusUpdateOrganizationReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdateOrganizationReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusUpdateOrganizationResultFromJSON(json['result'])
  }
}

export function ChorusUpdateOrganizationReplyToJSON(
  value?: ChorusUpdateOrganizationReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusUpdateOrganizationResultToJSON(value.result)
  }
}
