/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusListAppsResult } from './ChorusListAppsResult'
import {
  ChorusListAppsResultFromJSON,
  ChorusListAppsResultFromJSONTyped,
  ChorusListAppsResultToJSON
} from './ChorusListAppsResult'
import type { ChorusPaginationResult } from './ChorusPaginationResult'
import {
  ChorusPaginationResultFromJSON,
  ChorusPaginationResultFromJSONTyped,
  ChorusPaginationResultToJSON
} from './ChorusPaginationResult'

/**
 *
 * @export
 * @interface ChorusListAppsReply
 */
export interface ChorusListAppsReply {
  /**
   *
   * @type {ChorusListAppsResult}
   * @memberof ChorusListAppsReply
   */
  result?: ChorusListAppsResult
  /**
   *
   * @type {ChorusPaginationResult}
   * @memberof ChorusListAppsReply
   */
  pagination?: ChorusPaginationResult
}

/**
 * Check if a given object implements the ChorusListAppsReply interface.
 */
export function instanceOfChorusListAppsReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListAppsReplyFromJSON(json: any): ChorusListAppsReply {
  return ChorusListAppsReplyFromJSONTyped(json, false)
}

export function ChorusListAppsReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListAppsReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusListAppsResultFromJSON(json['result']),
    pagination: !exists(json, 'pagination')
      ? undefined
      : ChorusPaginationResultFromJSON(json['pagination'])
  }
}

export function ChorusListAppsReplyToJSON(
  value?: ChorusListAppsReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusListAppsResultToJSON(value.result),
    pagination: ChorusPaginationResultToJSON(value.pagination)
  }
}
