/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * ApprovalStepDecision is one approver's decision on one step.
 * @export
 * @interface ChorusApprovalStepDecision
 */
export interface ChorusApprovalStepDecision {
  /**
   *
   * @type {string}
   * @memberof ChorusApprovalStepDecision
   */
  approverId?: string
  /**
   *
   * @type {Date}
   * @memberof ChorusApprovalStepDecision
   */
  approvedAt?: Date
  /**
   * true: approved, false: rejected.
   * @type {boolean}
   * @memberof ChorusApprovalStepDecision
   */
  approve?: boolean
}

/**
 * Check if a given object implements the ChorusApprovalStepDecision interface.
 */
export function instanceOfChorusApprovalStepDecision(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusApprovalStepDecisionFromJSON(
  json: any
): ChorusApprovalStepDecision {
  return ChorusApprovalStepDecisionFromJSONTyped(json, false)
}

export function ChorusApprovalStepDecisionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusApprovalStepDecision {
  if (json === undefined || json === null) {
    return json
  }
  return {
    approverId: !exists(json, 'approverId') ? undefined : json['approverId'],
    approvedAt: !exists(json, 'approvedAt')
      ? undefined
      : new Date(json['approvedAt']),
    approve: !exists(json, 'approve') ? undefined : json['approve']
  }
}

export function ChorusApprovalStepDecisionToJSON(
  value?: ChorusApprovalStepDecision | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    approverId: value.approverId,
    approvedAt:
      value.approvedAt === undefined
        ? undefined
        : value.approvedAt.toISOString(),
    approve: value.approve
  }
}
