/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusTermsOfUseVersion } from './ChorusTermsOfUseVersion'
import {
  ChorusTermsOfUseVersionFromJSON,
  ChorusTermsOfUseVersionFromJSONTyped,
  ChorusTermsOfUseVersionToJSON
} from './ChorusTermsOfUseVersion'

/**
 *
 * @export
 * @interface ChorusPublishTermsOfUseVersionResult
 */
export interface ChorusPublishTermsOfUseVersionResult {
  /**
   *
   * @type {ChorusTermsOfUseVersion}
   * @memberof ChorusPublishTermsOfUseVersionResult
   */
  termsOfUseVersion?: ChorusTermsOfUseVersion
}

/**
 * Check if a given object implements the ChorusPublishTermsOfUseVersionResult interface.
 */
export function instanceOfChorusPublishTermsOfUseVersionResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusPublishTermsOfUseVersionResultFromJSON(
  json: any
): ChorusPublishTermsOfUseVersionResult {
  return ChorusPublishTermsOfUseVersionResultFromJSONTyped(json, false)
}

export function ChorusPublishTermsOfUseVersionResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusPublishTermsOfUseVersionResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    termsOfUseVersion: !exists(json, 'termsOfUseVersion')
      ? undefined
      : ChorusTermsOfUseVersionFromJSON(json['termsOfUseVersion'])
  }
}

export function ChorusPublishTermsOfUseVersionResultToJSON(
  value?: ChorusPublishTermsOfUseVersionResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    termsOfUseVersion: ChorusTermsOfUseVersionToJSON(value.termsOfUseVersion)
  }
}
