/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusAbortWorkspaceFileUploadReply
 */
export interface ChorusAbortWorkspaceFileUploadReply {
  /**
   *
   * @type {object}
   * @memberof ChorusAbortWorkspaceFileUploadReply
   */
  result?: object
}

/**
 * Check if a given object implements the ChorusAbortWorkspaceFileUploadReply interface.
 */
export function instanceOfChorusAbortWorkspaceFileUploadReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusAbortWorkspaceFileUploadReplyFromJSON(
  json: any
): ChorusAbortWorkspaceFileUploadReply {
  return ChorusAbortWorkspaceFileUploadReplyFromJSONTyped(json, false)
}

export function ChorusAbortWorkspaceFileUploadReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusAbortWorkspaceFileUploadReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result') ? undefined : json['result']
  }
}

export function ChorusAbortWorkspaceFileUploadReplyToJSON(
  value?: ChorusAbortWorkspaceFileUploadReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: value.result
  }
}
