/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusUpdateAppResult } from './ChorusUpdateAppResult'
import {
  ChorusUpdateAppResultFromJSON,
  ChorusUpdateAppResultFromJSONTyped,
  ChorusUpdateAppResultToJSON
} from './ChorusUpdateAppResult'

/**
 *
 * @export
 * @interface ChorusUpdateAppReply
 */
export interface ChorusUpdateAppReply {
  /**
   *
   * @type {ChorusUpdateAppResult}
   * @memberof ChorusUpdateAppReply
   */
  result?: ChorusUpdateAppResult
}

/**
 * Check if a given object implements the ChorusUpdateAppReply interface.
 */
export function instanceOfChorusUpdateAppReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdateAppReplyFromJSON(json: any): ChorusUpdateAppReply {
  return ChorusUpdateAppReplyFromJSONTyped(json, false)
}

export function ChorusUpdateAppReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdateAppReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusUpdateAppResultFromJSON(json['result'])
  }
}

export function ChorusUpdateAppReplyToJSON(
  value?: ChorusUpdateAppReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusUpdateAppResultToJSON(value.result)
  }
}
