/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusApprovalRequest } from './ChorusApprovalRequest'
import {
  ChorusApprovalRequestFromJSON,
  ChorusApprovalRequestFromJSONTyped,
  ChorusApprovalRequestToJSON
} from './ChorusApprovalRequest'

/**
 *
 * @export
 * @interface ChorusListApprovalRequestsResult
 */
export interface ChorusListApprovalRequestsResult {
  /**
   *
   * @type {Array<ChorusApprovalRequest>}
   * @memberof ChorusListApprovalRequestsResult
   */
  approvalRequests?: Array<ChorusApprovalRequest>
}

/**
 * Check if a given object implements the ChorusListApprovalRequestsResult interface.
 */
export function instanceOfChorusListApprovalRequestsResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListApprovalRequestsResultFromJSON(
  json: any
): ChorusListApprovalRequestsResult {
  return ChorusListApprovalRequestsResultFromJSONTyped(json, false)
}

export function ChorusListApprovalRequestsResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListApprovalRequestsResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    approvalRequests: !exists(json, 'approvalRequests')
      ? undefined
      : (json['approvalRequests'] as Array<any>).map(
          ChorusApprovalRequestFromJSON
        )
  }
}

export function ChorusListApprovalRequestsResultToJSON(
  value?: ChorusListApprovalRequestsResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    approvalRequests:
      value.approvalRequests === undefined
        ? undefined
        : (value.approvalRequests as Array<any>).map(
            ChorusApprovalRequestToJSON
          )
  }
}
