/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusCreateDataTransferRequestResult } from './ChorusCreateDataTransferRequestResult'
import {
  ChorusCreateDataTransferRequestResultFromJSON,
  ChorusCreateDataTransferRequestResultFromJSONTyped,
  ChorusCreateDataTransferRequestResultToJSON
} from './ChorusCreateDataTransferRequestResult'

/**
 *
 * @export
 * @interface ChorusCreateDataTransferRequestReply
 */
export interface ChorusCreateDataTransferRequestReply {
  /**
   *
   * @type {ChorusCreateDataTransferRequestResult}
   * @memberof ChorusCreateDataTransferRequestReply
   */
  result?: ChorusCreateDataTransferRequestResult
}

/**
 * Check if a given object implements the ChorusCreateDataTransferRequestReply interface.
 */
export function instanceOfChorusCreateDataTransferRequestReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateDataTransferRequestReplyFromJSON(
  json: any
): ChorusCreateDataTransferRequestReply {
  return ChorusCreateDataTransferRequestReplyFromJSONTyped(json, false)
}

export function ChorusCreateDataTransferRequestReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateDataTransferRequestReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusCreateDataTransferRequestResultFromJSON(json['result'])
  }
}

export function ChorusCreateDataTransferRequestReplyToJSON(
  value?: ChorusCreateDataTransferRequestReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusCreateDataTransferRequestResultToJSON(value.result)
  }
}
