/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusEnableTotpReply
 */
export interface ChorusEnableTotpReply {
  /**
   *
   * @type {object}
   * @memberof ChorusEnableTotpReply
   */
  result?: object
}

/**
 * Check if a given object implements the ChorusEnableTotpReply interface.
 */
export function instanceOfChorusEnableTotpReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusEnableTotpReplyFromJSON(
  json: any
): ChorusEnableTotpReply {
  return ChorusEnableTotpReplyFromJSONTyped(json, false)
}

export function ChorusEnableTotpReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusEnableTotpReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result') ? undefined : json['result']
  }
}

export function ChorusEnableTotpReplyToJSON(
  value?: ChorusEnableTotpReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: value.result
  }
}
