/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusManageUserRoleInWorkspaceResult } from './ChorusManageUserRoleInWorkspaceResult'
import {
  ChorusManageUserRoleInWorkspaceResultFromJSON,
  ChorusManageUserRoleInWorkspaceResultFromJSONTyped,
  ChorusManageUserRoleInWorkspaceResultToJSON
} from './ChorusManageUserRoleInWorkspaceResult'

/**
 *
 * @export
 * @interface ChorusManageUserRoleInWorkspaceReply
 */
export interface ChorusManageUserRoleInWorkspaceReply {
  /**
   *
   * @type {ChorusManageUserRoleInWorkspaceResult}
   * @memberof ChorusManageUserRoleInWorkspaceReply
   */
  result?: ChorusManageUserRoleInWorkspaceResult
}

/**
 * Check if a given object implements the ChorusManageUserRoleInWorkspaceReply interface.
 */
export function instanceOfChorusManageUserRoleInWorkspaceReply(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusManageUserRoleInWorkspaceReplyFromJSON(
  json: any
): ChorusManageUserRoleInWorkspaceReply {
  return ChorusManageUserRoleInWorkspaceReplyFromJSONTyped(json, false)
}

export function ChorusManageUserRoleInWorkspaceReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusManageUserRoleInWorkspaceReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusManageUserRoleInWorkspaceResultFromJSON(json['result'])
  }
}

export function ChorusManageUserRoleInWorkspaceReplyToJSON(
  value?: ChorusManageUserRoleInWorkspaceReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusManageUserRoleInWorkspaceResultToJSON(value.result)
  }
}
