/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusResetTotpResult } from './ChorusResetTotpResult'
import {
  ChorusResetTotpResultFromJSON,
  ChorusResetTotpResultFromJSONTyped,
  ChorusResetTotpResultToJSON
} from './ChorusResetTotpResult'

/**
 *
 * @export
 * @interface ChorusResetTotpReply
 */
export interface ChorusResetTotpReply {
  /**
   *
   * @type {ChorusResetTotpResult}
   * @memberof ChorusResetTotpReply
   */
  result?: ChorusResetTotpResult
}

/**
 * Check if a given object implements the ChorusResetTotpReply interface.
 */
export function instanceOfChorusResetTotpReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusResetTotpReplyFromJSON(json: any): ChorusResetTotpReply {
  return ChorusResetTotpReplyFromJSONTyped(json, false)
}

export function ChorusResetTotpReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusResetTotpReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusResetTotpResultFromJSON(json['result'])
  }
}

export function ChorusResetTotpReplyToJSON(
  value?: ChorusResetTotpReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusResetTotpResultToJSON(value.result)
  }
}
