/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusMarkNotificationsAsReadRequest
 */
export interface ChorusMarkNotificationsAsReadRequest {
  /**
   *
   * @type {Array<string>}
   * @memberof ChorusMarkNotificationsAsReadRequest
   */
  notificationIds?: Array<string>
  /**
   *
   * @type {boolean}
   * @memberof ChorusMarkNotificationsAsReadRequest
   */
  markAll?: boolean
}

/**
 * Check if a given object implements the ChorusMarkNotificationsAsReadRequest interface.
 */
export function instanceOfChorusMarkNotificationsAsReadRequest(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusMarkNotificationsAsReadRequestFromJSON(
  json: any
): ChorusMarkNotificationsAsReadRequest {
  return ChorusMarkNotificationsAsReadRequestFromJSONTyped(json, false)
}

export function ChorusMarkNotificationsAsReadRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusMarkNotificationsAsReadRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    notificationIds: !exists(json, 'notificationIds')
      ? undefined
      : json['notificationIds'],
    markAll: !exists(json, 'markAll') ? undefined : json['markAll']
  }
}

export function ChorusMarkNotificationsAsReadRequestToJSON(
  value?: ChorusMarkNotificationsAsReadRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    notificationIds: value.notificationIds,
    markAll: value.markAll
  }
}
