/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ChorusResetPasswordReply
 */
export interface ChorusResetPasswordReply {
  /**
   *
   * @type {object}
   * @memberof ChorusResetPasswordReply
   */
  result?: object
}

/**
 * Check if a given object implements the ChorusResetPasswordReply interface.
 */
export function instanceOfChorusResetPasswordReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusResetPasswordReplyFromJSON(
  json: any
): ChorusResetPasswordReply {
  return ChorusResetPasswordReplyFromJSONTyped(json, false)
}

export function ChorusResetPasswordReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusResetPasswordReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result') ? undefined : json['result']
  }
}

export function ChorusResetPasswordReplyToJSON(
  value?: ChorusResetPasswordReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: value.result
  }
}
