/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusApprovalRequest } from './ChorusApprovalRequest'
import {
  ChorusApprovalRequestFromJSON,
  ChorusApprovalRequestFromJSONTyped,
  ChorusApprovalRequestToJSON
} from './ChorusApprovalRequest'

/**
 *
 * @export
 * @interface ChorusCreateDataExtractionRequestResult
 */
export interface ChorusCreateDataExtractionRequestResult {
  /**
   *
   * @type {ChorusApprovalRequest}
   * @memberof ChorusCreateDataExtractionRequestResult
   */
  approvalRequest?: ChorusApprovalRequest
}

/**
 * Check if a given object implements the ChorusCreateDataExtractionRequestResult interface.
 */
export function instanceOfChorusCreateDataExtractionRequestResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateDataExtractionRequestResultFromJSON(
  json: any
): ChorusCreateDataExtractionRequestResult {
  return ChorusCreateDataExtractionRequestResultFromJSONTyped(json, false)
}

export function ChorusCreateDataExtractionRequestResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateDataExtractionRequestResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    approvalRequest: !exists(json, 'approvalRequest')
      ? undefined
      : ChorusApprovalRequestFromJSON(json['approvalRequest'])
  }
}

export function ChorusCreateDataExtractionRequestResultToJSON(
  value?: ChorusCreateDataExtractionRequestResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    approvalRequest: ChorusApprovalRequestToJSON(value.approvalRequest)
  }
}
