/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspace } from './ChorusWorkspace'
import {
  ChorusWorkspaceFromJSON,
  ChorusWorkspaceFromJSONTyped,
  ChorusWorkspaceToJSON
} from './ChorusWorkspace'

/**
 *
 * @export
 * @interface ChorusListWorkspacesReply
 */
export interface ChorusListWorkspacesReply {
  /**
   *
   * @type {Array<ChorusWorkspace>}
   * @memberof ChorusListWorkspacesReply
   */
  result?: Array<ChorusWorkspace>
}

/**
 * Check if a given object implements the ChorusListWorkspacesReply interface.
 */
export function instanceOfChorusListWorkspacesReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListWorkspacesReplyFromJSON(
  json: any
): ChorusListWorkspacesReply {
  return ChorusListWorkspacesReplyFromJSONTyped(json, false)
}

export function ChorusListWorkspacesReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListWorkspacesReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : (json['result'] as Array<any>).map(ChorusWorkspaceFromJSON)
  }
}

export function ChorusListWorkspacesReplyToJSON(
  value?: ChorusListWorkspacesReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result:
      value.result === undefined
        ? undefined
        : (value.result as Array<any>).map(ChorusWorkspaceToJSON)
  }
}
