/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusCreateWorkspaceResult } from './ChorusCreateWorkspaceResult'
import {
  ChorusCreateWorkspaceResultFromJSON,
  ChorusCreateWorkspaceResultFromJSONTyped,
  ChorusCreateWorkspaceResultToJSON
} from './ChorusCreateWorkspaceResult'

/**
 *
 * @export
 * @interface ChorusCreateWorkspaceReply
 */
export interface ChorusCreateWorkspaceReply {
  /**
   *
   * @type {ChorusCreateWorkspaceResult}
   * @memberof ChorusCreateWorkspaceReply
   */
  result?: ChorusCreateWorkspaceResult
}

/**
 * Check if a given object implements the ChorusCreateWorkspaceReply interface.
 */
export function instanceOfChorusCreateWorkspaceReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateWorkspaceReplyFromJSON(
  json: any
): ChorusCreateWorkspaceReply {
  return ChorusCreateWorkspaceReplyFromJSONTyped(json, false)
}

export function ChorusCreateWorkspaceReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateWorkspaceReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusCreateWorkspaceResultFromJSON(json['result'])
  }
}

export function ChorusCreateWorkspaceReplyToJSON(
  value?: ChorusCreateWorkspaceReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusCreateWorkspaceResultToJSON(value.result)
  }
}
