/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspace } from './ChorusWorkspace'
import {
  ChorusWorkspaceFromJSON,
  ChorusWorkspaceFromJSONTyped,
  ChorusWorkspaceToJSON
} from './ChorusWorkspace'

/**
 *
 * @export
 * @interface ChorusListWorkspacesResult
 */
export interface ChorusListWorkspacesResult {
  /**
   *
   * @type {Array<ChorusWorkspace>}
   * @memberof ChorusListWorkspacesResult
   */
  workspaces?: Array<ChorusWorkspace>
}

/**
 * Check if a given object implements the ChorusListWorkspacesResult interface.
 */
export function instanceOfChorusListWorkspacesResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListWorkspacesResultFromJSON(
  json: any
): ChorusListWorkspacesResult {
  return ChorusListWorkspacesResultFromJSONTyped(json, false)
}

export function ChorusListWorkspacesResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListWorkspacesResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    workspaces: !exists(json, 'workspaces')
      ? undefined
      : (json['workspaces'] as Array<any>).map(ChorusWorkspaceFromJSON)
  }
}

export function ChorusListWorkspacesResultToJSON(
  value?: ChorusListWorkspacesResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    workspaces:
      value.workspaces === undefined
        ? undefined
        : (value.workspaces as Array<any>).map(ChorusWorkspaceToJSON)
  }
}
