/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusDeleteAppInstanceResult } from './ChorusDeleteAppInstanceResult'
import {
  ChorusDeleteAppInstanceResultFromJSON,
  ChorusDeleteAppInstanceResultFromJSONTyped,
  ChorusDeleteAppInstanceResultToJSON
} from './ChorusDeleteAppInstanceResult'

/**
 *
 * @export
 * @interface ChorusDeleteAppInstanceReply
 */
export interface ChorusDeleteAppInstanceReply {
  /**
   *
   * @type {ChorusDeleteAppInstanceResult}
   * @memberof ChorusDeleteAppInstanceReply
   */
  result?: ChorusDeleteAppInstanceResult
}

/**
 * Check if a given object implements the ChorusDeleteAppInstanceReply interface.
 */
export function instanceOfChorusDeleteAppInstanceReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusDeleteAppInstanceReplyFromJSON(
  json: any
): ChorusDeleteAppInstanceReply {
  return ChorusDeleteAppInstanceReplyFromJSONTyped(json, false)
}

export function ChorusDeleteAppInstanceReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusDeleteAppInstanceReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusDeleteAppInstanceResultFromJSON(json['result'])
  }
}

export function ChorusDeleteAppInstanceReplyToJSON(
  value?: ChorusDeleteAppInstanceReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusDeleteAppInstanceResultToJSON(value.result)
  }
}
