/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusOrganization } from './ChorusOrganization'
import {
  ChorusOrganizationFromJSON,
  ChorusOrganizationFromJSONTyped,
  ChorusOrganizationToJSON
} from './ChorusOrganization'

/**
 *
 * @export
 * @interface ChorusUpdateOrganizationResult
 */
export interface ChorusUpdateOrganizationResult {
  /**
   *
   * @type {ChorusOrganization}
   * @memberof ChorusUpdateOrganizationResult
   */
  organization?: ChorusOrganization
}

/**
 * Check if a given object implements the ChorusUpdateOrganizationResult interface.
 */
export function instanceOfChorusUpdateOrganizationResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusUpdateOrganizationResultFromJSON(
  json: any
): ChorusUpdateOrganizationResult {
  return ChorusUpdateOrganizationResultFromJSONTyped(json, false)
}

export function ChorusUpdateOrganizationResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusUpdateOrganizationResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    organization: !exists(json, 'organization')
      ? undefined
      : ChorusOrganizationFromJSON(json['organization'])
  }
}

export function ChorusUpdateOrganizationResultToJSON(
  value?: ChorusUpdateOrganizationResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    organization: ChorusOrganizationToJSON(value.organization)
  }
}
