/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusAuthorizationRole } from './ChorusAuthorizationRole'
import {
  ChorusAuthorizationRoleFromJSON,
  ChorusAuthorizationRoleFromJSONTyped,
  ChorusAuthorizationRoleToJSON
} from './ChorusAuthorizationRole'

/**
 *
 * @export
 * @interface ChorusListRolesResult
 */
export interface ChorusListRolesResult {
  /**
   *
   * @type {Array<ChorusAuthorizationRole>}
   * @memberof ChorusListRolesResult
   */
  roles?: Array<ChorusAuthorizationRole>
}

/**
 * Check if a given object implements the ChorusListRolesResult interface.
 */
export function instanceOfChorusListRolesResult(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusListRolesResultFromJSON(
  json: any
): ChorusListRolesResult {
  return ChorusListRolesResultFromJSONTyped(json, false)
}

export function ChorusListRolesResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusListRolesResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    roles: !exists(json, 'roles')
      ? undefined
      : (json['roles'] as Array<any>).map(ChorusAuthorizationRoleFromJSON)
  }
}

export function ChorusListRolesResultToJSON(
  value?: ChorusListRolesResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    roles:
      value.roles === undefined
        ? undefined
        : (value.roles as Array<any>).map(ChorusAuthorizationRoleToJSON)
  }
}
