/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusAppInstance } from './ChorusAppInstance'
import {
  ChorusAppInstanceFromJSON,
  ChorusAppInstanceFromJSONTyped,
  ChorusAppInstanceToJSON
} from './ChorusAppInstance'

/**
 *
 * @export
 * @interface ChorusCreateAppInstanceResult
 */
export interface ChorusCreateAppInstanceResult {
  /**
   *
   * @type {ChorusAppInstance}
   * @memberof ChorusCreateAppInstanceResult
   */
  appInstance?: ChorusAppInstance
}

/**
 * Check if a given object implements the ChorusCreateAppInstanceResult interface.
 */
export function instanceOfChorusCreateAppInstanceResult(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusCreateAppInstanceResultFromJSON(
  json: any
): ChorusCreateAppInstanceResult {
  return ChorusCreateAppInstanceResultFromJSONTyped(json, false)
}

export function ChorusCreateAppInstanceResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusCreateAppInstanceResult {
  if (json === undefined || json === null) {
    return json
  }
  return {
    appInstance: !exists(json, 'appInstance')
      ? undefined
      : ChorusAppInstanceFromJSON(json['appInstance'])
  }
}

export function ChorusCreateAppInstanceResultToJSON(
  value?: ChorusCreateAppInstanceResult | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    appInstance: ChorusAppInstanceToJSON(value.appInstance)
  }
}
