/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusAcceptTermsOfUseResult } from './ChorusAcceptTermsOfUseResult'
import {
  ChorusAcceptTermsOfUseResultFromJSON,
  ChorusAcceptTermsOfUseResultFromJSONTyped,
  ChorusAcceptTermsOfUseResultToJSON
} from './ChorusAcceptTermsOfUseResult'

/**
 *
 * @export
 * @interface ChorusAcceptTermsOfUseReply
 */
export interface ChorusAcceptTermsOfUseReply {
  /**
   *
   * @type {ChorusAcceptTermsOfUseResult}
   * @memberof ChorusAcceptTermsOfUseReply
   */
  result?: ChorusAcceptTermsOfUseResult
}

/**
 * Check if a given object implements the ChorusAcceptTermsOfUseReply interface.
 */
export function instanceOfChorusAcceptTermsOfUseReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ChorusAcceptTermsOfUseReplyFromJSON(
  json: any
): ChorusAcceptTermsOfUseReply {
  return ChorusAcceptTermsOfUseReplyFromJSONTyped(json, false)
}

export function ChorusAcceptTermsOfUseReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChorusAcceptTermsOfUseReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : ChorusAcceptTermsOfUseResultFromJSON(json['result'])
  }
}

export function ChorusAcceptTermsOfUseReplyToJSON(
  value?: ChorusAcceptTermsOfUseReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: ChorusAcceptTermsOfUseResultToJSON(value.result)
  }
}
