/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface DevstoreServicePutWorkspaceEntryBody
 */
export interface DevstoreServicePutWorkspaceEntryBody {
  /**
   *
   * @type {string}
   * @memberof DevstoreServicePutWorkspaceEntryBody
   */
  key?: string
  /**
   *
   * @type {string}
   * @memberof DevstoreServicePutWorkspaceEntryBody
   */
  value?: string
}

/**
 * Check if a given object implements the DevstoreServicePutWorkspaceEntryBody interface.
 */
export function instanceOfDevstoreServicePutWorkspaceEntryBody(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function DevstoreServicePutWorkspaceEntryBodyFromJSON(
  json: any
): DevstoreServicePutWorkspaceEntryBody {
  return DevstoreServicePutWorkspaceEntryBodyFromJSONTyped(json, false)
}

export function DevstoreServicePutWorkspaceEntryBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DevstoreServicePutWorkspaceEntryBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    key: !exists(json, 'key') ? undefined : json['key'],
    value: !exists(json, 'value') ? undefined : json['value']
  }
}

export function DevstoreServicePutWorkspaceEntryBodyToJSON(
  value?: DevstoreServicePutWorkspaceEntryBody | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    key: value.key,
    value: value.value
  }
}
