/* tslint:disable */
/* eslint-disable */
/**
 * template backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendCredentials
 */
export interface TemplatebackendCredentials {
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendCredentials
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendCredentials
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendCredentials
     */
    totp?: string;
}

/**
 * Check if a given object implements the TemplatebackendCredentials interface.
 */
export function instanceOfTemplatebackendCredentials(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendCredentialsFromJSON(json: any): TemplatebackendCredentials {
    return TemplatebackendCredentialsFromJSONTyped(json, false);
}

export function TemplatebackendCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendCredentials {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'totp': !exists(json, 'totp') ? undefined : json['totp'],
    };
}

export function TemplatebackendCredentialsToJSON(value?: TemplatebackendCredentials | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'totp': value.totp,
    };
}

