/* tslint:disable */
/* eslint-disable */
/**
 * template backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendCreateUserResult
 */
export interface TemplatebackendCreateUserResult {
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendCreateUserResult
     */
    id?: string;
}

/**
 * Check if a given object implements the TemplatebackendCreateUserResult interface.
 */
export function instanceOfTemplatebackendCreateUserResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendCreateUserResultFromJSON(json: any): TemplatebackendCreateUserResult {
    return TemplatebackendCreateUserResultFromJSONTyped(json, false);
}

export function TemplatebackendCreateUserResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendCreateUserResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function TemplatebackendCreateUserResultToJSON(value?: TemplatebackendCreateUserResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

