/* tslint:disable */
/* eslint-disable */
/**
 * template backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { TemplatebackendGetUserResult } from './TemplatebackendGetUserResult'
import {
  TemplatebackendGetUserResultFromJSON,
  TemplatebackendGetUserResultFromJSONTyped,
  TemplatebackendGetUserResultToJSON
} from './TemplatebackendGetUserResult'

/**
 *
 * @export
 * @interface TemplatebackendGetUserReply
 */
export interface TemplatebackendGetUserReply {
  /**
   *
   * @type {TemplatebackendGetUserResult}
   * @memberof TemplatebackendGetUserReply
   */
  result?: TemplatebackendGetUserResult
}

/**
 * Check if a given object implements the TemplatebackendGetUserReply interface.
 */
export function instanceOfTemplatebackendGetUserReply(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function TemplatebackendGetUserReplyFromJSON(
  json: any
): TemplatebackendGetUserReply {
  return TemplatebackendGetUserReplyFromJSONTyped(json, false)
}

export function TemplatebackendGetUserReplyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TemplatebackendGetUserReply {
  if (json === undefined || json === null) {
    return json
  }
  return {
    result: !exists(json, 'result')
      ? undefined
      : TemplatebackendGetUserResultFromJSON(json['result'])
  }
}

export function TemplatebackendGetUserReplyToJSON(
  value?: TemplatebackendGetUserReply | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    result: TemplatebackendGetUserResultToJSON(value.result)
  }
}
