/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusRole } from './ChorusRole'
import {
  ChorusRoleFromJSON,
  ChorusRoleFromJSONTyped,
  ChorusRoleToJSON
} from './ChorusRole'

/**
 *
 * @export
 * @interface UserServiceCreateUserRoleBody
 */
export interface UserServiceCreateUserRoleBody {
  /**
   *
   * @type {ChorusRole}
   * @memberof UserServiceCreateUserRoleBody
   */
  role?: ChorusRole
}

/**
 * Check if a given object implements the UserServiceCreateUserRoleBody interface.
 */
export function instanceOfUserServiceCreateUserRoleBody(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function UserServiceCreateUserRoleBodyFromJSON(
  json: any
): UserServiceCreateUserRoleBody {
  return UserServiceCreateUserRoleBodyFromJSONTyped(json, false)
}

export function UserServiceCreateUserRoleBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserServiceCreateUserRoleBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    role: !exists(json, 'role') ? undefined : ChorusRoleFromJSON(json['role'])
  }
}

export function UserServiceCreateUserRoleBodyToJSON(
  value?: UserServiceCreateUserRoleBody | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    role: ChorusRoleToJSON(value.role)
  }
}
