/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspaceFile } from './ChorusWorkspaceFile'
import {
  ChorusWorkspaceFileFromJSON,
  ChorusWorkspaceFileFromJSONTyped,
  ChorusWorkspaceFileToJSON
} from './ChorusWorkspaceFile'
import type { ChorusWorkspaceFilePart } from './ChorusWorkspaceFilePart'
import {
  ChorusWorkspaceFilePartFromJSON,
  ChorusWorkspaceFilePartFromJSONTyped,
  ChorusWorkspaceFilePartToJSON
} from './ChorusWorkspaceFilePart'

/**
 *
 * @export
 * @interface WorkspaceFileServiceCompleteWorkspaceFileUploadBody
 */
export interface WorkspaceFileServiceCompleteWorkspaceFileUploadBody {
  /**
   *
   * @type {ChorusWorkspaceFile}
   * @memberof WorkspaceFileServiceCompleteWorkspaceFileUploadBody
   */
  file?: ChorusWorkspaceFile
  /**
   *
   * @type {Array<ChorusWorkspaceFilePart>}
   * @memberof WorkspaceFileServiceCompleteWorkspaceFileUploadBody
   */
  parts?: Array<ChorusWorkspaceFilePart>
}

/**
 * Check if a given object implements the WorkspaceFileServiceCompleteWorkspaceFileUploadBody interface.
 */
export function instanceOfWorkspaceFileServiceCompleteWorkspaceFileUploadBody(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function WorkspaceFileServiceCompleteWorkspaceFileUploadBodyFromJSON(
  json: any
): WorkspaceFileServiceCompleteWorkspaceFileUploadBody {
  return WorkspaceFileServiceCompleteWorkspaceFileUploadBodyFromJSONTyped(
    json,
    false
  )
}

export function WorkspaceFileServiceCompleteWorkspaceFileUploadBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WorkspaceFileServiceCompleteWorkspaceFileUploadBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    file: !exists(json, 'file')
      ? undefined
      : ChorusWorkspaceFileFromJSON(json['file']),
    parts: !exists(json, 'parts')
      ? undefined
      : (json['parts'] as Array<any>).map(ChorusWorkspaceFilePartFromJSON)
  }
}

export function WorkspaceFileServiceCompleteWorkspaceFileUploadBodyToJSON(
  value?: WorkspaceFileServiceCompleteWorkspaceFileUploadBody | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    file: ChorusWorkspaceFileToJSON(value.file),
    parts:
      value.parts === undefined
        ? undefined
        : (value.parts as Array<any>).map(ChorusWorkspaceFilePartToJSON)
  }
}
