/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusRole } from './ChorusRole'
import {
  ChorusRoleFromJSON,
  ChorusRoleFromJSONTyped,
  ChorusRoleToJSON
} from './ChorusRole'

/**
 *
 * @export
 * @interface WorkspaceServiceAddUserRoleInWorkspaceBody
 */
export interface WorkspaceServiceAddUserRoleInWorkspaceBody {
  /**
   *
   * @type {ChorusRole}
   * @memberof WorkspaceServiceAddUserRoleInWorkspaceBody
   */
  role?: ChorusRole
}

/**
 * Check if a given object implements the WorkspaceServiceAddUserRoleInWorkspaceBody interface.
 */
export function instanceOfWorkspaceServiceAddUserRoleInWorkspaceBody(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function WorkspaceServiceAddUserRoleInWorkspaceBodyFromJSON(
  json: any
): WorkspaceServiceAddUserRoleInWorkspaceBody {
  return WorkspaceServiceAddUserRoleInWorkspaceBodyFromJSONTyped(json, false)
}

export function WorkspaceServiceAddUserRoleInWorkspaceBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WorkspaceServiceAddUserRoleInWorkspaceBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    role: !exists(json, 'role') ? undefined : ChorusRoleFromJSON(json['role'])
  }
}

export function WorkspaceServiceAddUserRoleInWorkspaceBodyToJSON(
  value?: WorkspaceServiceAddUserRoleInWorkspaceBody | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    role: ChorusRoleToJSON(value.role)
  }
}
