/* tslint:disable */
/* eslint-disable */
/**
 * CHORUS backend API
 * CHORUS backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { ChorusWorkspaceFile } from './ChorusWorkspaceFile'
import {
  ChorusWorkspaceFileFromJSON,
  ChorusWorkspaceFileFromJSONTyped,
  ChorusWorkspaceFileToJSON
} from './ChorusWorkspaceFile'

/**
 *
 * @export
 * @interface WorkspaceFileServiceInitiateWorkspaceFileUploadBody
 */
export interface WorkspaceFileServiceInitiateWorkspaceFileUploadBody {
  /**
   *
   * @type {ChorusWorkspaceFile}
   * @memberof WorkspaceFileServiceInitiateWorkspaceFileUploadBody
   */
  file?: ChorusWorkspaceFile
}

/**
 * Check if a given object implements the WorkspaceFileServiceInitiateWorkspaceFileUploadBody interface.
 */
export function instanceOfWorkspaceFileServiceInitiateWorkspaceFileUploadBody(
  value: object
): boolean {
  let isInstance = true

  return isInstance
}

export function WorkspaceFileServiceInitiateWorkspaceFileUploadBodyFromJSON(
  json: any
): WorkspaceFileServiceInitiateWorkspaceFileUploadBody {
  return WorkspaceFileServiceInitiateWorkspaceFileUploadBodyFromJSONTyped(
    json,
    false
  )
}

export function WorkspaceFileServiceInitiateWorkspaceFileUploadBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WorkspaceFileServiceInitiateWorkspaceFileUploadBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    file: !exists(json, 'file')
      ? undefined
      : ChorusWorkspaceFileFromJSON(json['file'])
  }
}

export function WorkspaceFileServiceInitiateWorkspaceFileUploadBodyToJSON(
  value?: WorkspaceFileServiceInitiateWorkspaceFileUploadBody | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    file: ChorusWorkspaceFileToJSON(value.file)
  }
}
