export const data = [
  {
    id: 1,
    Status: 'Terminé',
    Date_recu: '23/12/20',
    BASEC: '2021-00095',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR001',
    Dpt: 'DNC',
    Service: 'OClin-DIM',
    PI_email: 'Jocelyne.Bloch@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      'Deep brain stimulation of the lateral hypothalamus to augment motor function of patients with spinal cord injury',
    Acronym: 'CIP',
    ORH_Oclin: 'OClin-DIM',
    Cat: 'C',
    Phase_Chapter: 'NA',
    Art34: 'Specific',
    CG_Cons_spécif: 'No',
    Mineurs: 'No',
    Population_vulnerable: 'No',
    ICF_Emergency: 'No',
    CRF: 'No',
    Langue: 'Anglais',
    Mono_Multicentric: 'Mono',
    Contrat: 'REDCap',
    Addendum: 'No',
    Registre_Nbr: 'NA',
    Biobanque: 'No',
    Open_Data: 'No',
    Master: 'NA',
    Doctorat: 'NA',
    Nbre_Revues: 'NA',
    Nbre_participants: 'NA',
    Commentaire: 'NA'
  },
  {
    id: 2,
    Status: 'Terminé',
    Date_recu: '17/11/20',
    BASEC: '2020-02930',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR002',
    Dpt: 'DC',
    Service: '',
    PI_email: 'erin.gonvers@unil.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      'Respiratory impact of local anaesthetic volume for an interscalene brachial plexus block with an extrafascial approach',
    Acronym: 'VOLBIS',
    ORH_Oclin: 'OClin-DIM',
    Cat: 'A',
    Phase_Chapter: 'II',
    Art34: 'Specific',
    CG_Cons_spécif: 'No',
    Mineurs: 'No',
    Population_vulnerable: '',
    ICF_Emergency: 'No',
    CRF: 'No',
    Langue: 'Français',
    Mono_Multicentric: 'Mono',
    Contrat: 'REDCap',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 3,
    Status: 'Terminé',
    Date_recu: '17/11/20',
    BASEC: '2021-00130',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR003',
    Dpt: 'DO',
    Service: '',
    PI_email: 'gillian.harkness@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      "investigue le niveau et l'impact de la fatigue liée au cancer auprès des patients atteints d'un cancer du poumon en traitement systémique et suivi par le centre des tumeurs thoraciques.",
    Acronym: 'NA',
    ORH_Oclin: 'ORH',
    Cat: 'A',
    Phase_Chapter: 'Ch2.',
    Art34: 'Specific',
    CG_Cons_spécif: 'No',
    Mineurs: 'No',
    Population_vulnerable: '',
    ICF_Emergency: 'No',
    CRF: 'No',
    Langue: 'Anglais',
    Mono_Multicentric: 'Mono',
    Contrat: 'REDCap',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 4,
    Status: 'Terminé',
    Date_recu: '17/11/20',
    BASEC: 'NA',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR004',
    Dpt: 'DMLP',
    Service: '',
    PI_email: 'Marko.Krstic@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      "Substitution des inhibiteurs du TNF-alpha par leurs biosimilaires dans le service de rhumatologie d'un hôpital universitaire.",
    Acronym: 'TNF',
    ORH_Oclin: 'Non-LRH',
    Cat: '',
    Phase_Chapter: '',
    Art34: '',
    CG_Cons_spécif: '',
    Mineurs: '',
    Population_vulnerable: '',
    ICF_Emergency: '',
    CRF: '',
    Langue: '',
    Mono_Multicentric: '',
    Contrat: '',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 5,
    Status: 'Terminé',
    Date_recu: '18/11/20',
    BASEC: '2020-02862',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR005',
    Dpt: 'PAMELA',
    Service: '',
    PI_email: 'xavier.crevoisier@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      'Posterior to anterior malleolar extended lateral approach to the ancle (PAMELA)',
    Acronym: 'PAMELA',
    ORH_Oclin: 'Oclin',
    Cat: 'A',
    Phase_Chapter: 'Ch4.',
    Art34: 'Specific',
    CG_Cons_spécif: 'No',
    Mineurs: 'No',
    Population_vulnerable: '',
    ICF_Emergency: 'No',
    CRF: 'No',
    Langue: 'Anglais',
    Mono_Multicentric: 'Mono',
    Contrat: 'REDCap',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 6,
    Status: 'Terminé',
    Date_recu: '18/11/20',
    BASEC: '2020-02854',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR006',
    Dpt: 'MAKO',
    Service: '',
    PI_email: 'Julien.Wegrzyn@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      'Robotic-arm assisted partial and total knee replacement: an observational cohort study',
    Acronym: 'MAKO',
    ORH_Oclin: 'ORH',
    Cat: 'A',
    Phase_Chapter: 'Ch2.',
    Art34: 'Specific',
    CG_Cons_spécif: 'No',
    Mineurs: 'No',
    Population_vulnerable: '',
    ICF_Emergency: 'No',
    CRF: 'No',
    Langue: 'Anglais',
    Mono_Multicentric: 'Mono',
    Contrat: 'REDCap',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 7,
    Status: 'Terminé',
    Date_recu: '19/11/20',
    BASEC: '2019-00155',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR007',
    Dpt: 'connectingAge',
    Service: '',
    PI_email: 'Murielle.bortolotti@chuv.ch',
    Main_contact_email_Study_co: 'Enrique.Castelao@chuv.ch',
    TITRE_du_protocole:
      'cardiovascular diseases and psychiatric disorders in the general population a prospective follow-up study.',
    Acronym: 'connectingAge',
    ORH_Oclin: 'ORH',
    Cat: 'A',
    Phase_Chapter: 'Ch2.',
    Art34: 'Specific',
    CG_Cons_spécif: 'No',
    Mineurs: 'No',
    Population_vulnerable: '',
    ICF_Emergency: 'No',
    CRF: 'No',
    Langue: 'Anglais',
    Mono_Multicentric: 'Mono',
    Contrat: 'REDCap',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 8,
    Status: 'Terminé',
    Date_recu: '19/11/20',
    BASEC: '2020-02836',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR008',
    Dpt: 'DRM',
    Service: '',
    PI_email: 'emilie.hochart@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      "Pendaisons : comparaison rétrospective d'une cohorte de patients décédés et de patients ayant survécu.",
    Acronym: 'NA',
    ORH_Oclin: 'ORH',
    Cat: 'A',
    Phase_Chapter: 'Ch3.',
    Art34: 'Art.34',
    CG_Cons_spécif: 'No',
    Mineurs: 'No',
    Population_vulnerable: '',
    ICF_Emergency: 'No',
    CRF: 'No',
    Langue: 'Français',
    Mono_Multicentric: 'Mono',
    Contrat: 'REDCap',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 9,
    Status: 'Terminé',
    Date_recu: '20/11/20',
    BASEC: '2020-02763',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR009',
    Dpt: 'DRM',
    Service: '',
    PI_email: 'francois.bochud@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      'Medical image quality: Model observers of radiologists performing a search task and AI algorithms that include the anatomical texture in low-contrast CT diagnostics',
    Acronym: 'NA',
    ORH_Oclin: 'ORH',
    Cat: 'A',
    Phase_Chapter: 'Ch4.',
    Art34: 'Yes',
    CG_Cons_spécif: 'No',
    Mineurs: 'No',
    Population_vulnerable: '',
    ICF_Emergency: 'No',
    CRF: 'No',
    Langue: 'Anglais',
    Mono_Multicentric: 'Mono',
    Contrat: 'NA',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 10,
    Status: 'Terminé',
    Date_recu: '20/11/20',
    BASEC: 'NA',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR010',
    Dpt: 'DO',
    Service: '',
    PI_email: 'sophie.voruz@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      'A novel heterozygous mutation in FGB (c.1231_1232 del GA) causing hypofibrinogenemia with a mild clinical history of bleeding in a large Swiss family.',
    Acronym: 'FGB',
    ORH_Oclin: 'Non-LRH',
    Cat: 'NA',
    Phase_Chapter: '',
    Art34: '',
    CG_Cons_spécif: '',
    Mineurs: '',
    Population_vulnerable: '',
    ICF_Emergency: '',
    CRF: '',
    Langue: '',
    Mono_Multicentric: '',
    Contrat: '',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 11,
    Status: 'Abandonné',
    Date_recu: '19/11/20',
    BASEC: '',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR011',
    Dpt: 'DC',
    Service: '',
    PI_email: 'laurence.pincet@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole: 'NA',
    Acronym: 'NA',
    ORH_Oclin: 'ORH',
    Cat: '',
    Phase_Chapter: 'Ch3.',
    Art34: '',
    CG_Cons_spécif: '',
    Mineurs: '',
    Population_vulnerable: '',
    ICF_Emergency: '',
    CRF: '',
    Langue: '',
    Mono_Multicentric: 'Mono',
    Contrat: '',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 12,
    Status: 'Terminé',
    Date_recu: '23/11/20',
    BASEC: '2020-02685',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR012',
    Dpt: 'Cardiologie',
    Service: '',
    PI_email: 'tobias.rutz@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      'Prevalence and impact of pulmonary anomalous venous return in turner syndrome',
    Acronym: 'TURNER',
    ORH_Oclin: 'ORH',
    Cat: '',
    Phase_Chapter: 'Ch3.',
    Art34: 'Art.34',
    CG_Cons_spécif: 'No',
    Mineurs: 'No',
    Population_vulnerable: '',
    ICF_Emergency: 'No',
    CRF: 'No',
    Langue: 'Anglais',
    Mono_Multicentric: 'Mono',
    Contrat: 'Excel',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 13,
    Status: 'Terminé',
    Date_recu: '23/11/20',
    BASEC: '2020-02798',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR013',
    Dpt: 'DM',
    Service: '',
    PI_email: 'rosemary.hottinger@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      "Analyse de précision des allergies IgE-médiées : impact de l'immunothérapie de désensibilisation",
    Acronym: 'Immuno-IgE',
    ORH_Oclin: 'ORH',
    Cat: 'A',
    Phase_Chapter: 'Ch2.',
    Art34: 'Specific',
    CG_Cons_spécif: 'No',
    Mineurs: 'No',
    Population_vulnerable: '',
    ICF_Emergency: 'No',
    CRF: 'No',
    Langue: 'Français',
    Mono_Multicentric: 'Mono',
    Contrat: 'REDCap',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 14,
    Status: 'Terminé',
    Date_recu: '23/11/20',
    BASEC: '2020-02766',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR014',
    Dpt: 'DFME',
    Service: '',
    PI_email: 'floriane.naef@unil.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole:
      "Évaluation des besoins d'un outil d'information et suivi thérapeutique en oncologie pédiatrique",
    Acronym: 'Outil',
    ORH_Oclin: 'Non-LRH',
    Cat: '',
    Phase_Chapter: '',
    Art34: '',
    CG_Cons_spécif: 'Yes',
    Mineurs: '',
    Population_vulnerable: '',
    ICF_Emergency: '',
    CRF: '',
    Langue: '',
    Mono_Multicentric: '',
    Contrat: '',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  },
  {
    id: 15,
    Status: 'Abandonné',
    Date_recu: '25/11/20',
    BASEC: '',
    BPR_First: '',
    CRC_Recomm_suivies: '',
    CODE_BPR: 'BPR015',
    Dpt: 'STEREOPULM',
    Service: '',
    PI_email: 'remy.kinj@chuv.ch',
    Main_contact_email_Study_co: '',
    TITRE_du_protocole: 'Radiothérapie Stéréotaxique Pulmonaire au CHUV.',
    Acronym: 'STEREOPULM',
    ORH_Oclin: 'ORH',
    Cat: 'A',
    Phase_Chapter: 'Ch3.',
    Art34: '',
    CG_Cons_spécif: 'CG',
    Mineurs: 'No',
    Population_vulnerable: '',
    ICF_Emergency: '',
    CRF: '',
    Langue: 'Français',
    Mono_Multicentric: 'Mono',
    Contrat: '',
    Addendum: '',
    Registre_Nbr: '',
    Biobanque: '',
    Open_Data: '',
    Master: '',
    Doctorat: '',
    Nbre_Revues: '',
    Nbre_participants: '',
    Commentaire: ''
  }
]
