pipeline {
    agent {
        docker {
            image 'docker:latest'
        }
    }
    environment {
	    E_MAIL_INFORM = 'paloma.cito@chuv.ch'
        COMPOSE_PROJECT_NAME = 'my-app'
	}

    stages {

        stage('Build') {
            steps {
                sh 'ls -l'
                sh 'ls -l frontend/'
                sh 'docker-compose -f docker/docker-compose.yml build test'
            }
        }

        stage('Run containers') {
            steps {
                //sh 'docker-compose -f docker/docker-compose.yml up -d test --remove-orphans'
                sh 'docker run  t3-app-test ls -la /app'
                // sh 'docker-compose run --rm app pytest -v'
            }
        }
        stage('Run Tests') {
            steps {
                //sh 'docker exec t3-app-test pnpm test'
                //sh 'docker-compose -f docker/docker-compose.yml run --rm dev pnpm run test'
                sh 'sleep 60'
                sh 'docker logs t3-app-test'
                // sh 'docker logs t3-app-dev'
                // sh 'docker logs t3-app-prod'
            }
        }
        stage("User notification?") {
            when {
                expression {
                   return null
                   //return params.SEND_EMAIL TODO
                }
            }
            steps {
                emailext subject: "${env.JOB_NAME} - build SUCCESS (${env.BUILD_NUMBER})", body: "${env.BUILD_URL}console", to: "${E_MAIL_INFORM}"
            }
        }
    }
    post {
        always {
            // always (cannot be empty)
            sh 'docker-compose -f docker/docker-compose.yml down'
            echo 'Email notification'

            //junit '../tests/result.xml' TODO
         }
        failure {
             // only in case of failure
             emailext subject: "${env.JOB_NAME} - build FAILURE (${env.BUILD_NUMBER})", body: "${env.BUILD_URL}console", to: "${E_MAIL_INFORM}";
         }
        unstable {
             // only if the run was marked as unstable
             emailext subject: "${env.JOB_NAME} - build UNSTABLE (${env.BUILD_NUMBER})", body: "${env.BUILD_URL}console", to: "${E_MAIL_INFORM}";
         }
    }
}
