pipeline {
    agent {
        docker {
            image 'docker:latest'
        }
    }
    environment {
	    E_MAIL_INFORM = 'paloma.cito@chuv.ch'
        COMPOSE_PROJECT_NAME = 'my-app'
	}

    stages {
        stage('Build') {
            steps {
                sh 'docker-compose -f docker/docker-compose.yml build'
            }
        }

        stage('Run containers') {
            steps {
                sh 'docker-compose -f docker/docker-compose.yml up -d  --remove-orphans'

            }
        }
        stage('Run Tests') {
            steps {
                sh 'docker-compose -f docker/docker-compose.yml run --rm dev pnpm test'
                sh 'docker logs t3-app-dev'
                sh 'docker logs t3-app-prod'
            }
        }

        stage("User notification?") {
            when {
                expression {
                   return params.SEND_EMAIL
                }
            }
            steps {
                emailext subject: "${env.JOB_NAME} - build SUCCESS (${env.BUILD_NUMBER})", body: "${env.BUILD_URL}console", to: "${E_MAIL_INFORM}"
            }
        }
    }
    post {
        always {
            // always (cannot be empty)
            sh 'docker-compose -f docker/docker-compose.yml down'
            echo 'Email notification'

            //junit '../tests/result.xml' TODO
         }
        failure {
             // only in case of failure
             emailext subject: "${env.JOB_NAME} - build FAILURE (${env.BUILD_NUMBER})", body: "${env.BUILD_URL}console", to: "${E_MAIL_INFORM}";
         }
        unstable {
             // only if the run was marked as unstable
             emailext subject: "${env.JOB_NAME} - build UNSTABLE (${env.BUILD_NUMBER})", body: "${env.BUILD_URL}console", to: "${E_MAIL_INFORM}";
         }
    }
}
