import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

type GuidePage = {
  id: string
  title: string
  shortTitle: string
  content: string
  sourceUrl: string
}

type GuideSection = {
  id: string
  label: string
  pages: GuidePage[]
}

const projectRoot = process.cwd()
const sourceRoot = path.resolve(
  process.argv[2] ??
    path.join(projectRoot, '../chorus-tre.github.io/docs/user-guide')
)
const outputPath = path.join(projectRoot, 'src/generated/user-guide.ts')

function titleFromMarkdown(markdown: string, fallback: string) {
  return markdown.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? fallback
}

function cleanMarkdown(markdown: string) {
  return markdown
    .replace(/^---[\s\S]*?---\s*/, '')
    .replace(/^#\s+.+\n+/, '')
    .replace(/<Accordion[^>]*>/g, '')
    .replace(/<\/Accordion>/g, '')
    .replace(/<AccordionSection title="([^"]+)">/g, '## $1')
    .replace(/<\/AccordionSection>/g, '')
    .replace(/<div[\s\S]*<\/div>/g, '')
    .trim()
}

async function page(
  filePath: string,
  id: string,
  sourcePath: string
): Promise<GuidePage> {
  const markdown = await readFile(filePath, 'utf8')
  const fallback = id.replaceAll('-', ' ')
  const title = titleFromMarkdown(markdown, fallback)
  return {
    id,
    title,
    shortTitle: title.replace(
      /^(Access|Create|Open|Launch) (the |a |an )?/i,
      ''
    ),
    content: cleanMarkdown(markdown) || '_More content is coming soon._',
    sourceUrl: `https://chorus-tre.github.io/docs/user-guide/${sourcePath}`
  }
}

async function sidebarPosition(filePath: string) {
  const markdown = await readFile(filePath, 'utf8')
  return Number(
    markdown.match(/sidebar_position:\s*(\d+)/)?.[1] ?? Number.MAX_SAFE_INTEGER
  )
}

async function main() {
  const gettingStartedDir = path.join(sourceRoot, 'getting-started')
  const gettingStartedFiles = (await readdir(gettingStartedDir)).filter(
    (name) => /^\d+_.+\.md$/.test(name)
  )
  const positionedFiles = await Promise.all(
    gettingStartedFiles.map(async (name) => ({
      name,
      position: await sidebarPosition(path.join(gettingStartedDir, name))
    }))
  )
  positionedFiles.sort((a, b) => a.position - b.position)

  const overview = await page(path.join(sourceRoot, 'index.md'), 'overview', '')
  overview.content =
    'This guide offers a quick start with CHORUS and resources for onboarding, working with data, launching applications, and collaborating securely.\n\nChoose a section above or continue to **Getting started**.'

  const sections: GuideSection[] = [
    { id: 'overview', label: 'Overview', pages: [overview] },
    {
      id: 'getting-started',
      label: 'Getting started',
      pages: await Promise.all(
        positionedFiles.map(({ name }) => {
          const id = name
            .replace(/^\d+_/, '')
            .replace(/\.md$/, '')
            .replaceAll('_', '-')
          const sourceName = name.replace(/^\d+_/, '').replace(/\.md$/, '')
          return page(
            path.join(gettingStartedDir, name),
            id,
            `getting-started/${sourceName}`
          )
        })
      )
    },
    {
      id: 'tutorials',
      label: 'Tutorials',
      pages: [
        await page(
          path.join(sourceRoot, 'tutorials.md'),
          'tutorials',
          'tutorials'
        )
      ]
    },
    {
      id: 'faq',
      label: 'FAQ',
      pages: [await page(path.join(sourceRoot, 'faq.md'), 'faq', 'faq')]
    },
    {
      id: 'glossary',
      label: 'Glossary',
      pages: [
        await page(path.join(sourceRoot, 'glossary.md'), 'glossary', 'glossary')
      ]
    }
  ]

  const generated = `// Generated by scripts/process-user-guide.ts. Do not edit manually.\n\nexport const userGuide = ${JSON.stringify(sections, null, 2)} as const\n`
  await mkdir(path.dirname(outputPath), { recursive: true })
  await writeFile(outputPath, generated)
  console.log(
    `Processed ${sections.flatMap((section) => section.pages).length} guide pages into ${outputPath}`
  )
}

await main()
