'use client'

import { zodResolver } from '@hookform/resolvers/zod'
import { Pencil, Trash2 } from 'lucide-react'
import { startTransition, useActionState, useEffect, useState } from 'react'
import { useFieldArray, useForm } from 'react-hook-form'
import { z } from 'zod'

import { deleteUserRole, updateUser } from '@/view-model/user-view-model'
import { Button } from '~/components/button'
import { CreateUserRoleDialog } from '~/components/forms/create-user-role-dialog'
import { Badge } from '~/components/ui/badge'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from '~/components/ui/dialog'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage
} from '~/components/ui/form'
import { Input } from '~/components/ui/input'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '~/components/ui/table'
import { Result } from '~/domain/model'
import { Role, User, UserUpdateSchema } from '~/domain/model/user'

import { toast } from '../hooks/use-toast'

type FormData = z.infer<typeof UserUpdateSchema>

export function UserEditDialog({
  user,
  onUserUpdated,
  isControlled = false
}: {
  user: User
  onUserUpdated: () => void
  isControlled?: boolean
}) {
  const [dialogOpen, setDialogOpen] = useState(false)
  const [internalUser, setInternalUser] = useState(user)
  const [hasBeenModified, setHasBeenModified] = useState(false)

  useEffect(() => {
    if (dialogOpen) {
      setInternalUser(user)
      setHasBeenModified(false)
    }
  }, [dialogOpen, user])

  const form = useForm<FormData>({
    resolver: zodResolver(UserUpdateSchema),
    defaultValues: {
      id: internalUser.id,
      firstName: internalUser.firstName,
      lastName: internalUser.lastName,
      username: internalUser.username,
      password: '',
      rolesWithContext: internalUser.rolesWithContext || []
    }
  })

  useEffect(() => {
    form.reset({
      id: internalUser.id,
      firstName: internalUser.firstName,
      lastName: internalUser.lastName,
      username: internalUser.username,
      password: '',
      rolesWithContext: internalUser.rolesWithContext || []
    })
  }, [internalUser, form])

  const { fields, remove } = useFieldArray({
    control: form.control,
    name: 'rolesWithContext'
  })

  const [state, formAction] = useActionState(updateUser, {} as Result<User>)
  const [isDeletingRole, setIsDeletingRole] = useState<string | null>(null)

  useEffect(() => {
    if (state?.error || state?.issues) {
      // Display validation errors in toast
      if (state.issues && state.issues.length > 0) {
        const errorMessages = state.issues
          .map((issue) => {
            const path = issue.path.join('.')
            return path ? `${path}: ${issue.message}` : issue.message
          })
          .join('\n')

        toast({
          title: 'Validation Error',
          description: errorMessages,
          variant: 'destructive'
        })
      } else if (state.error) {
        toast({
          title: 'Error updating user',
          description: state.error,
          variant: 'destructive'
        })
      }
    } else if (state?.data) {
      setDialogOpen(false)
    }
  }, [state])

  const handleRoleAdded = (updatedUser: User) => {
    setInternalUser(updatedUser)
    setHasBeenModified(true)
  }

  const handleRemoveRole = async (role: Role, index: number) => {
    if (!role.id && !role.name) {
      // If role doesn't have an ID or name, just remove it from the form
      remove(index)
      return
    }

    // The role from the form has a UUID (generated by react-hook-form)
    // We need to find the corresponding role in internalUser.rolesWithContext
    // which has the numeric ID returned by the API
    let roleIdentifier: string | undefined

    if (role.id && /^\d+$/.test(role.id)) {
      // If role.id is already numeric, use it directly
      roleIdentifier = role.id
    } else {
      // Find the matching role in internalUser.rolesWithContext by comparing name and context
      const matchingRole = internalUser.rolesWithContext?.find((r) => {
        // Compare role name
        if (r.name !== role.name) return false

        // Compare context (all keys and values must match)
        const roleContext = role.context || {}
        const rContext = r.context || {}

        // Check if all keys in role.context exist in r.context with same values
        const roleContextKeys = Object.keys(roleContext)
        const rContextKeys = Object.keys(rContext)

        if (roleContextKeys.length !== rContextKeys.length) return false

        return roleContextKeys.every(
          (key) => roleContext[key] === rContext[key]
        )
      })

      if (matchingRole?.id && /^\d+$/.test(matchingRole.id)) {
        roleIdentifier = matchingRole.id
      }
    }

    if (!roleIdentifier) {
      toast({
        title: 'Error deleting role',
        description:
          'Could not find numeric role ID. The role may not be persisted yet.',
        variant: 'destructive'
      })
      return
    }

    setIsDeletingRole(role.id || role.name || '')
    try {
      const result: Result<User> = await deleteUserRole(
        internalUser.id,
        roleIdentifier
      )

      if (result && 'error' in result && result.error) {
        toast({
          title: 'Error deleting role',
          description: result.error,
          variant: 'destructive'
        })
      } else if (result && 'data' in result && result.data) {
        // Update internal user with the updated data from server
        setInternalUser(result.data)
        setHasBeenModified(true)
        toast({
          title: 'Role deleted',
          description: 'Role has been successfully removed',
          variant: 'default'
        })
      }
    } catch (error) {
      toast({
        title: 'Error deleting role',
        description: error instanceof Error ? error.message : String(error),
        variant: 'destructive'
      })
    } finally {
      setIsDeletingRole(null)
    }
  }

  const handleOpenChange = (isOpen: boolean) => {
    setDialogOpen(isOpen)
    if (!isOpen && hasBeenModified) {
      onUserUpdated()
    }
  }

  const onSubmit = (data: z.infer<typeof UserUpdateSchema>) => {
    const formData = new FormData()
    formData.append('id', data.id)
    formData.append('username', data.username)
    formData.append('firstName', data.firstName)
    formData.append('lastName', data.lastName)
    formData.append('password', data.password)

    startTransition(() => {
      formAction(formData)
    })
  }

  return (
    <Dialog open={dialogOpen} onOpenChange={handleOpenChange}>
      {!isControlled && (
        <DialogTrigger asChild>
          <Button
            variant="ghost"
            aria-label={`Edit user ${user.firstName} ${user.lastName}`}
          >
            <Pencil className="h-4 w-4" aria-hidden="true" />
            <span className="sr-only">Edit user</span>
          </Button>
        </DialogTrigger>
      )}
      <DialogContent className="">
        <DialogHeader>
          <DialogTitle>Edit User</DialogTitle>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <input type="hidden" {...form.register('id')} />
            <FormField
              control={form.control}
              name="firstName"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>First Name</FormLabel>
                  <FormControl>
                    <Input {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="lastName"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Last Name</FormLabel>
                  <FormControl>
                    <Input {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="username"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Username</FormLabel>
                  <FormControl>
                    <Input {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="password"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Password</FormLabel>
                  <FormControl>
                    <Input
                      type="password"
                      {...field}
                      placeholder="Leave blank to keep current password"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="rolesWithContext"
              render={() => (
                <FormItem>
                  <FormLabel className="flex items-center justify-between gap-2">
                    Roles ({fields.length}){' '}
                    <CreateUserRoleDialog
                      userId={internalUser.id}
                      onRoleAdded={handleRoleAdded}
                    />
                  </FormLabel>
                  <FormControl>
                    <div className="max-h-60 overflow-auto">
                      <Table
                        className=""
                        aria-label={`User roles management table with ${fields.length} role${fields.length !== 1 ? 's' : ''}`}
                      >
                        <caption className="sr-only">
                          User roles management table showing roles and
                          available actions. Use arrow keys to navigate.
                        </caption>
                        <TableHeader>
                          <TableRow>
                            <TableHead scope="col">Role</TableHead>
                            <TableHead scope="col">Workspace</TableHead>
                            <TableHead scope="col">Workbench</TableHead>
                            <TableHead scope="col">User</TableHead>
                            <TableHead scope="col">Actions</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          {fields.map((r, i) => (
                            <TableRow key={r.id} className="border-muted/50">
                              <TableCell className="p-2">
                                <Badge key={`role-badge-${r.name}-${i}`}>
                                  {r.name}
                                </Badge>
                              </TableCell>
                              <TableCell className="p-2">
                                {r.context?.workspace ? (
                                  <Badge
                                    className="bg-red-400"
                                    key={`role-badge-${r.name}-${i}`}
                                  >
                                    {r.context?.workspace}
                                  </Badge>
                                ) : null}
                              </TableCell>
                              <TableCell className="p-2">
                                {r.context?.workbench ? (
                                  <Badge
                                    className="bg-orange-400"
                                    key={`role-badge-${r.name}-${i}`}
                                  >
                                    {r.context?.workbench}
                                  </Badge>
                                ) : null}
                              </TableCell>
                              <TableCell className="p-2">
                                {r.context?.user ? (
                                  <Badge
                                    className="bg-yellow-400"
                                    key={`role-badge-${r.name}-${i}`}
                                  >
                                    {r.context?.user}
                                  </Badge>
                                ) : null}
                              </TableCell>
                              <TableCell className="p-2">
                                <Button
                                  variant="ghost"
                                  aria-label="Delete role"
                                  onClick={() => handleRemoveRole(r, i)}
                                  disabled={isDeletingRole === (r.id || r.name)}
                                >
                                  <Trash2
                                    className="h-4 w-4"
                                    aria-hidden="true"
                                  />
                                </Button>
                              </TableCell>
                            </TableRow>
                          ))}
                        </TableBody>
                      </Table>
                    </div>
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <Button type="submit">Save Changes</Button>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  )
}
